
package ws.internal.payment.payoo.jax;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UniGWS", targetNamespace = "UniGWS", wsdlLocation = "file:/D:/Temp/ws/UniGWS.wsdl")
public class UniGWS
    extends Service
{

    private final static URL UNIGWS_WSDL_LOCATION;
    private final static WebServiceException UNIGWS_EXCEPTION;
    private final static QName UNIGWS_QNAME = new QName("UniGWS", "UniGWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Temp/ws/UniGWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UNIGWS_WSDL_LOCATION = url;
        UNIGWS_EXCEPTION = e;
    }

    public UniGWS() {
        super(__getWsdlLocation(), UNIGWS_QNAME);
    }

    public UniGWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), UNIGWS_QNAME, features);
    }

    public UniGWS(URL wsdlLocation) {
        super(wsdlLocation, UNIGWS_QNAME);
    }

    public UniGWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNIGWS_QNAME, features);
    }

    public UniGWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UniGWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UniGWSSoap
     */
    @WebEndpoint(name = "UniGWSSoap")
    public UniGWSSoap getUniGWSSoap() {
        return super.getPort(new QName("UniGWS", "UniGWSSoap"), UniGWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UniGWSSoap
     */
    @WebEndpoint(name = "UniGWSSoap")
    public UniGWSSoap getUniGWSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("UniGWS", "UniGWSSoap"), UniGWSSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UNIGWS_EXCEPTION!= null) {
            throw UNIGWS_EXCEPTION;
        }
        return UNIGWS_WSDL_LOCATION;
    }

}
