
package ws.internal.payment.payoo.jax;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UniGWSSoap", targetNamespace = "UniGWS")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UniGWSSoap {


    /**
     * 
     * @param request
     * @return
     *     returns ws.internal.payment.payoo.test.UniGWSResponse
     */
    @WebMethod(operationName = "Execute", action = "UniGWS/Execute")
    @WebResult(name = "ExecuteResult", targetNamespace = "UniGWS")
    @RequestWrapper(localName = "Execute", targetNamespace = "UniGWS", className = "ws.internal.payment.payoo.test.Execute")
    @ResponseWrapper(localName = "ExecuteResponse", targetNamespace = "UniGWS", className = "ws.internal.payment.payoo.test.ExecuteResponse")
    public UniGWSResponse execute(
        @WebParam(name = "request", targetNamespace = "UniGWS")
        UniGWSRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns ws.internal.payment.payoo.test.UniGWSResponse
     */
    @WebMethod(operationName = "Execute2", action = "UniGWS/Execute2")
    @WebResult(name = "Execute2Result", targetNamespace = "UniGWS")
    @RequestWrapper(localName = "Execute2", targetNamespace = "UniGWS", className = "ws.internal.payment.payoo.test.Execute2")
    @ResponseWrapper(localName = "Execute2Response", targetNamespace = "UniGWS", className = "ws.internal.payment.payoo.test.Execute2Response")
    public UniGWSResponse execute2(
        @WebParam(name = "request", targetNamespace = "UniGWS")
        UniGWSRequest request);

}
