/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scb.com.vn.message;

/**
 *
 * @author minhndb
 */
public class CardwordMessage
{
    public enum ErrorCodeEnum
    {
        /* CARDWORD ERROR CODE */
        COMPLETE_RESPONSE_WITHOUT_ERROR("000"),
        NO_RECORD_FOUND("001"),
        DUPLICATE_SEQUENSE_NUMBER("002"),
        SESSION_EXPIRED("003"),
        NOT_APPROVE("004"),
        TIMEOUT("005"),
        EXCEPTION("009"),
        INVALID_FI_CODE("010"),
        INVALID_CARD_INDICATOR("011"),
        INVALID_CARD_TYPE("012"),
        INVALID_NAME("013"),
        INVALID_EMBOSS_NAME("014"),
        INVALID_NEW_ID_INDICATOR("015"),
        INVALID_NEW_ID("016"),
        INVALID_OLD_IC("017"),
        INVALID_DOB("018"),
        INVALID_GENDER("019"),
        INVALID_COUNTRY("020"),
        INVALID_RACE("021"),
        INVALID_MARITAL_STATUS("022"),
        INVALID_MOTHER_MAIDEN_NAME("023"),
        INVALID_BILLING_OPTION("024"),
        INVALID_SOURCE_CODE("025"),
        INVALID_SALE_OFFICER_CODE("026"),
        INVALID_BRANCH_CODE("027"),
        INVALID_PROMOTION_CODE("028"),
        INVALID_RESIDENCE_ADDRESS("029"),
        INVALID_RESIDENCE_POSTCODE("030"),
        INVALID_RESIDENCE_TOWN("031"),
        INVALID_RESIDENCE_COUNTRY("032"),
        INVALID_RESIDENCE_PHONE_NUMBER("033"),
        INVALID_RESIDENCE_TYPE("034"),
        INVALID_RESIDENCE_SINCE("035"),
        INVALID_MAILING_ADDRESS("036"),
        INVALID_MAILLING_POSTCODE("037"),
        INVALID_MAILING_TOWN("038"),
        INVALID_MAILING_COUNTRY("039"),
        INVALID_MAILING_PHONE_NUMBER("040"),
        INVALID_DELIVERY_OFFICE_NAME("041"),
        INVALID_DELIVERY_OFFICE_DEPARTMENT_NAME("042"),
        INVALID_DELIVERY_ADDRESS("043"),
        INVALID_DELIVERY_POSTCODE("044"),
        INVALID_DELIVERY_TOWN("045"),
        INVALID_DELIVERY_COUNTRY("046"),
        INVALID_OFFICE_NAME("047"),
        INVALID_OFFICE_ADDRESS("048"),
        INVALID_OFFICE_POSTCODE("049"),
        INVALID_OFFICE_TOWN("050"),
        INVALID_OFFICE_COUNTRY("051"),
        INVALID_OFFICE_PHONE_NUMBER("052"),
        INVALID_OFFICE_FAX("053"),
        INVALID_INDUSTRY_CODE("054"),
        INVALID_POSITION_HELD("055"),
        INVALID_ANNUAL_INCOME("056"),
        INVALID_EMAIL_ADDRESS("057"),
        INVALID_MOBILE_NUMBER("058"),
        INVALID_PREVIOUS_EMPLOYER_NAME("059"),
        INVALID_PREVIOUS_EMPLOYER_ADDRESS("060"),
        INVALID_PREVIOUS_EMPLOYER_POSTCODE("061"),
        INVALID_PREVIOUS_EMPLOYER_TOWN("062"),
        INVALID_PREVIOUS_EMPOYER_COUNTRY("063"),
        INVALID_PREVIOUS_EMPLOYER_PHONE_NUMBER("064"),
        INVALID_PREVIOUS_EMPLOYER_YEAR_SINCE("065"),
        INVALID_SPOUSE_NAME("066"),
        INVALID_SPOUSE_NEW_ID_NUMBER("067"),
        INVALID_SPOUSE_ADDRESS("068"),
        INVALID_SPOUSE_POSTCODE("069"),
        INVALID_SPOUSE_TOWN("070"),
        INVALID_SPOUSE_COUNTRY("071"),
        INVALID_SPOUSE_PHONE_NUMBER("072"),
        INVALID_EMERGENCY_CONTACT_PERSON("073"),
        INVALID_EMERGENCY_CONTACT_NUMBER("074"),
        INVALID_EMERGENCY_MOBILE_NUMBER("075"),
        INVALID_ANSWER_FOR_QUESTION_1("076"),
        INVALID_ANSWER_FOR_QUESTION_2("077"),
        INVALID_ANSWER_FOR_QUESTION_3("078"),
        INVALID_ANSWER_FOR_QUESTION_4("079"),
        INVALID_ANSWER_FOR_QUESTION_5("080"),
        INVALID_PAN("081"),
        INVALID_EXPIRY_DATE("082"),
        INVALID_CURRENCY_CODE("083"),
        INVALID_AMOUNT("084"),
        INVALID_BENEFICIARY_PAN("085"),
        INVALID_BENEFICIARY_NAME("086"),
        INVALID_POINT_REDEEM("087"),
        INVALID_STATEMENT_MONTH("088"),
        INVALID_USER_ID_OR_PASSWORD("089"),
        OVER_ALLOWABLE_MAXIMUM_NO_OF_OCCURRENCES("090"),
        INVALID_TITLE("91"),
        INVALID_PLACE_OF_BIRTH("092"),
        INVALID_PR_STATUS("093"),
        INVALID_IMMIGRATION_VISA_EXPIRY_DATE("094"),
        INVALID_WORK_NATURE("095"),
        INVALID_NATURE_OF_BUSINESS("096"),
        INVALID_RESIDENCE_STATE("097"),
        INVALID_MAILING_STATE("098"),
        INVALID_DELIVERY_STATE("099"),
        INVALID_OFFICE_STATE("100"),
        INVALID_MINISTERIAL_OR_DIPLOMATIC("101"),
        INVALID_CRN("102"),
        INVALID_SOURCE_SYSTEM("103"),
        INVALID_REFERENCE_NUMBER("104"),
        INVALID_RELOAD_METHOD("105"),
        INVALID_RELOAD_SOURCE("106"),
        INVALID_TRANSFEROR_PAN("107"),
        INVALID_SURCHARGE_FEE("109"),
        INVALID_BENEFICIARY_EXPIRY_DATE("110"),
        INVALID_SOURCE_CODE_AND_PROMOTION_CODE_MAPPING("111"),
        DUPLICATE_APPLICATION("112"),
        INVALID_LAST_UPDATE_TIMESTAMP("113"),
        CARD_ALREADY_ACTIVATED("114"),
        THIS_RECORD_HAS_BEEN_DELETED_BY_NOTHER_UER("115"),
        PLEASE_PORVIDE_AT_LEAST_1_SECURITY_VALIDATION("116"),
        INVALID_ACTION("117"),
        INVALID_PIN("118"),
        CARD_ALREADY_LINKED("119"),
        INVALID_DATA("120"),
        ONLY_NEW_ID_POLICE_AND_MILITARY_IS_ACCEPTED_FOR_MALAYSIAN("121"),
        INVALID_DELIVERY_OPTION("122"),
        INVALID_DELIVERY_CENTER_CODE("123"),
        INVALID_EMERGENCY_RELATION("124"),
        INVALID_OCCUPATION("125"),
        INVALID_TRANSACTION_DATE("126"),
        INVALID_TRANSACTION_TIME("127"),
        INVALID_MERCHANT_ID("128"),
        INVALID_TERMINAL_ID("129"),
        MORE_THAN_1_TRANSACTION_FOUND_PLEASE_CALL_CUSTOMER_SUPPORT("130"),
        INVALID_CVV2("131"),
        DUPLICATE_REFERENCE_NUMBER("132"),
        INVALID_APPLICATION_TYPE("133"),
        INVALID_CORPORATE_AND_GOVERNMENT_PAYMENT_FLAG("134"),
        INVALID_PREFERRED_LANGUAGE("135"),
        INVALID_ALTERNATE_EMAIL("136"),
        CARD_ACTIVATION_FAILED("137"),
        INVALID_MEMBER_ID("138"),
        INVALID_RECOMMENDER_PAN("139"),
        INVALID_RECOMMENDER_NAME("140"),
        APPLICATION_CRITERIA_FALIED("141"),
        MOBILE_NUMBER_NOT_FOUND("142"),
        INVALID_ADDITIONAL_REFERENCE("143"),
        PAN_NOT_IN_GOOD_STATUS("145"),
        INVALID_SECURITY_CODE("146"),
        CARD_EXPIRED("147"),
        INVALID_SECURITY("148"),
        COMPROMISED_CARD_NUMBER("149"),
        CARD_APPLICATION_ALREADY_CREATED("150"),
        INVALID_APPLICATION_MEMBER_ID_IS_RESERVED_FOR_PRE("151"),
        CARD_ALREADY_BLOCKED_FOR_INTERNET_TRANSACTION("152"),
        CARD_ALREADY_UNBLOCKED_FOR_INTERNET_TRANSACTION("153"),
        CARD_ALREADY_UNBLOCKED_FOR_POS_TRANSACTION("154"),
        CARD_ALREADY_BLOCKED_FOR_POS_TRANSACTION("155"),
        INVALID_ADJUSTMENT_CODE("156"),
        INVALID_ACCOUNT_INDICATOR("157"),
        INVALID_ACTION_TYPE("158"),
        INVALID_ACTION_CODE("159"),
        INVALID_ADJUSTMENT_AMOUNT("160"),
        INVALID_OFFICER_ID("161"),
        INVALID_REWARD_ACTION("162"),
        INSUFFICIENT_POINTS("163"),
        
        CARDWORD_IS_MAINTANING("1100"),
        UNKNOW_CARDWORD_MESSAGE("1101"),
        CARDWORD_OK("2000"),
        CARDWORD_OK_DBI_FAILED("2001"),
        CARDWORD_RETURN_DBI_FAILED("2002")
        ;
        
        private String code;

        private ErrorCodeEnum(String c)
        {
            code = c;
        }
        
        public static ErrorCodeEnum get(String value)
        {
            ErrorCodeEnum[] values = ErrorCodeEnum.values();
            for (ErrorCodeEnum val : values)
            {
                if (val.getValue().equals(value))
                {
                    return val;
                }
            }
            return ErrorCodeEnum.UNKNOW_CARDWORD_MESSAGE;
        }
        
        public String getValue()
        {
            return code;
        }
    }
    
    public static String getErrorCodeDescription(ErrorCodeEnum index)
    {
        switch (index)
        {
            case COMPLETE_RESPONSE_WITHOUT_ERROR:
                return ErrorCodeEnum.COMPLETE_RESPONSE_WITHOUT_ERROR.toString();
            default:
                return index.toString();
        }
    }
    
}
