/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scb.com.vn.message;

/**
 *
 * @author minhndb
 */
public class CommonMessage
{
    public enum CommontEnum
    {
        /* COMMON */
        DATA_IS_VALID("1000"),
        INVALID_PROVIDER("1001"),
        INVALID_MERCARDNAME("1002"),
        INVALID_FUNDINGSOURCE("1003"),
        INVALID_CHANNEL("1004"),
        INVALID_REFERENCENO("1005"),
        INVALID_LOC4DIGIT("1006"),
        INVALID_AMOUNT("1007"),
        INVALID_CCY("1008"),
        INVALID_CCYCODE("1009"),
        INVALID_MERID("1010"),
        INVALID_DATETIME("1011"),
        INVALID_MERFNAME("1012"),
        INVALID_MERLNAME("1013"),
        INVALID_MERADDRESS("1014"),
        INVALID_MERCITY("1015"),
        INVALID_MERCOUNTRY("1016"),
        INVALID_MERCOUTRYSUB("1017"),
        INVALID_MERPOSTALCODE("1018"),
        INVALID_MERCATEGORY("1019"),
        INVALID_SENDERACC("1020"),
        INVALID_SENDERFNAME("1021"),
        INVALID_SENDERLNAME("1022"),
        INVALID_SENDERADDRESS("1023"),
        INVALID_SENDERCITY("1024"),
        INVALID_SENDERPOSTALCODE("1025"),
        INVALID_SENDERCOUNTRY("1026"),
        INVALID_SENDEREXPIRE("1027"),
        INVALID_CARDBRAND("1028"),
        INVALID_SENDERCOUNTRYSUB("1029"),
        INVALID_ADDITIONAL_MSG("1030"),
        
        INVALID_ACQUIRERCOUNTRYCODE("1031"),
        INVALID_CARDACCIDCODE("1032"),
        INVALID_CARDACCNAME("1033"),
        INVALID_CARDACCCITY("1034"),
        INVALID_CARDACCSTATE("1035"),
        INVALID_CARDACCCOUNTRY("1036"),
        INVALID_TRANSFEEAMT("1037"),
        INVALID_MERCATEGORYCODE("1038"),
        INVALID_LOCALTRANSDATE("1039"),
        INVALID_PIREFNUM("1040"),
        INVALID_PITYPE("1041"),
        INVALID_MERPRIMARYACCNUM("1042"),
        INVALID_RETRIEVALREFNUM("1043"),
        INVALID_SECONDARYID("1044"),
        INVALID_REFNO("1045"),
        INVALID_SYSTRACEAUDITNUM("1046"),
        INVALID_TRANSCURRENCYCODE("1047"),
        INVALID_PANCLEAR("1048"),
        INVALID_CARDNAME("1049"),
        INVALID_CARDTYPE("1050"),
        INVALID_CREDITCARD("1051"),
        DUPLICATE_SEQUENCENO("1052"),
        
        /* VNPAY QR COMMON */
        INVALID_BANKCODE("1053"),
        INVALID_PAYTYPE("1054"),
        INVALID_ITEM("1055"),
        INVALID_PAYCODE("1056"),
        INVALID_CHECKSUM("1057"),
        INVALID_PROMOTIONCODE("1058"),
        INVALID_MOBILE("1059"),
        INVALID_USERNAME("1060"),
        INVALID_ACCOUNTNO("1061"),
        INVALID_DEBITAMOUNT("1062"),
        INVALID_PARTNER("1063"),
        INVALID_CLIENTID("1064"),
        INVALID_MERCHANTID("1065"),
        INVALID_PAYDATE("1066"),
        INVALID_ADDITIONALDATA("1067"),
        INVALID_MESSAGETYPE("1068"),
        INVALID_REALAMOUNT("1069"),
        
        LOC4DIGIT_DOES_NOT_FOUND("1070"),
        
        INVALID_DESCRIPTION("1071"),
        INVALID_CWINFO("1072"),
        
        CARDWORD_IS_MAINTANING("1100"),
        UNKNOW_CARDWORD_MESSAGE("1101"),
        UNKNOW_MASTER_MESSAGE("1102"),
        UNKNOW_MESSAGE("1103"),
        
        
        DBI_IS_ERROR("1998"), SYSTEM_IS_ERROR("1999"),
        
        /* CARDWORD */
        CARDWORD_OK("2000"),
        CARDWORD_OK_DBI_FAILED("2001"),
        CARDWORD_RETURN_DBI_FAILED("2002"),
        CARDWORD_FAILED("2003"),
        
        COMPLETE_RESPONSE_WITHOUT_ERROR("2100"),
        NO_RECORD_FOUND("2101"),
        DUPLICATE_SEQUENSE_NUMBER("2102"),
        SESSION_EXPIRED("2103"),
        NOT_APPROVE("2104"),
        TIMEOUT("2105"),
        EXCEPTION("2106"),
        INVALID_FI_CODE("2107"),
        INVALID_CARD_INDICATOR("2108"),
        INVALID_CARD_TYPE("2109"),
        INVALID_NAME("2110"),
        INVALID_EMBOSS_NAME("2111"),
        INVALID_NEW_ID_INDICATOR("2112"),
        INVALID_NEW_ID("2113"),
        INVALID_OLD_IC("2114"),
        INVALID_DOB("2115"),
        INVALID_GENDER("2116"),
        INVALID_COUNTRY("2117"),
        INVALID_RACE("2118"),
        INVALID_MARITAL_STATUS("2119"),
        INVALID_MOTHER_MAIDEN_NAME("2120"),
        INVALID_BILLING_OPTION("2121"),
        INVALID_SOURCE_CODE("2122"),
        INVALID_SALE_OFFICER_CODE("2123"),
        INVALID_BRANCH_CODE("2124"),
        INVALID_PROMOTION_CODE("2125"),
        INVALID_RESIDENCE_ADDRESS("2126"),
        INVALID_RESIDENCE_POSTCODE("2127"),
        INVALID_RESIDENCE_TOWN("2128"),
        INVALID_RESIDENCE_COUNTRY("2129"),
        INVALID_RESIDENCE_PHONE_NUMBER("2130"),
        INVALID_RESIDENCE_TYPE("2131"),
        INVALID_RESIDENCE_SINCE("2132"),
        INVALID_MAILING_ADDRESS("2133"),
        INVALID_MAILLING_POSTCODE("2134"),
        INVALID_MAILING_TOWN("2135"),
        INVALID_MAILING_COUNTRY("2136"),
        INVALID_MAILING_PHONE_NUMBER("2137"),
        INVALID_DELIVERY_OFFICE_NAME("2138"),
        INVALID_DELIVERY_OFFICE_DEPARTMENT_NAME("2139"),
        INVALID_DELIVERY_ADDRESS("2140"),
        INVALID_DELIVERY_POSTCODE("2141"),
        INVALID_DELIVERY_TOWN("2142"),
        INVALID_DELIVERY_COUNTRY("2143"),
        INVALID_OFFICE_NAME("2144"),
        INVALID_OFFICE_ADDRESS("2145"),
        INVALID_OFFICE_POSTCODE("2146"),
        INVALID_OFFICE_TOWN("2147"),
        INVALID_OFFICE_COUNTRY("2148"),
        INVALID_OFFICE_PHONE_NUMBER("2149"),
        INVALID_OFFICE_FAX("2150"),
        INVALID_INDUSTRY_CODE("2151"),
        INVALID_POSITION_HELD("2152"),
        INVALID_ANNUAL_INCOME("2153"),
        INVALID_EMAIL_ADDRESS("2154"),
        INVALID_MOBILE_NUMBER("2155"),
        INVALID_PREVIOUS_EMPLOYER_NAME("2156"),
        INVALID_PREVIOUS_EMPLOYER_ADDRESS("2157"),
        INVALID_PREVIOUS_EMPLOYER_POSTCODE("2158"),
        INVALID_PREVIOUS_EMPLOYER_TOWN("2159"),
        INVALID_PREVIOUS_EMPOYER_COUNTRY("2160"),
        INVALID_PREVIOUS_EMPLOYER_PHONE_NUMBER("2161"),
        INVALID_PREVIOUS_EMPLOYER_YEAR_SINCE("2162"),
        INVALID_SPOUSE_NAME("2163"),
        INVALID_SPOUSE_NEW_ID_NUMBER("2164"),
        INVALID_SPOUSE_ADDRESS("2165"),
        INVALID_SPOUSE_POSTCODE("2166"),
        INVALID_SPOUSE_TOWN("2167"),
        INVALID_SPOUSE_COUNTRY("2168"),
        INVALID_SPOUSE_PHONE_NUMBER("2169"),
        INVALID_EMERGENCY_CONTACT_PERSON("2170"),
        INVALID_EMERGENCY_CONTACT_NUMBER("2171"),
        INVALID_EMERGENCY_MOBILE_NUMBER("2172"),
        INVALID_ANSWER_FOR_QUESTION_1("2173"),
        INVALID_ANSWER_FOR_QUESTION_2("2174"),
        INVALID_ANSWER_FOR_QUESTION_3("2175"),
        INVALID_ANSWER_FOR_QUESTION_4("2176"),
        INVALID_ANSWER_FOR_QUESTION_5("2177"),
        INVALID_PAN("2178"),
        INVALID_EXPIRY_DATE("2179"),
        INVALID_CURRENCY_CODE("2180"),
        INVALID_BENEFICIARY_PAN("2181"),
        INVALID_BENEFICIARY_NAME("2182"),
        INVALID_POINT_REDEEM("2183"),
        INVALID_STATEMENT_MONTH("2184"),
        INVALID_USER_ID_OR_PASSWORD("2185"),
        OVER_ALLOWABLE_MAXIMUM_NO_OF_OCCURRENCES("2186"),
        INVALID_TITLE("2187"),
        INVALID_PLACE_OF_BIRTH("2188"),
        INVALID_PR_STATUS("2189"),
        INVALID_IMMIGRATION_VISA_EXPIRY_DATE("2190"),
        INVALID_WORK_NATURE("2191"),
        INVALID_NATURE_OF_BUSINESS("2192"),
        INVALID_RESIDENCE_STATE("2193"),
        INVALID_MAILING_STATE("2194"),
        INVALID_DELIVERY_STATE("2195"),
        INVALID_OFFICE_STATE("2196"),
        INVALID_MINISTERIAL_OR_DIPLOMATIC("2197"),
        INVALID_CRN("2198"),
        INVALID_SOURCE_SYSTEM("2199"),
        INVALID_REFERENCE_NUMBER("2200"),
        INVALID_RELOAD_METHOD("2201"),
        INVALID_RELOAD_SOURCE("2202"),
        INVALID_TRANSFEROR_PAN("2203"),
        INVALID_SURCHARGE_FEE("2204"),
        INVALID_BENEFICIARY_EXPIRY_DATE("2205"),
        INVALID_SOURCE_CODE_AND_PROMOTION_CODE_MAPPING("2206"),
        DUPLICATE_APPLICATION("2207"),
        INVALID_LAST_UPDATE_TIMESTAMP("2208"),
        CARD_ALREADY_ACTIVATED("2209"),
        THIS_RECORD_HAS_BEEN_DELETED_BY_NOTHER_UER("2210"),
        PLEASE_PORVIDE_AT_LEAST_1_SECURITY_VALIDATION("2211"),
        INVALID_ACTION("2212"),
        INVALID_PIN("2213"),
        CARD_ALREADY_LINKED("2214"),
        INVALID_DATA("2215"),
        ONLY_NEW_ID_POLICE_AND_MILITARY_IS_ACCEPTED_FOR_MALAYSIAN("2216"),
        INVALID_DELIVERY_OPTION("2217"),
        INVALID_DELIVERY_CENTER_CODE("2218"),
        INVALID_EMERGENCY_RELATION("2219"),
        INVALID_OCCUPATION("2220"),
        INVALID_TRANSACTION_DATE("2221"),
        INVALID_TRANSACTION_TIME("2222"),
        INVALID_MERCHANT_ID("2223"),
        INVALID_TERMINAL_ID("2224"),
        MORE_THAN_1_TRANSACTION_FOUND_PLEASE_CALL_CUSTOMER_SUPPORT("2225"),
        INVALID_CVV2("2226"),
        DUPLICATE_REFERENCE_NUMBER("2227"),
        INVALID_APPLICATION_TYPE("2228"),
        INVALID_CORPORATE_AND_GOVERNMENT_PAYMENT_FLAG("2229"),
        INVALID_PREFERRED_LANGUAGE("2230"),
        INVALID_ALTERNATE_EMAIL("2231"),
        CARD_ACTIVATION_FAILED("2232"),
        INVALID_MEMBER_ID("2233"),
        INVALID_RECOMMENDER_PAN("2234"),
        INVALID_RECOMMENDER_NAME("2235"),
        APPLICATION_CRITERIA_FALIED("2236"),
        MOBILE_NUMBER_NOT_FOUND("2237"),
        INVALID_ADDITIONAL_REFERENCE("2238"),
        PAN_NOT_IN_GOOD_STATUS("2239"),
        INVALID_SECURITY_CODE("2240"),
        CARD_EXPIRED("2241"),
        INVALID_SECURITY("2242"),
        COMPROMISED_CARD_NUMBER("2243"),
        CARD_APPLICATION_ALREADY_CREATED("2244"),
        INVALID_APPLICATION_MEMBER_ID_IS_RESERVED_FOR_PRE("2245"),
        CARD_ALREADY_BLOCKED_FOR_INTERNET_TRANSACTION("2246"),
        CARD_ALREADY_UNBLOCKED_FOR_INTERNET_TRANSACTION("2247"),
        CARD_ALREADY_UNBLOCKED_FOR_POS_TRANSACTION("2248"),
        CARD_ALREADY_BLOCKED_FOR_POS_TRANSACTION("2249"),
        INVALID_ADJUSTMENT_CODE("2250"),
        INVALID_ACCOUNT_INDICATOR("2251"),
        INVALID_ACTION_TYPE("2252"),
        INVALID_ACTION_CODE("2253"),
        INVALID_ADJUSTMENT_AMOUNT("2254"),
        INVALID_OFFICER_ID("2255"),
        INVALID_REWARD_ACTION("2256"),
        INSUFFICIENT_POINTS("2257"),
        
        /* MASTER CARD */
        MASTERCARD_OK("3000"),
        MASTERCARD_OK_DBI_FAILED("3001"),
        MASTERCARD_RETURN_DBI_FAILED("3002"),
        MASTERCARD_FAILED("3003"),
        
        PARTNER_DAILY_LIMIT("3010"),
        MAX_TRANSACTION_LIMIT("3011"),
        MIN_TRANSACTION_LIMIT("3012"),
        CONS_MONTHLY_TRAN_LIMIT("3013"),
        MAX_TRAN_TYPE_LIMIT("3014"),
        MIN_TRAN_TYPE_LIMIT("3015"),
        ACCOUNT_TYPE("3016"),
        ACCOUNT_NOT_ELIGIBLE("3017"),
        NETWORK_NOT_ELIGIBLE("3018"),
        CURRENCY_NOT_SUPPORTED("3019"),
        INVALID_INPUT_VALUE("3020"),
        DECLINE("3021"),
        AUTHENTICATION_FAILED("3022"),
        INVALID_INPUT_LENGTH("3023"),
        RESOURCE_ERROR("3024"),
        MASTERCARD_UNKNOWN("3025"),
        
        
        /* VNPAY QR */
        SUCCESS("4000"),
        
        /* CHECK QR */
        THISQRCODEISPAID("4101"),
        IPADDRESSISDENIED("4102"),
        BANKCODEISNOTEXIT("4103"),
        QRCODEISNOTINFORMAT("4104"),
        LISTQRCODEISREQUIRED("4105"),
        MERCHANTISNOTEXIT("4106"),
        MERCHANTISNOTACTIVE("4107"),
        FALSECHECKSUM("4108"),
        TERMINALISNOTEXIT("4109"),
        TERMINALISNOTACTIVE("4110"),
        MASTERMERCHANTISNOTEXIST("4111"),
        MASTERMERCHANTISNOTACTIVE("4112"),
        QRCODEISNOTACTIVE("4113"),
        DATAOFQRCODEISCHANGED("4114"),
        THESEQRCODEDONTHAVETHESAMEMERCHANT("4115"),
        MAKHACHHANGKOHOPLE("4116"),
        THESEQRCODEDONTHAVETHESAMETERMINAL("4117"),
        THESEISNOPROMOTION("4118"),
        VOUCHERCODEDOESNTEXIST("4119"),
        THEBANKDOESNTSUPPORTFORTHISPROMOTION("4120"),
        MECHANT_TERMINALDOESNTSUPPORTTHEVOUCHER("4121"),
        VOUCHERCODEWASUSEDUP("4122"),
        DEBITAMOUNTISNTENOUGHTOGETTHECONDITION("4123"),
        VOUCHEREXCEEDSNUMBEROFTIMESALLOWED("4124"),
        VOUCHERISPENDING("4125"),
        VOUCHERISLOCKED("4126"),
        VOUCHERISOUTOFDATE("4127"),
        USERNAMEISINVALID("4128"),
        BANKNOTSUPPORT("4129"),
        INTERNALERROR("4130"),
        
        /* PAYMENT QR */
        DATAISNOTINFORMAT("4150"),
        MOBILEISINVALID("4151"),
        POSTDATATOMERCHANTFAILED("4152"),
        PAYDATEISNOTINFORMAT("4153"),
        MERCHANTDONTRESPONSE("4154"),
        TRANSACTIONALREADYCONFIRMER("4155"),
        INVALIDTRANSACTION("4156"),
        TRANSACTIONNOTFOUND("4157"),
        INVALIDAMOUNT("4158"),
        TRANSACTIONEXPIRED("4159"),
        INVALIDRESPONSECODE("4160"),
        ACCOUNTISLOCKED("4161"),
        MOBILEISLOCKED("4162"),
        TERMINALISINVALID("4163"),
        TRANSACTIONDUPLICATE("4164"),
        TERMINALISINACTIVE("4165"),
        MESSAGETYPEISINVALID("4166"),
        NOTENOUGHPRODUCTINORDER("4167"),
        OUTOFSTOCKINORDER("4168"),
        THISORDERISPROCESSING("4169"),
        MERCHANT_TERMINALISNOTAPPROVED("4170"),
        THISBANKISNOTSUPPORT("4171"),
        SOTIENGACHNOKHONGHOPLE("4172"),
        SYSTEMISMAINTAINING("4173"),
        
        /* REFUND QR */
        DATAINPUTISNOTINFORMAT("4190"),
        BANKTRACEISREQUIRED("4191"),
        PAYCODEISREQUIRED("4192"),
        //TIMEOUT("4193"),
        
        TRANSACTION_OK("0000")
        ;

        private String code;

        private CommontEnum(String c)
        {
            code = c;
        }

        public static CommontEnum getFromValue(String value)
        {
            CommontEnum[] values = CommontEnum.values();
            for (CommontEnum val : values)
            {
                if (val.getValue().equals(value))
                {
                    return val;
                }
            }
            return CommontEnum.UNKNOW_MESSAGE;
        }
        
        public static CommontEnum getFromName(String value)
        {
            CommontEnum[] values = CommontEnum.values();
            for (CommontEnum val : values)
            {
                if (val.toString().equals(value))
                {
                    return val;
                }
            }
            return CommontEnum.UNKNOW_MESSAGE;
        }

        public String getValue()
        {
            return code;
        }
    }
    
    public static String getCommontEnumDescription(CommontEnum index)
    {
        switch (index)
        {
            case SYSTEM_IS_ERROR:
                return "He thong loi";
            case TRANSACTION_OK:
                return "Thanh toán hóa đơn thành công";
            default:
                return index.toString();
        }
    }
}

