package scb.com.vn.model;
// Generated Feb 25, 2013 10:12:56 AM by Hibernate Tools 3.2.1.GA

import java.util.List;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * PblBillpaid generated by hbm2java
 */
@XmlRootElement(name = "INSPAYMENTREQUESTDTO")
public class InsPaymentRp implements java.io.Serializable {

    private int id;
    private String idPartner;
    private String ownerID;
    private String ownerName;
    private String usertype;
    private String idchannel;
    private String accCust;
    private String accIdaccount;
    private String acc_holdername;
    private String acc_address;
    private Long totalamount;
    private int paymentmethod;
    private String iduserMaker;
    private String idchanneluserMaker;
    private String iduserChecker;
    private String idchanneluserChecker;
    private String status;
    private String branchcode;
    private String dataxml;
    private String pol_num;
    private String prem_typ;
    private String area;
    private String accountTo;
    private List<InsPaymentDetailRp> inspaydetaillist;

    /**
     *
     */
    public InsPaymentRp() {
    }

    /**
     *
     * @param id
     * @param idPartner
     * @param ownerID
     * @param ownerName
     * @param usertype
     * @param idchannel
     * @param acc_holdername
     * @param acc_address
     * @param paymentmethod
     * @param totalamount
     * @param iduserMaker
     * @param accCust
     * @param accIdaccount
     * @param iduserChecker
     * @param idchanneluserMaker
     * @param dataxml
     * @param idchanneluserChecker
     * @param status
     * @param branchcode
     * @param pol_num
     * @param prem_typ
     * @param area
     * @param accountTo
     */
    public InsPaymentRp(int id, String idPartner, String ownerID, String ownerName, String usertype, String idchannel,
            String acc_holdername, String acc_address, int paymentmethod, Long totalamount, String iduserMaker,
            String accCust, String accIdaccount, String iduserChecker, String idchanneluserMaker, String dataxml,
            String idchanneluserChecker, String status, String branchcode, String pol_num, String prem_typ, String area, String accountTo) {
        this.id = id;
        this.idPartner = idPartner;
        this.ownerID = ownerID;
        this.ownerName = ownerName;
        this.usertype = usertype;
        this.idchannel = idchannel;
        this.accCust = accCust;
        this.accIdaccount = accIdaccount;
        this.acc_holdername = acc_holdername;
        this.acc_address = acc_address;
        this.totalamount = totalamount;
        this.paymentmethod = paymentmethod;
        this.iduserMaker = iduserMaker;
        this.iduserChecker = iduserChecker;
        this.dataxml = dataxml;
        this.pol_num = pol_num;
        this.prem_typ = prem_typ;
        this.area = area;
        this.idchanneluserMaker = idchanneluserMaker;
        this.idchanneluserChecker = idchanneluserChecker;
        this.accCust = accCust;
        this.accIdaccount = accIdaccount;
        this.status = status;
        this.branchcode = branchcode;
        this.accountTo = accountTo;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "Item")
    @XmlElementWrapper(name = "Data", nillable = true)
    public List<InsPaymentDetailRp> getInspaydetaillist() {
        return inspaydetaillist;
    }

    /**
     *
     * @param inspaydetaillist
     */
    public void setInspaydetaillist(List<InsPaymentDetailRp> inspaydetaillist) {
        this.inspaydetaillist = inspaydetaillist;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ID", required = false, nillable = true)
    public int getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDPARTNER", required = false, nillable = true)
    public String getIdPartner() {
        return idPartner;
    }

    /**
     *
     * @param idPartner
     */
    public void setIdPartner(String idPartner) {
        this.idPartner = idPartner;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "OWNERID", required = false, nillable = true)
    public String getOwnerID() {
        return ownerID;
    }

    /**
     *
     * @param ownerID
     */
    public void setOwnerID(String ownerID) {
        this.ownerID = ownerID;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "OWNERNAME", required = false, nillable = true)
    public String getOwnerName() {
        return ownerName;
    }

    /**
     *
     * @param ownerName
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "USERTYPE", required = false, nillable = true)
    public String getUsertype() {
        return usertype;
    }

    /**
     *
     * @param usertype
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDCHANNEL", required = false, nillable = true)
    public String getIdchannel() {
        return idchannel;
    }

    /**
     *
     * @param idchannel
     */
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ACCCUST", required = false, nillable = true)
    public String getAccCust() {
        return accCust;
    }

    /**
     *
     * @param accCust
     */
    public void setAccCust(String accCust) {
        this.accCust = accCust;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ACCIDACCOUNT", required = false, nillable = true)
    public String getAccIdaccount() {
        return accIdaccount;
    }

    /**
     *
     * @param accIdaccount
     */
    public void setAccIdaccount(String accIdaccount) {
        this.accIdaccount = accIdaccount;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ACCHOLDERNAME", required = false, nillable = true)
    public String getAcc_holdername() {
        return acc_holdername;
    }

    /**
     *
     * @param acc_holdername
     */
    public void setAcc_holdername(String acc_holdername) {
        this.acc_holdername = acc_holdername;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ACCADDRESS", required = false, nillable = true)
    public String getAcc_address() {
        return acc_address;
    }

    /**
     *
     * @param acc_address
     */
    public void setAcc_address(String acc_address) {
        this.acc_address = acc_address;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "TOTALAMOUNT", required = false, nillable = true)
    public Long getTotalamount() {
        return totalamount;
    }

    /**
     *
     * @param totalamount
     */
    public void setTotalamount(Long totalamount) {
        this.totalamount = totalamount;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "PAYMENTMETHOD", required = false, nillable = true)
    public int getPaymentmethod() {
        return paymentmethod;
    }

    /**
     *
     * @param paymentmethod
     */
    public void setPaymentmethod(int paymentmethod) {
        this.paymentmethod = paymentmethod;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDUSERMAKER", required = false, nillable = true)
    public String getIduserMaker() {
        return iduserMaker;
    }

    /**
     *
     * @param iduserMaker
     */
    public void setIduserMaker(String iduserMaker) {
        this.iduserMaker = iduserMaker;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDCHANNELUSERMAKER", required = false, nillable = true)
    public String getIdchanneluserMaker() {
        return idchanneluserMaker;
    }

    /**
     *
     * @param idchanneluserMaker
     */
    public void setIdchanneluserMaker(String idchanneluserMaker) {
        this.idchanneluserMaker = idchanneluserMaker;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDUSERCHECKER", required = false, nillable = true)
    public String getIduserChecker() {
        return iduserChecker;
    }

    /**
     *
     * @param iduserChecker
     */
    public void setIduserChecker(String iduserChecker) {
        this.iduserChecker = iduserChecker;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDCHANNELUSERCHECKER", required = false, nillable = true)
    public String getIdchanneluserChecker() {
        return idchanneluserChecker;
    }

    /**
     *
     * @param idchanneluserChecker
     */
    public void setIdchanneluserChecker(String idchanneluserChecker) {
        this.idchanneluserChecker = idchanneluserChecker;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "STATUS", required = false, nillable = true)
    public String getStatus() {
        return status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "BRANCHCODE", required = false, nillable = true)
    public String getBranchcode() {
        return branchcode;
    }

    /**
     *
     * @param branchcode
     */
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "DATAXML", required = false, nillable = true)
    public String getDataxml() {
        return dataxml;
    }

    /**
     *
     * @param dataxml
     */
    public void setDataxml(String dataxml) {
        this.dataxml = dataxml;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "POLNUM", required = false, nillable = true)
    public String getPol_num() {
        return pol_num;
    }

    /**
     *
     * @param pol_num
     */
    public void setPol_num(String pol_num) {
        this.pol_num = pol_num;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "PREMTYP", required = false, nillable = true)
    public String getPrem_typ() {
        return prem_typ;
    }

    /**
     *
     * @param prem_typ
     */
    public void setPrem_typ(String prem_typ) {
        this.prem_typ = prem_typ;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "AREA", required = false, nillable = true)
    public String getArea() {
        return area;
    }

    /**
     *
     * @param area
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ACCOUNTTO", required = false, nillable = true)
    public String getAccountTo() {
        return accountTo;
    }

    /**
     *
     * @param accountTo
     */
    public void setAccountTo(String accountTo) {
        this.accountTo = accountTo;
    }

}
