package scb.com.vn.model;
// Generated Feb 25, 2013 10:12:56 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * PblBillpaid generated by hbm2java
 */
@XmlRootElement(name = "NEWPORTREQUEST")
public class NewportRq implements java.io.Serializable {

    private String idservicetype;
    private String idprovider;
    private String idpartner;
    private String iduserMaker;
    private Long totalamount;
    private String idchanneluserMaker;
    private String iduserChecker;
    private String idchanneluserChecker;
    private String idchannel;
    private Integer paymentmethod;
    private String accIdaccount;
    private String branchcode;
    private String accPartnerIdaccount;
    private String errorcode;
    private String errorMessage;
    private String bill_code;
    private String consignment_code;
    private String tax_code;
    private String Container_code;
    private String transcode;

    /**
     *
     */
    public NewportRq() {
    }

    /**
     *
     * @param id
     * @param provider
     * @param idpartner
     * @param iduserMaker
     * @param idchanneluserMaker
     * @param insdateMaker
     * @param iduserChecker
     * @param idchanneluserChecker
     * @param insdateChecker
     * @param idchannel
     * @param usertype
     * @param refPartner
     * @param refFcubs
     * @param totalamount
     * @param paymentmethod
     * @param accCust
     * @param accIdaccount
     * @param accHoldername
     * @param accAddress
     * @param insdate
     * @param transdate
     * @param paydate
     * @param paydateFcubs
     * @param isapproved
     * @param status
     */
    public NewportRq(int id, String provider, String idpartner, String iduserMaker, String idchanneluserMaker, Date insdateMaker, String iduserChecker, String idchanneluserChecker, Date insdateChecker, String idchannel, String usertype, String refPartner, String refFcubs, Long totalamount, Integer paymentmethod, String accCust, String accIdaccount, String accHoldername, String accAddress, Date insdate, Date transdate, Date paydate, Date paydateFcubs, Character isapproved, Character status) {

        this.iduserMaker = iduserMaker;
        this.idchanneluserMaker = idchanneluserMaker;
        this.iduserChecker = iduserChecker;
        this.idchanneluserChecker = idchanneluserChecker;
        this.idchannel = idchannel;
        this.paymentmethod = paymentmethod;
        this.accIdaccount = accIdaccount;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDPARTNER", required = false, nillable = true)
    public String getIdpartner() {
        return idpartner;
    }

    /**
     *
     * @param idpartner
     */
    public void setIdpartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "TRANSCODE", required = false, nillable = true)
    public String getTranscode() {
        return transcode;
    }

    /**
     *
     * @param transcode
     */
    public void setTranscode(String transcode) {
        this.transcode = transcode;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "TOTALAMOUNT", required = false, nillable = true)
    public Long getTotalamount() {
        return totalamount;
    }

    /**
     *
     * @param totalamount
     */
    public void setTotalamount(Long totalamount) {
        this.totalamount = totalamount;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDSERVICETYPE", required = false, nillable = true)
    public String getIdservicetype() {
        return idservicetype;
    }

    /**
     *
     * @param idservicetype
     */
    public void setIdservicetype(String idservicetype) {
        this.idservicetype = idservicetype;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDPROVIDER", required = false, nillable = true)
    public String getIdprovider() {
        return idprovider;
    }

    /**
     *
     * @param idprovider
     */
    public void setIdprovider(String idprovider) {
        this.idprovider = idprovider;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "BILL_CODE", required = false, nillable = true)
    public String getBill_code() {
        return bill_code;
    }

    /**
     *
     * @param bill_code
     */
    public void setBill_code(String bill_code) {
        this.bill_code = bill_code;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "CONSIGNMENT_CODE", required = false, nillable = true)
    public String getConsignment_code() {
        return consignment_code;
    }

    /**
     *
     * @param consignment_code
     */
    public void setConsignment_code(String consignment_code) {
        this.consignment_code = consignment_code;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "TAX_CODE", required = false, nillable = true)
    public String getTax_code() {
        return tax_code;
    }

    /**
     *
     * @param tax_code
     */
    public void setTax_code(String tax_code) {
        this.tax_code = tax_code;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "CONTAINER_CODE", required = false, nillable = true)
    public String getContainer_code() {
        return Container_code;
    }

    /**
     *
     * @param Container_code
     */
    public void setContainer_code(String Container_code) {
        this.Container_code = Container_code;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ERRORCODE", required = false, nillable = true)
    public String getErrorcode() {
        return errorcode;
    }

    /**
     *
     * @param errorcode
     */
    public void setErrorcode(String errorcode) {
        this.errorcode = errorcode;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ERRORMESSAGE", required = false, nillable = true)
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     *
     * @param errorMessage
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDUSERMAKER", required = false, nillable = true)
    public String getIduserMaker() {
        return this.iduserMaker;
    }

    /**
     *
     * @param iduserMaker
     */
    public void setIduserMaker(String iduserMaker) {
        this.iduserMaker = iduserMaker;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDCHANNELUSERMAKER", required = false, nillable = true)
    public String getIdchanneluserMaker() {
        return this.idchanneluserMaker;
    }

    /**
     *
     * @param idchanneluserMaker
     */
    public void setIdchanneluserMaker(String idchanneluserMaker) {
        this.idchanneluserMaker = idchanneluserMaker;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDUSERCHECKER", required = false, nillable = true)
    public String getIduserChecker() {
        return this.iduserChecker;
    }

    /**
     *
     * @param iduserChecker
     */
    public void setIduserChecker(String iduserChecker) {
        this.iduserChecker = iduserChecker;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDCHANNELUSERCHECKER", required = false, nillable = true)
    public String getIdchanneluserChecker() {
        return this.idchanneluserChecker;
    }

    /**
     *
     * @param idchanneluserChecker
     */
    public void setIdchanneluserChecker(String idchanneluserChecker) {
        this.idchanneluserChecker = idchanneluserChecker;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDCHANNEL", required = false, nillable = true)
    public String getIdchannel() {
        return this.idchannel;
    }

    /**
     *
     * @param idchannel
     */
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "PAYMENTMETHOD", required = false, nillable = true)
    public Integer getPaymentmethod() {
        return this.paymentmethod;
    }

    /**
     *
     * @param paymentmethod
     */
    public void setPaymentmethod(Integer paymentmethod) {
        this.paymentmethod = paymentmethod;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ACCIDACCOUNT", required = false, nillable = true)
    public String getAccIdaccount() {
        return this.accIdaccount;
    }

    /**
     *
     * @param accIdaccount
     */
    public void setAccIdaccount(String accIdaccount) {
        this.accIdaccount = accIdaccount;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "BRANCHCODE", required = false, nillable = true)
    public String getBranchcode() {
        return branchcode;
    }

    /**
     *
     * @param branchcode
     */
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ACCPARTNERIDACCOUNT", required = false, nillable = true)
    public String getAccPartnerIdaccount() {
        return accPartnerIdaccount;
    }

    /**
     *
     * @param accPartnerIdaccount
     */
    public void setAccPartnerIdaccount(String accPartnerIdaccount) {
        this.accPartnerIdaccount = accPartnerIdaccount;
    }

}
