package scb.com.vn.model;
// Generated Feb 25, 2013 10:12:56 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * PblBillpaid generated by hbm2java
 */
@XmlRootElement(name = "BUYCARDREQUESTDTO")
public class RTBuyCardRq implements java.io.Serializable {

    private int id;
    private String provider;
    private String idpartner;
    private String orgtransid;
    private String pricetag;
    private Integer quantity;
    private Long discount;
    private String iduserMaker;
    private String idchanneluserMaker;
    private String iduserChecker;
    private String idchanneluserChecker;
    private String idchannel;
    private Long totalamount;
    private Integer paymentmethod;
    private String accIdaccount;
    private Character status;
    private String branchcode;
    private String accPartnerIdaccount;
    private String errorcode;
    private String errorMessage;
    private List<RTCardDetail> rtcarddetail;
    private String TxnID;

    /**
     *
     */
    public RTBuyCardRq() {
    }

    /**
     *
     * @param id
     * @param provider
     * @param idpartner
     * @param iduserMaker
     * @param idchanneluserMaker
     * @param insdateMaker
     * @param iduserChecker
     * @param idchanneluserChecker
     * @param insdateChecker
     * @param idchannel
     * @param usertype
     * @param refPartner
     * @param refFcubs
     * @param totalamount
     * @param paymentmethod
     * @param accCust
     * @param accIdaccount
     * @param accHoldername
     * @param accAddress
     * @param insdate
     * @param transdate
     * @param paydate
     * @param paydateFcubs
     * @param isapproved
     * @param status
     */
    public RTBuyCardRq(int id, String provider, String idpartner, String iduserMaker, String idchanneluserMaker, Date insdateMaker, String iduserChecker, String idchanneluserChecker, Date insdateChecker, String idchannel, String usertype, String refPartner, String refFcubs, Long totalamount, Integer paymentmethod, String accCust, String accIdaccount, String accHoldername, String accAddress, Date insdate, Date transdate, Date paydate, Date paydateFcubs, Character isapproved, Character status) {
        this.id = id;
        this.provider = provider;
        this.idpartner = idpartner;
        this.iduserMaker = iduserMaker;
        this.idchanneluserMaker = idchanneluserMaker;
        this.iduserChecker = iduserChecker;
        this.idchanneluserChecker = idchanneluserChecker;
        this.idchannel = idchannel;
        this.totalamount = totalamount;
        this.paymentmethod = paymentmethod;
        this.accIdaccount = accIdaccount;
        this.status = status;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "Item")
    @XmlElementWrapper(name = "Data", nillable = true)
    public List<RTCardDetail> getRtcarddetail() {
        return rtcarddetail;
    }

    /**
     *
     * @param rtcarddetail
     */
    public void setRtcarddetail(List<RTCardDetail> rtcarddetail) {
        this.rtcarddetail = rtcarddetail;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ERRORCODE", required = false, nillable = true)
    public String getErrorcode() {
        return errorcode;
    }

    /**
     *
     * @param errorcode
     */
    public void setErrorcode(String errorcode) {
        this.errorcode = errorcode;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ERRORMESSAGE", required = false, nillable = true)
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     *
     * @param errorMessage
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "STATUS", required = false, nillable = true)
    public Character getStatus() {
        return status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(Character status) {
        this.status = status;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ID", required = false, nillable = true)
    public int getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "PROVIDER", required = false, nillable = true)
    public String getProvider() {
        return provider;
    }

    /**
     *
     * @param provider
     */
    public void setProvider(String provider) {
        this.provider = provider;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ORGTRANSID", required = false, nillable = true)
    public String getOrgtransid() {
        return orgtransid;
    }

    /**
     *
     * @param orgtransid
     */
    public void setOrgtransid(String orgtransid) {
        this.orgtransid = orgtransid;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "PRICETAG", required = false, nillable = true)
    public String getPricetag() {
        return pricetag;
    }

    /**
     *
     * @param pricetag
     */
    public void setPricetag(String pricetag) {
        this.pricetag = pricetag;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "QUANTITY", required = false, nillable = true)
    public Integer getQuantity() {
        return quantity;
    }

    /**
     *
     * @param quantity
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "DISCOUNT", required = false, nillable = true)
    public Long getDiscount() {
        return discount;
    }

    /**
     *
     * @param discount
     */
    public void setDiscount(Long discount) {
        this.discount = discount;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDPARTNER", required = false, nillable = true)
    public String getIdpartner() {
        return this.idpartner;
    }

    /**
     *
     * @param idpartner
     */
    public void setIdpartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDUSERMAKER", required = false, nillable = true)
    public String getIduserMaker() {
        return this.iduserMaker;
    }

    /**
     *
     * @param iduserMaker
     */
    public void setIduserMaker(String iduserMaker) {
        this.iduserMaker = iduserMaker;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDCHANNELUSERMAKER", required = false, nillable = true)
    public String getIdchanneluserMaker() {
        return this.idchanneluserMaker;
    }

    /**
     *
     * @param idchanneluserMaker
     */
    public void setIdchanneluserMaker(String idchanneluserMaker) {
        this.idchanneluserMaker = idchanneluserMaker;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDUSERCHECKER", required = false, nillable = true)
    public String getIduserChecker() {
        return this.iduserChecker;
    }

    /**
     *
     * @param iduserChecker
     */
    public void setIduserChecker(String iduserChecker) {
        this.iduserChecker = iduserChecker;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDCHANNELUSERCHECKER", required = false, nillable = true)
    public String getIdchanneluserChecker() {
        return this.idchanneluserChecker;
    }

    /**
     *
     * @param idchanneluserChecker
     */
    public void setIdchanneluserChecker(String idchanneluserChecker) {
        this.idchanneluserChecker = idchanneluserChecker;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDCHANNEL", required = false, nillable = true)
    public String getIdchannel() {
        return this.idchannel;
    }

    /**
     *
     * @param idchannel
     */
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "TOTALAMOUNT", required = false, nillable = true)
    public Long getTotalamount() {
        return this.totalamount;
    }

    /**
     *
     * @param totalamount
     */
    public void setTotalamount(Long totalamount) {
        this.totalamount = totalamount;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "PAYMENTMETHOD", required = false, nillable = true)
    public Integer getPaymentmethod() {
        return this.paymentmethod;
    }

    /**
     *
     * @param paymentmethod
     */
    public void setPaymentmethod(Integer paymentmethod) {
        this.paymentmethod = paymentmethod;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ACCIDACCOUNT", required = false, nillable = true)
    public String getAccIdaccount() {
        return this.accIdaccount;
    }

    /**
     *
     * @param accIdaccount
     */
    public void setAccIdaccount(String accIdaccount) {
        this.accIdaccount = accIdaccount;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "BRANCHCODE", required = false, nillable = true)
    public String getBranchcode() {
        return branchcode;
    }

    /**
     *
     * @param branchcode
     */
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ACCPARTNERIDACCOUNT", required = false, nillable = true)
    public String getAccPartnerIdaccount() {
        return accPartnerIdaccount;
    }

    /**
     *
     * @param accPartnerIdaccount
     */
    public void setAccPartnerIdaccount(String accPartnerIdaccount) {
        this.accPartnerIdaccount = accPartnerIdaccount;
    }

    /**
     * @return the TxnID
     */
    @XmlElement(name = "TxnID", required = false, nillable = true)
    public String getTxnID() {
        return TxnID;
    }

    /**
     * @param TxnID the TxnID to set
     */
    public void setTxnID(String TxnID) {
        this.TxnID = TxnID;
    }

}
