package scb.com.vn.model;
// Generated Dec 22, 2012 11:38:57 AM by Hibernate Tools 3.2.1.GA

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * PblProvider generated by hbm2java
 */
@XmlRootElement(name = "RTCARDDETAIL")
public class RTCardDetail implements java.io.Serializable {

    private String cardcode;
    private String serial;
    private String expire_date;

    /**
     *
     */
    public RTCardDetail() {
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "CARDCODE", required = false, nillable = true)
    public String getCardcode() {
        return cardcode;
    }

    /**
     *
     * @param cardcode
     */
    public void setCardcode(String cardcode) {
        this.cardcode = cardcode;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "SERIAL", required = false, nillable = true)
    public String getSerial() {
        return serial;
    }

    /**
     *
     * @param serial
     */
    public void setSerial(String serial) {
        this.serial = serial;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "EXPIREDATE", required = false, nillable = true)
    public String getExpire_date() {
        return expire_date;
    }

    /**
     *
     * @param expire_date
     */
    public void setExpire_date(String expire_date) {
        this.expire_date = expire_date;
    }

}
