//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.24 at 03:26:49 AM ICT 
//


package vn.com.scb.bian;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillPaymentInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillPaymentInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="billTotalAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="billIsPrepaid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="billPaymentRule" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="billPaymentRange" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idBillPaid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillPaymentInfoType", propOrder = {
    "billServiceCode",
    "billProviderCode",
    "billPartnerCode",
    "billCustomerCode",
    "billPaymentMethod",
    "billTransCode",
    "billCustomerName",
    "billCustomerAddress",
    "billMoreInfomation",   
    "billPayAmount",
    "billTotalAmount",
    "billIsPrepaid",
    "billPaymentRule",
    "billPaymentRange",
    "billProductCode",
    "idBillPaid"
})
public class BillPaymentInfoType {
  @XmlElement(required = true)
    protected String billServiceCode;
    @XmlElement(required = true)
    protected String billProviderCode;
    @XmlElement(required = true)
    protected String billPartnerCode;
    @XmlElement(required = true)
    protected String billCustomerCode;
    @XmlElement(required = true)
    protected String billPaymentMethod;
    @XmlElement(required = true)
    protected String billTransCode;
    @XmlElement(required = true)
    protected String billCustomerName;
    @XmlElement(required = true)
    protected String billCustomerAddress;
    @XmlElement(required = true)
    protected String billMoreInfomation;
    @XmlElement(required = true)
    protected String billTotalAmount;
    @XmlElement(required = true)
    protected String billPayAmount;
  
    @XmlElement(required = true)
    protected String billIsPrepaid;
    @XmlElement(required = true)
    protected String billPaymentRule;
    @XmlElement(required = true)
    protected String billPaymentRange;
    @XmlElement(required = true)
    protected String idBillPaid;
    @XmlElement(required = true)
    private String billProductCode;
    /**
     * Gets the value of the billTotalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillTotalAmount() {
        return billTotalAmount;
    }

    /**
     * Sets the value of the billTotalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillTotalAmount(String value) {
        this.billTotalAmount = value;
    }

    /**
     * Gets the value of the billIsPrepaid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillIsPrepaid() {
        return billIsPrepaid;
    }

    /**
     * Sets the value of the billIsPrepaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillIsPrepaid(String value) {
        this.billIsPrepaid = value;
    }

    /**
     * Gets the value of the billPaymentRule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPaymentRule() {
        return billPaymentRule;
    }

    /**
     * Sets the value of the billPaymentRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPaymentRule(String value) {
        this.billPaymentRule = value;
    }

    /**
     * Gets the value of the billPaymentRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPaymentRange() {
        return billPaymentRange;
    }

    /**
     * Sets the value of the billPaymentRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPaymentRange(String value) {
        this.billPaymentRange = value;
    }

    /**
     * Gets the value of the idBillPaid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdBillPaid() {
        return idBillPaid;
    }

    /**
     * Sets the value of the idBillPaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdBillPaid(String value) {
        this.idBillPaid = value;
    }
  /**
     * Gets the value of the billServiceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillServiceCode() {
        return billServiceCode;
    }

    /**
     * Sets the value of the billServiceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillServiceCode(String value) {
        this.billServiceCode = value;
    }

    /**
     * Gets the value of the billProviderCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillProviderCode() {
        return billProviderCode;
    }

    /**
     * Sets the value of the billProviderCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillProviderCode(String value) {
        this.billProviderCode = value;
    }

    /**
     * Gets the value of the billPartnerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPartnerCode() {
        return billPartnerCode;
    }

    /**
     * Sets the value of the billPartnerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPartnerCode(String value) {
        this.billPartnerCode = value;
    }

    /**
     * Gets the value of the billCustomerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillCustomerCode() {
        return billCustomerCode;
    }

    /**
     * Sets the value of the billCustomerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillCustomerCode(String value) {
        this.billCustomerCode = value;
    }

    /**
     * Gets the value of the billPaymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPaymentMethod() {
        return billPaymentMethod;
    }

    /**
     * Sets the value of the billPaymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPaymentMethod(String value) {
        this.billPaymentMethod = value;
    }

    /**
     * Gets the value of the billTransCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillTransCode() {
        return billTransCode;
    }

    /**
     * Sets the value of the billTransCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillTransCode(String value) {
        this.billTransCode = value;
    }

    /**
     * Gets the value of the billCustomerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillCustomerName() {
        return billCustomerName;
    }

    /**
     * Sets the value of the billCustomerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillCustomerName(String value) {
        this.billCustomerName = value;
    }

    /**
     * Gets the value of the billCustomerAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillCustomerAddress() {
        return billCustomerAddress;
    }

    /**
     * Sets the value of the billCustomerAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillCustomerAddress(String value) {
        this.billCustomerAddress = value;
    }

    /**
     * Gets the value of the billMoreInfomation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillMoreInfomation() {
        return billMoreInfomation;
    }

    /**
     * Sets the value of the billMoreInfomation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillMoreInfomation(String value) {
        this.billMoreInfomation = value;
    }
  
    /**
     * Gets the value of the billPayAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPayAmount() {
        return billPayAmount;
    }

    /**
     * Sets the value of the billPayAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPayAmount(String value) {
        this.billPayAmount = value;
    }

    /**
     * @return the billProductCode
     */
    public String getBillProductCode() {
        return billProductCode;
    }

    /**
     * @param billProductCode the billProductCode to set
     */
    public void setBillProductCode(String billProductCode) {
        this.billProductCode = billProductCode;
    }
}
