//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.22 at 06:17:18 AM ICT 
//


package vn.com.scb.bian;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillPaymentDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillPaymentDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="billDetailId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="billCustomerCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="billDetailMonth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="billDetailMoneyAmount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="billDetailPaymentFee" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillPaymentDetailType", propOrder = {
    "billDetailId",
    "billCustomerCode",
    "billDetailMonth",
    "billDetailMoneyAmount",
    "billDetailPaymentFee"
})
public class BillPaymentDetailType {

    @XmlElement(required = true)
    protected String billDetailId;
    @XmlElement(required = true)
    protected String billCustomerCode;
    @XmlElement(required = true)
    protected String billDetailMonth;
    @XmlElement(required = true)
    protected String billDetailMoneyAmount;
    @XmlElement(required = true)
    protected String billDetailPaymentFee;

    /**
     * Gets the value of the billDetailId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillDetailId() {
        return billDetailId;
    }

    /**
     * Sets the value of the billDetailId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillDetailId(String value) {
        this.billDetailId = value;
    }

    /**
     * Gets the value of the billCustomerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillCustomerCode() {
        return billCustomerCode;
    }

    /**
     * Sets the value of the billCustomerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillCustomerCode(String value) {
        this.billCustomerCode = value;
    }

    /**
     * Gets the value of the billDetailMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillDetailMonth() {
        return billDetailMonth;
    }

    /**
     * Sets the value of the billDetailMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillDetailMonth(String value) {
        this.billDetailMonth = value;
    }

    /**
     * Gets the value of the billDetailMoneyAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillDetailMoneyAmount() {
        return billDetailMoneyAmount;
    }

    /**
     * Sets the value of the billDetailMoneyAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillDetailMoneyAmount(String value) {
        this.billDetailMoneyAmount = value;
    }

    /**
     * Gets the value of the billDetailPaymentFee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillDetailPaymentFee() {
        return billDetailPaymentFee;
    }

    /**
     * Sets the value of the billDetailPaymentFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillDetailPaymentFee(String value) {
        this.billDetailPaymentFee = value;
    }

}
