//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.22 at 06:17:18 AM ICT 
//


package vn.com.scb.bian;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillPaymentServiceInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillPaymentServiceInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="billPaymentServiceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billPaymentProvider" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billPaymentServiceCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billPaymentServiceStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billPaymentDebitAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billPaymentLatestTransDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billPaymentBranchCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billPaymentIssueDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="billPaymentContractNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillPaymentServiceInfoType", propOrder = {
    "billPaymentServiceType",
    "billPaymentProvider",
    "billPaymentServiceCode",
    "billPaymentServiceStatus",
    "billPaymentDebitAccount",
    "billPaymentLatestTransDate",
    "billPaymentBranchCode",
    "billPaymentIssueDate",
    "billPaymentContractNum"
})
public class BillPaymentServiceInfoType {

    protected String billPaymentServiceType;
    protected String billPaymentProvider;
    protected String billPaymentServiceCode;
    protected String billPaymentServiceStatus;
    protected String billPaymentDebitAccount;
    protected String billPaymentLatestTransDate;
    protected String billPaymentBranchCode;
    protected String billPaymentIssueDate;
    protected String billPaymentContractNum;

    /**
     * Gets the value of the billPaymentServiceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPaymentServiceType() {
        return billPaymentServiceType;
    }

    /**
     * Sets the value of the billPaymentServiceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPaymentServiceType(String value) {
        this.billPaymentServiceType = value;
    }

    /**
     * Gets the value of the billPaymentProvider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPaymentProvider() {
        return billPaymentProvider;
    }

    /**
     * Sets the value of the billPaymentProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPaymentProvider(String value) {
        this.billPaymentProvider = value;
    }

    /**
     * Gets the value of the billPaymentServiceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPaymentServiceCode() {
        return billPaymentServiceCode;
    }

    /**
     * Sets the value of the billPaymentServiceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPaymentServiceCode(String value) {
        this.billPaymentServiceCode = value;
    }

    /**
     * Gets the value of the billPaymentServiceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPaymentServiceStatus() {
        return billPaymentServiceStatus;
    }

    /**
     * Sets the value of the billPaymentServiceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPaymentServiceStatus(String value) {
        this.billPaymentServiceStatus = value;
    }

    /**
     * Gets the value of the billPaymentDebitAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPaymentDebitAccount() {
        return billPaymentDebitAccount;
    }

    /**
     * Sets the value of the billPaymentDebitAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPaymentDebitAccount(String value) {
        this.billPaymentDebitAccount = value;
    }

    /**
     * Gets the value of the billPaymentLatestTransDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPaymentLatestTransDate() {
        return billPaymentLatestTransDate;
    }

    /**
     * Sets the value of the billPaymentLatestTransDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPaymentLatestTransDate(String value) {
        this.billPaymentLatestTransDate = value;
    }

    /**
     * Gets the value of the billPaymentBranchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPaymentBranchCode() {
        return billPaymentBranchCode;
    }

    /**
     * Sets the value of the billPaymentBranchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPaymentBranchCode(String value) {
        this.billPaymentBranchCode = value;
    }

    /**
     * Gets the value of the billPaymentIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPaymentIssueDate() {
        return billPaymentIssueDate;
    }

    /**
     * Sets the value of the billPaymentIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPaymentIssueDate(String value) {
        this.billPaymentIssueDate = value;
    }

    /**
     * Gets the value of the billPaymentContractNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPaymentContractNum() {
        return billPaymentContractNum;
    }

    /**
     * Sets the value of the billPaymentContractNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPaymentContractNum(String value) {
        this.billPaymentContractNum = value;
    }

}
