package scb.com.vn.mobile.model;
// Generated Feb 25, 2013 10:12:56 AM by Hibernate Tools 3.2.1.GA

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import scb.com.vn.model.InsPaymentDetailRp;
import scb.com.vn.model.MobileRequest;

/**
 * PblBillpaid generated by hbm2java
 */
@XmlRootElement(name = "InsuranceFeePayRq")
public class InsuranceFeePayRq extends MobileRequest {

    private int id;
    private String ownerID;
    private String ownerName;
    private String usertype;
    private String idchannel;
    private String accCust;
    private String accIdaccount;
    private String acc_holdername;
    private String acc_address;
    private Long totalamount;
    private int paymentmethod;
    private String iduserMaker;
    private String idchanneluserMaker;
    private String iduserChecker;
    private String idchanneluserChecker;
    private String status;
    private String branchcode;
    private String dataxml;
    private String pol_num;
    private String prem_typ;
    private String area;
    private String accountTo;
    private InsPaymentDetailRp[] Insdetaillist;

    /**
     *
     */
    public InsuranceFeePayRq() {
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ID", required = false, nillable = true)
    public int getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "Ownerid", required = false, nillable = true)
    public String getOwnerID() {
        return ownerID;
    }

    /**
     *
     * @param ownerID
     */
    public void setOwnerID(String ownerID) {
        this.ownerID = ownerID;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "Ownername", required = false, nillable = true)
    public String getOwnerName() {
        return ownerName;
    }

    /**
     *
     * @param ownerName
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "USERTYPE", required = false, nillable = true)
    public String getUsertype() {
        return usertype;
    }

    /**
     *
     * @param usertype
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDCHANNEL", required = false, nillable = true)
    public String getIdchannel() {
        return idchannel;
    }

    /**
     *
     * @param idchannel
     */
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "CifNo", required = false, nillable = true)
    public String getAccCust() {
        return accCust;
    }

    /**
     *
     * @param accCust
     */
    public void setAccCust(String accCust) {
        this.accCust = accCust;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "DebitAccount", required = false, nillable = true)
    public String getAccIdaccount() {
        return accIdaccount;
    }

    /**
     *
     * @param accIdaccount
     */
    public void setAccIdaccount(String accIdaccount) {
        this.accIdaccount = accIdaccount;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ACCHOLDERNAME", required = false, nillable = true)
    public String getAcc_holdername() {
        return acc_holdername;
    }

    /**
     *
     * @param acc_holdername
     */
    public void setAcc_holdername(String acc_holdername) {
        this.acc_holdername = acc_holdername;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ACCADDRESS", required = false, nillable = true)
    public String getAcc_address() {
        return acc_address;
    }

    /**
     *
     * @param acc_address
     */
    public void setAcc_address(String acc_address) {
        this.acc_address = acc_address;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "PayAmt", required = false, nillable = true)
    public Long getTotalamount() {
        return totalamount;
    }

    /**
     *
     * @param totalamount
     */
    public void setTotalamount(Long totalamount) {
        this.totalamount = totalamount;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "PAYMENTMETHOD", required = false, nillable = true)
    public int getPaymentmethod() {
        return paymentmethod;
    }

    /**
     *
     * @param paymentmethod
     */
    public void setPaymentmethod(int paymentmethod) {
        this.paymentmethod = paymentmethod;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDUSERMAKER", required = false, nillable = true)
    public String getIduserMaker() {
        return iduserMaker;
    }

    /**
     *
     * @param iduserMaker
     */
    public void setIduserMaker(String iduserMaker) {
        this.iduserMaker = iduserMaker;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDCHANNELUSERMAKER", required = false, nillable = true)
    public String getIdchanneluserMaker() {
        return idchanneluserMaker;
    }

    /**
     *
     * @param idchanneluserMaker
     */
    public void setIdchanneluserMaker(String idchanneluserMaker) {
        this.idchanneluserMaker = idchanneluserMaker;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDUSERCHECKER", required = false, nillable = true)
    public String getIduserChecker() {
        return iduserChecker;
    }

    /**
     *
     * @param iduserChecker
     */
    public void setIduserChecker(String iduserChecker) {
        this.iduserChecker = iduserChecker;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "IDCHANNELUSERCHECKER", required = false, nillable = true)
    public String getIdchanneluserChecker() {
        return idchanneluserChecker;
    }

    /**
     *
     * @param idchanneluserChecker
     */
    public void setIdchanneluserChecker(String idchanneluserChecker) {
        this.idchanneluserChecker = idchanneluserChecker;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "STATUS", required = false, nillable = true)
    public String getStatus() {
        return status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "BRANCHCODE", required = false, nillable = true)
    public String getBranchcode() {
        return branchcode;
    }

    /**
     *
     * @param branchcode
     */
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "DATAXML", required = false, nillable = true)
    public String getDataxml() {
        return dataxml;
    }

    /**
     *
     * @param dataxml
     */
    public void setDataxml(String dataxml) {
        this.dataxml = dataxml;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "PolNum", required = false, nillable = true)
    public String getPol_num() {
        return pol_num;
    }

    /**
     *
     * @param pol_num
     */
    public void setPol_num(String pol_num) {
        this.pol_num = pol_num;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "PREM_TYPE", required = false, nillable = true)
    public String getPrem_typ() {
        return prem_typ;
    }

    /**
     *
     * @param prem_typ
     */
    public void setPrem_typ(String prem_typ) {
        this.prem_typ = prem_typ;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "AREA", required = false, nillable = true)
    public String getArea() {
        return area;
    }

    /**
     *
     * @param area
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "ACCOUNTTO", required = false, nillable = true)
    public String getAccountTo() {
        return accountTo;
    }

    /**
     *
     * @param accountTo
     */
    public void setAccountTo(String accountTo) {
        this.accountTo = accountTo;
    }

    /**
     * @return the Insdetaillist
     */
    @XmlElement(name = "INSPAYMENTDETAIL")
    @XmlElementWrapper(name = "Inspaydetaillist", nillable = true)
    public InsPaymentDetailRp[] getInsdetaillist() {
        return Insdetaillist;
    }

    /**
     * @param Insdetaillist the Insdetaillist to set
     */
    public void setInsdetaillist(InsPaymentDetailRp[] Insdetaillist) {
        this.Insdetaillist = Insdetaillist;
    }

}
