package scb.com.vn.dbi.dto;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BPblAutoRegContract generated by hbm2java
 */
public class BPblAutoRegContract implements java.io.Serializable {

    private String idcontract;
    private String custAccCif;
    private String custAccNo;
    private String custAccName;
    private String custAccAddress;
    private String custAccIdcard;
    private String custAccIdcardLoc;
    private String custAccIdcardDob;
    private char havesms;
    private String mobile;
    private char active;
    private Date datcreated;
    private String makerid;
    private String branchcode;
    private String checkerid;
    private Date datautheq;
    private String makeridModify;
    private String makeridModifyBrncode;
    private Date makeridModifyDatcreated;
    private String checkeridModify;
    private Date checkeridModifyDatcreate;
    private Date lastsendsms;
    private Character isapproved;    
    private Set<BPblAutoReg> BPblAutoRegs = new HashSet<BPblAutoReg>(0);

    /**
     * Create a new instance of BPblAutoRegContract
     */
    public BPblAutoRegContract() {
    }

    /**
     *
     * @param idcontract
     * @param custAccCif
     * @param custAccNo
     * @param custAccName
     * @param havesms
     * @param active
     * @param datcreated
     */
    public BPblAutoRegContract(String idcontract, String custAccCif, String custAccNo, String custAccName, char havesms, char active, Date datcreated) {
        this.idcontract = idcontract;
        this.custAccCif = custAccCif;
        this.custAccNo = custAccNo;
        this.custAccName = custAccName;
        this.havesms = havesms;
        this.active = active;
        this.datcreated = datcreated;
    }

    /**
     *
     * @param idcontract
     * @param custAccCif
     * @param custAccNo
     * @param custAccName
     * @param custAccAddress
     * @param custAccIdcard
     * @param custAccIdcardLoc
     * @param custAccIdcardDob
     * @param havesms
     * @param mobile
     * @param active
     * @param datcreated
     * @param makerid
     * @param branchcode
     * @param checkerid
     * @param datautheq
     * @param makeridModify
     * @param makeridModifyBrncode
     * @param makeridModifyDatcreated
     * @param checkeridModify
     * @param checkeridModifyDatcreate
     * @param lastsendsms
     * @param isapproved
     * @param BPblAutoRegs
     */
    public BPblAutoRegContract(String idcontract, String custAccCif, String custAccNo, String custAccName, String custAccAddress, String custAccIdcard, String custAccIdcardLoc, String custAccIdcardDob, char havesms, String mobile, char active, Date datcreated, String makerid, String branchcode, String checkerid, Date datautheq, String makeridModify, String makeridModifyBrncode, Date makeridModifyDatcreated, String checkeridModify, Date checkeridModifyDatcreate, Date lastsendsms, Character isapproved, Set<BPblAutoReg> BPblAutoRegs) {
        this.idcontract = idcontract;
        this.custAccCif = custAccCif;
        this.custAccNo = custAccNo;
        this.custAccName = custAccName;
        this.custAccAddress = custAccAddress;
        this.custAccIdcard = custAccIdcard;
        this.custAccIdcardLoc = custAccIdcardLoc;
        this.custAccIdcardDob = custAccIdcardDob;
        this.havesms = havesms;
        this.mobile = mobile;
        this.active = active;
        this.datcreated = datcreated;
        this.makerid = makerid;
        this.branchcode = branchcode;
        this.checkerid = checkerid;
        this.datautheq = datautheq;
        this.makeridModify = makeridModify;
        this.makeridModifyBrncode = makeridModifyBrncode;
        this.makeridModifyDatcreated = makeridModifyDatcreated;
        this.checkeridModify = checkeridModify;
        this.checkeridModifyDatcreate = checkeridModifyDatcreate;
        this.lastsendsms = lastsendsms;
        this.isapproved = isapproved;
        this.BPblAutoRegs = BPblAutoRegs;
    }

    
    
    /**
     *
     * @return
     */
    public String getIdcontract() {
        return this.idcontract;
    }

    /**
     *
     * @param idcontract
     */
    public void setIdcontract(String idcontract) {
        this.idcontract = idcontract;
    }

    /**
     *
     * @return
     */
    public String getCustAccCif() {
        return this.custAccCif;
    }

    /**
     *
     * @param custAccCif
     */
    public void setCustAccCif(String custAccCif) {
        this.custAccCif = custAccCif;
    }

    /**
     *
     * @return
     */
    public String getCustAccNo() {
        return this.custAccNo;
    }

    /**
     *
     * @param custAccNo
     */
    public void setCustAccNo(String custAccNo) {
        this.custAccNo = custAccNo;
    }

    /**
     *
     * @return
     */
    public String getCustAccName() {
        return this.custAccName;
    }

    /**
     *
     * @param custAccName
     */
    public void setCustAccName(String custAccName) {
        this.custAccName = custAccName;
    }

    /**
     *
     * @return
     */
    public String getCustAccAddress() {
        return this.custAccAddress;
    }

    /**
     *
     * @param custAccAddress
     */
    public void setCustAccAddress(String custAccAddress) {
        this.custAccAddress = custAccAddress;
    }

    /**
     *
     * @return
     */
    public String getCustAccIdcard() {
        return this.custAccIdcard;
    }

    /**
     *
     * @param custAccIdcard
     */
    public void setCustAccIdcard(String custAccIdcard) {
        this.custAccIdcard = custAccIdcard;
    }

    /**
     *
     * @return
     */
    public String getCustAccIdcardLoc() {
        return this.custAccIdcardLoc;
    }

    /**
     *
     * @param custAccIdcardLoc
     */
    public void setCustAccIdcardLoc(String custAccIdcardLoc) {
        this.custAccIdcardLoc = custAccIdcardLoc;
    }

    /**
     *
     * @return
     */
    public String getCustAccIdcardDob() {
        return this.custAccIdcardDob;
    }

    /**
     *
     * @param custAccIdcardDob
     */
    public void setCustAccIdcardDob(String custAccIdcardDob) {
        this.custAccIdcardDob = custAccIdcardDob;
    }

    /**
     *
     * @return
     */
    public char getHavesms() {
        return this.havesms;
    }

    /**
     *
     * @param havesms
     */
    public void setHavesms(char havesms) {
        this.havesms = havesms;
    }

    /**
     *
     * @return
     */
    public String getMobile() {
        return this.mobile;
    }

    /**
     *
     * @param mobile
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     *
     * @return
     */
    public char getActive() {
        return this.active;
    }

    /**
     *
     * @param active
     */
    public void setActive(char active) {
        this.active = active;
    }

    /**
     *
     * @return
     */
    public Date getDatcreated() {
        return this.datcreated;
    }

    /**
     *
     * @param datcreated
     */
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    /**
     *
     * @return
     */
    public String getMakerid() {
        return this.makerid;
    }

    /**
     *
     * @param makerid
     */
    public void setMakerid(String makerid) {
        this.makerid = makerid;
    }

    /**
     *
     * @return
     */
    public String getBranchcode() {
        return this.branchcode;
    }

    /**
     *
     * @param branchcode
     */
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }

    /**
     *
     * @return
     */
    public String getCheckerid() {
        return this.checkerid;
    }

    /**
     *
     * @param checkerid
     */
    public void setCheckerid(String checkerid) {
        this.checkerid = checkerid;
    }

    /**
     *
     * @return
     */
    public Date getDatautheq() {
        return this.datautheq;
    }

    /**
     *
     * @param datautheq
     */
    public void setDatautheq(Date datautheq) {
        this.datautheq = datautheq;
    }

    /**
     *
     * @return
     */
    public String getMakeridModify() {
        return this.makeridModify;
    }

    /**
     *
     * @param makeridModify
     */
    public void setMakeridModify(String makeridModify) {
        this.makeridModify = makeridModify;
    }

    /**
     *
     * @return
     */
    public String getMakeridModifyBrncode() {
        return this.makeridModifyBrncode;
    }

    /**
     *
     * @param makeridModifyBrncode
     */
    public void setMakeridModifyBrncode(String makeridModifyBrncode) {
        this.makeridModifyBrncode = makeridModifyBrncode;
    }

    /**
     *
     * @return
     */
    public Date getMakeridModifyDatcreated() {
        return this.makeridModifyDatcreated;
    }

    /**
     *
     * @param makeridModifyDatcreated
     */
    public void setMakeridModifyDatcreated(Date makeridModifyDatcreated) {
        this.makeridModifyDatcreated = makeridModifyDatcreated;
    }

    /**
     *
     * @return
     */
    public String getCheckeridModify() {
        return this.checkeridModify;
    }

    /**
     *
     * @param checkeridModify
     */
    public void setCheckeridModify(String checkeridModify) {
        this.checkeridModify = checkeridModify;
    }

    /**
     *
     * @return
     */
    public Date getCheckeridModifyDatcreate() {
        return this.checkeridModifyDatcreate;
    }

    /**
     *
     * @param checkeridModifyDatcreate
     */
    public void setCheckeridModifyDatcreate(Date checkeridModifyDatcreate) {
        this.checkeridModifyDatcreate = checkeridModifyDatcreate;
    }

    /**
     *
     * @return
     */
    public Date getLastsendsms() {
        return this.lastsendsms;
    }

    /**
     *
     * @param lastsendsms
     */
    public void setLastsendsms(Date lastsendsms) {
        this.lastsendsms = lastsendsms;
    }

    /**
     *
     * @return
     */
    public Character getIsapproved() {
        return this.isapproved;
    }

    /**
     *
     * @param isapproved
     */
    public void setIsapproved(Character isapproved) {
        this.isapproved = isapproved;
    }

    /**
     *
     * @return
     */
    public Set<BPblAutoReg> getBPblAutoRegs() {
        return this.BPblAutoRegs;
    }

    /**
     *
     * @param BPblAutoRegs
     */
    public void setBPblAutoRegs(Set<BPblAutoReg> BPblAutoRegs) {
        this.BPblAutoRegs = BPblAutoRegs;
    }

}
