package scb.com.vn.dbi.dto;

/**
 * CardType generated by hbm2java
 */
public class CardType implements java.io.Serializable {

    private String cardtype;
    private String brn;
    private String cardname;

    /**
     * Create a new instance of CardType
     */
    public CardType() {
    }

    /**
     *
     * @param cardtype
     */
    public CardType(String cardtype) {
        this.cardtype = cardtype;
    }

    /**
     *
     * @param cardtype
     * @param brn
     * @param cardname
     */
    public CardType(String cardtype, String brn, String cardname) {
        this.cardtype = cardtype;
        this.brn = brn;
        this.cardname = cardname;
    }

    /**
     *
     * @return
     */
    public String getCardtype() {
        return this.cardtype;
    }

    /**
     *
     * @param cardtype
     */
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype;
    }

    /**
     *
     * @return
     */
    public String getBrn() {
        return this.brn;
    }

    /**
     *
     * @param brn
     */
    public void setBrn(String brn) {
        this.brn = brn;
    }

    /**
     *
     * @return
     */
    public String getCardname() {
        return this.cardname;
    }

    /**
     *
     * @param cardname
     */
    public void setCardname(String cardname) {
        this.cardname = cardname;
    }
}
