package scb.com.vn.dbi.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 * EbIssuecard generated by hbm2java
 */
public class EbIssuecard implements java.io.Serializable {

    private Integer id;
    private CardType CARDTYPE;
    private String registertype;
    private String brn;
    private Character issuetype;
    private String sourceaccount;
    private Long cardaccountno;
    private String refFcubs;
    private BigDecimal amountfee;
    private BigDecimal amounttax;
    private String fullname;
    private String idnumber;
    private Integer birthday;
    private String relationship;
    private Character cardrecievemode;
    private String branchcode;
    private String address;
    private BigDecimal limitrequest;
    private String guaranteemode;
    private String guaranteemodeinfo;
    private String loanpurpose;
    private Long loanamount;
    private Short expectedtime;
    private BigDecimal expectinterest;
    private String repaymentsource;
    private String idchannel;
    private VwMbCustomer CUSTOMERNO;
    private String idchanneluser;
    private Date insdate;
    private Date checkeddate;
    private String idchecker;
    private String idchannelchecker;
    private String cardno;
    private String accountno;
    private Long accountbalance;
    private String issuebranchcode;
    private Character ischecked;
    private String email;
    private Character existscb;
    private Character existotherbank;
    private Character incomegreaterfivem;
    private String telCus;
    private String issueidDate;
    private String issueidPlace;
    private String sex;
    private String ccy;
    private String stateEmailPeriod;
    private String statePostPeriod;
    private String isAttach;
    private String collateral;
    private String address01;
    private String guaranteeFromDate;
    private String guaranteeToDate;
    private String collateralDesc;
    private String guaranteeType;

    /**
     * Create a new instance of EbIssuecard
     */
    public EbIssuecard() {
    }

    /**
     *
     * @param CARDTYPE
     * @param registertype
     * @param brn
     * @param issuetype
     * @param sourceaccount
     * @param cardaccountno
     * @param refFcubs
     * @param amountfee
     * @param amounttax
     * @param fullname
     * @param idnumber
     * @param birthday
     * @param relationship
     * @param cardrecievemode
     * @param branchcode
     * @param address
     * @param limitrequest
     * @param guaranteemode
     * @param guaranteemodeinfo
     * @param loanpurpose
     * @param loanamount
     * @param expectedtime
     * @param expectinterest
     * @param repaymentsource
     * @param idchannel
     * @param CUSTOMERNO
     * @param idchanneluser
     * @param insdate
     * @param checkeddate
     * @param idchecker
     * @param idchannelchecker
     * @param cardno
     * @param accountno
     * @param accountbalance
     * @param issuebranchcode
     * @param ischecked
     * @param email
     * @param existscb
     * @param existotherbank
     * @param incomegreaterfivem
     * @param telCus
     * @param issueidDate
     * @param issueidPlace
     * @param sex
     */
    public EbIssuecard(CardType CARDTYPE, String registertype, String brn, Character issuetype, String sourceaccount, Long cardaccountno, String refFcubs, BigDecimal amountfee, BigDecimal amounttax, String fullname, String idnumber, Integer birthday, String relationship, Character cardrecievemode, String branchcode, String address, BigDecimal limitrequest, String guaranteemode, String guaranteemodeinfo, String loanpurpose, Long loanamount, Short expectedtime, BigDecimal expectinterest, String repaymentsource, String idchannel, VwMbCustomer CUSTOMERNO, String idchanneluser, Date insdate, Date checkeddate, String idchecker, String idchannelchecker, String cardno, String accountno, Long accountbalance, String issuebranchcode, Character ischecked, String email, Character existscb, Character existotherbank, Character incomegreaterfivem, String telCus, String issueidDate,
            String issueidPlace, String sex, String stateEmailPeriod, String statePostPeriod, String isAttach) {
        this.CARDTYPE = CARDTYPE;
        this.registertype = registertype;
        this.brn = brn;
        this.issuetype = issuetype;
        this.sourceaccount = sourceaccount;
        this.cardaccountno = cardaccountno;
        this.refFcubs = refFcubs;
        this.amountfee = amountfee;
        this.amounttax = amounttax;
        this.fullname = fullname;
        this.idnumber = idnumber;
        this.birthday = birthday;
        this.relationship = relationship;
        this.cardrecievemode = cardrecievemode;
        this.branchcode = branchcode;
        this.address = address;
        this.limitrequest = limitrequest;
        this.guaranteemode = guaranteemode;
        this.guaranteemodeinfo = guaranteemodeinfo;
        this.loanpurpose = loanpurpose;
        this.loanamount = loanamount;
        this.expectedtime = expectedtime;
        this.expectinterest = expectinterest;
        this.repaymentsource = repaymentsource;
        this.idchannel = idchannel;
        this.CUSTOMERNO = CUSTOMERNO;
        this.idchanneluser = idchanneluser;
        this.insdate = insdate;
        this.checkeddate = checkeddate;
        this.idchecker = idchecker;
        this.idchannelchecker = idchannelchecker;
        this.cardno = cardno;
        this.accountno = accountno;
        this.accountbalance = accountbalance;
        this.issuebranchcode = issuebranchcode;
        this.ischecked = ischecked;
        this.email = email;
        this.existscb = existscb;
        this.existotherbank = existotherbank;
        this.incomegreaterfivem = incomegreaterfivem;
        this.telCus = telCus;
        this.issueidDate = issueidDate;
        this.issueidPlace = issueidPlace;
        this.sex = sex;
        this.stateEmailPeriod = stateEmailPeriod;
        this.statePostPeriod = statePostPeriod;
        this.isAttach = isAttach;
    }

    /**
     *
     * @return
     */
    public Integer getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public CardType getCARDTYPE() {
        return this.CARDTYPE;
    }

    /**
     *
     * @param CARDTYPE
     */
    public void setCARDTYPE(CardType CARDTYPE) {
        this.CARDTYPE = CARDTYPE;
    }

    /**
     *
     * @return
     */
    public String getRegistertype() {
        return this.registertype;
    }

    /**
     *
     * @param registertype
     */
    public void setRegistertype(String registertype) {
        this.registertype = registertype;
    }

    /**
     *
     * @return
     */
    public String getBrn() {
        return this.brn;
    }

    /**
     *
     * @param brn
     */
    public void setBrn(String brn) {
        this.brn = brn;
    }

    /**
     *
     * @return
     */
    public Character getIssuetype() {
        return this.issuetype;
    }

    /**
     *
     * @param issuetype
     */
    public void setIssuetype(Character issuetype) {
        this.issuetype = issuetype;
    }

    /**
     *
     * @return
     */
    public String getSourceaccount() {
        return this.sourceaccount;
    }

    /**
     *
     * @param sourceaccount
     */
    public void setSourceaccount(String sourceaccount) {
        this.sourceaccount = sourceaccount;
    }

    /**
     *
     * @return
     */
    public Long getCardaccountno() {
        return this.cardaccountno;
    }

    /**
     *
     * @param cardaccountno
     */
    public void setCardaccountno(Long cardaccountno) {
        this.cardaccountno = cardaccountno;
    }

    /**
     *
     * @return
     */
    public String getRefFcubs() {
        return this.refFcubs;
    }

    /**
     *
     * @param refFcubs
     */
    public void setRefFcubs(String refFcubs) {
        this.refFcubs = refFcubs;
    }

    /**
     *
     * @return
     */
    public BigDecimal getAmountfee() {
        return this.amountfee;
    }

    /**
     *
     * @param amountfee
     */
    public void setAmountfee(BigDecimal amountfee) {
        this.amountfee = amountfee;
    }

    /**
     *
     * @return
     */
    public BigDecimal getAmounttax() {
        return this.amounttax;
    }

    /**
     *
     * @param amounttax
     */
    public void setAmounttax(BigDecimal amounttax) {
        this.amounttax = amounttax;
    }

    /**
     *
     * @return
     */
    public String getFullname() {
        return this.fullname;
    }

    /**
     *
     * @param fullname
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     *
     * @return
     */
    public String getIdnumber() {
        return this.idnumber;
    }

    /**
     *
     * @param idnumber
     */
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber;
    }

    /**
     *
     * @return
     */
    public Integer getBirthday() {
        return this.birthday;
    }

    /**
     *
     * @param birthday
     */
    public void setBirthday(Integer birthday) {
        this.birthday = birthday;
    }

    /**
     *
     * @return
     */
    public String getRelationship() {
        return this.relationship;
    }

    /**
     *
     * @param relationship
     */
    public void setRelationship(String relationship) {
        this.relationship = relationship;
    }

    /**
     *
     * @return
     */
    public Character getCardrecievemode() {
        return this.cardrecievemode;
    }

    /**
     *
     * @param cardrecievemode
     */
    public void setCardrecievemode(Character cardrecievemode) {
        this.cardrecievemode = cardrecievemode;
    }

    /**
     *
     * @return
     */
    public String getBranchcode() {
        return this.branchcode;
    }

    /**
     *
     * @param branchcode
     */
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }

    /**
     *
     * @return
     */
    public String getAddress() {
        return this.address;
    }

    /**
     *
     * @param address
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     *
     * @return
     */
    public BigDecimal getLimitrequest() {
        return this.limitrequest;
    }

    /**
     *
     * @param limitrequest
     */
    public void setLimitrequest(BigDecimal limitrequest) {
        this.limitrequest = limitrequest;
    }

    /**
     *
     * @return
     */
    public String getGuaranteemode() {
        return this.guaranteemode;
    }

    /**
     *
     * @param guaranteemode
     */
    public void setGuaranteemode(String guaranteemode) {
        this.guaranteemode = guaranteemode;
    }

    /**
     *
     * @return
     */
    public String getGuaranteemodeinfo() {
        return this.guaranteemodeinfo;
    }

    /**
     *
     * @param guaranteemodeinfo
     */
    public void setGuaranteemodeinfo(String guaranteemodeinfo) {
        this.guaranteemodeinfo = guaranteemodeinfo;
    }

    /**
     *
     * @return
     */
    public String getLoanpurpose() {
        return this.loanpurpose;
    }

    /**
     *
     * @param loanpurpose
     */
    public void setLoanpurpose(String loanpurpose) {
        this.loanpurpose = loanpurpose;
    }

    /**
     *
     * @return
     */
    public Long getLoanamount() {
        return this.loanamount;
    }

    /**
     *
     * @param loanamount
     */
    public void setLoanamount(Long loanamount) {
        this.loanamount = loanamount;
    }

    /**
     *
     * @return
     */
    public Short getExpectedtime() {
        return this.expectedtime;
    }

    /**
     *
     * @param expectedtime
     */
    public void setExpectedtime(Short expectedtime) {
        this.expectedtime = expectedtime;
    }

    /**
     *
     * @return
     */
    public BigDecimal getExpectinterest() {
        return this.expectinterest;
    }

    /**
     *
     * @param expectinterest
     */
    public void setExpectinterest(BigDecimal expectinterest) {
        this.expectinterest = expectinterest;
    }

    /**
     *
     * @return
     */
    public String getRepaymentsource() {
        return this.repaymentsource;
    }

    /**
     *
     * @param repaymentsource
     */
    public void setRepaymentsource(String repaymentsource) {
        this.repaymentsource = repaymentsource;
    }

    /**
     *
     * @return
     */
    public String getIdchannel() {
        return this.idchannel;
    }

    /**
     *
     * @param idchannel
     */
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    /**
     *
     * @return
     */
    public String getIdchanneluser() {
        return this.idchanneluser;
    }

    /**
     *
     * @param idchanneluser
     */
    public void setIdchanneluser(String idchanneluser) {
        this.idchanneluser = idchanneluser;
    }

    /**
     *
     * @return
     */
    public Date getInsdate() {
        return this.insdate;
    }

    /**
     *
     * @param insdate
     */
    public void setInsdate(Date insdate) {
        this.insdate = insdate;
    }

    /**
     *
     * @return
     */
    public Date getCheckeddate() {
        return this.checkeddate;
    }

    /**
     *
     * @param checkeddate
     */
    public void setCheckeddate(Date checkeddate) {
        this.checkeddate = checkeddate;
    }

    /**
     *
     * @return
     */
    public String getIdchecker() {
        return this.idchecker;
    }

    /**
     *
     * @param idchecker
     */
    public void setIdchecker(String idchecker) {
        this.idchecker = idchecker;
    }

    /**
     *
     * @return
     */
    public String getIdchannelchecker() {
        return this.idchannelchecker;
    }

    /**
     *
     * @param idchannelchecker
     */
    public void setIdchannelchecker(String idchannelchecker) {
        this.idchannelchecker = idchannelchecker;
    }

    /**
     *
     * @return
     */
    public String getCardno() {
        return this.cardno;
    }

    /**
     *
     * @param cardno
     */
    public void setCardno(String cardno) {
        this.cardno = cardno;
    }

    /**
     *
     * @return
     */
    public String getAccountno() {
        return this.accountno;
    }

    /**
     *
     * @param accountno
     */
    public void setAccountno(String accountno) {
        this.accountno = accountno;
    }

    /**
     *
     * @return
     */
    public Long getAccountbalance() {
        return this.accountbalance;
    }

    /**
     *
     * @param accountbalance
     */
    public void setAccountbalance(Long accountbalance) {
        this.accountbalance = accountbalance;
    }

    /**
     *
     * @return
     */
    public String getIssuebranchcode() {
        return this.issuebranchcode;
    }

    /**
     *
     * @param issuebranchcode
     */
    public void setIssuebranchcode(String issuebranchcode) {
        this.issuebranchcode = issuebranchcode;
    }

    /**
     * @return the CUSTOMERNO
     */
    public VwMbCustomer getCUSTOMERNO() {
        return CUSTOMERNO;
    }

    /**
     * @param CUSTOMERNO the CUSTOMERNO to set
     */
    public void setCUSTOMERNO(VwMbCustomer CUSTOMERNO) {
        this.CUSTOMERNO = CUSTOMERNO;
    }

    /**
     *
     * @return
     */
    public Character getIschecked() {
        return this.ischecked;
    }

    /**
     *
     * @param ischecked
     */
    public void setIschecked(Character ischecked) {
        this.ischecked = ischecked;
    }

    /**
     * @return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email the email to set
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return the existscb
     */
    public Character getExistscb() {
        return existscb;
    }

    /**
     * @param existscb the existscb to set
     */
    public void setExistscb(Character existscb) {
        this.existscb = existscb;
    }

    /**
     * @return the existotherbank
     */
    public Character getExistotherbank() {
        return existotherbank;
    }

    /**
     * @param existotherbank the existotherbank to set
     */
    public void setExistotherbank(Character existotherbank) {
        this.existotherbank = existotherbank;
    }

    /**
     * @return the incomegreaterfivem
     */
    public Character getIncomegreaterfivem() {
        return incomegreaterfivem;
    }

    /**
     * @param incomegreaterfivem the incomegreaterfivem to set
     */
    public void setIncomegreaterfivem(Character incomegreaterfivem) {
        this.incomegreaterfivem = incomegreaterfivem;
    }

    /**
     * @return the addressCus
     */
    public String getTelCus() {
        return telCus;
    }

    /**
     * @param telCus
     */
    public void setTelCus(String telCus) {
        this.telCus = telCus;
    }

    /**
     *
     * @return
     */
    public String getIssueidDate() {
        return this.issueidDate;
    }

    /**
     *
     * @param issueidDate
     */
    public void setIssueidDate(String issueidDate) {
        this.issueidDate = issueidDate;
    }

    /**
     *
     * @return
     */
    public String getIssueidPlace() {
        return this.issueidPlace;
    }

    /**
     *
     * @param issueidPlace
     */
    public void setIssueidPlace(String issueidPlace) {
        this.issueidPlace = issueidPlace;
    }

    /**
     *
     * @return
     */
    public String getSex() {
        return this.sex;
    }

    /**
     *
     * @param sex
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * @return the ccy
     */
    public String getCcy() {
        return ccy;
    }

    /**
     * @param ccy the ccy to set
     */
    public void setCcy(String ccy) {
        this.ccy = ccy;
    }

    /**
     * @return the stateEmailPeriod
     */
    public String getStateEmailPeriod() {
        return stateEmailPeriod;
    }

    /**
     * @param stateEmailPeriod the stateEmailPeriod to set
     */
    public void setStateEmailPeriod(String stateEmailPeriod) {
        this.stateEmailPeriod = stateEmailPeriod;
    }

    /**
     * @return the statePostPeriod
     */
    public String getStatePostPeriod() {
        return statePostPeriod;
    }

    /**
     * @param statePostPeriod the statePostPeriod to set
     */
    public void setStatePostPeriod(String statePostPeriod) {
        this.statePostPeriod = statePostPeriod;
    }

    /**
     * @return the isAttach
     */
    public String getIsAttach() {
        return isAttach;
    }

    /**
     * @param isAttach the isAttach to set
     */
    public void setIsAttach(String isAttach) {
        this.isAttach = isAttach;
    }

    public String getCollateral() {
        return collateral;
    }

    public void setCollateral(String collateral) {
        this.collateral = collateral;
    }

    public String getAddress01() {
        return address01;
    }

    public void setAddress01(String address01) {
        this.address01 = address01;
    }

    public String getGuaranteeFromDate() {
        return guaranteeFromDate;
    }

    public void setGuaranteeFromDate(String guaranteeFromDate) {
        this.guaranteeFromDate = guaranteeFromDate;
    }

    public String getGuaranteeToDate() {
        return guaranteeToDate;
    }

    public void setGuaranteeToDate(String guaranteeToDate) {
        this.guaranteeToDate = guaranteeToDate;
    }

    public String getCollateralDesc() {
        return collateralDesc;
    }

    public void setCollateralDesc(String collateralDesc) {
        this.collateralDesc = collateralDesc;
    }

    public String getGuaranteeType() {
        return guaranteeType;
    }

    public void setGuaranteeType(String guaranteeType) {
        this.guaranteeType = guaranteeType;
    }
}
