package scb.com.vn.dbi.dto;

import java.util.HashSet;
import java.util.Set;

/**
 * EtsMstusertypes generated by hbm2java
 */
public class EtsMstusertypes implements java.io.Serializable {

    private String typeuser;
    private String description;
    private String isenabled;
    private String hasmultcust;
    private String flginternaltype;
    private String baseusertype;
    private String hascustid;
    private char lookuptype;
    private Set etsMstroles = new HashSet(0);

    /**
     * Create a new instance of EtsMstusertypes
     */
    public EtsMstusertypes() {
    }

    /**
     *
     * @param typeuser
     * @param description
     * @param isenabled
     * @param hasmultcust
     * @param baseusertype
     * @param hascustid
     * @param lookuptype
     */
    public EtsMstusertypes(String typeuser, String description, String isenabled, String hasmultcust, String baseusertype, String hascustid, char lookuptype) {
        this.typeuser = typeuser;
        this.description = description;
        this.isenabled = isenabled;
        this.hasmultcust = hasmultcust;
        this.baseusertype = baseusertype;
        this.hascustid = hascustid;
        this.lookuptype = lookuptype;
    }

    /**
     *
     * @param typeuser
     * @param description
     * @param isenabled
     * @param hasmultcust
     * @param flginternaltype
     * @param baseusertype
     * @param hascustid
     * @param lookuptype
     * @param etsMstroles
     */
    public EtsMstusertypes(String typeuser, String description, String isenabled, String hasmultcust, String flginternaltype, String baseusertype, String hascustid, char lookuptype, Set etsMstroles) {
        this.typeuser = typeuser;
        this.description = description;
        this.isenabled = isenabled;
        this.hasmultcust = hasmultcust;
        this.flginternaltype = flginternaltype;
        this.baseusertype = baseusertype;
        this.hascustid = hascustid;
        this.lookuptype = lookuptype;
        this.etsMstroles = etsMstroles;
    }

    /**
     *
     * @return
     */
    public String getTypeuser() {
        return this.typeuser;
    }

    /**
     *
     * @param typeuser
     */
    public void setTypeuser(String typeuser) {
        this.typeuser = typeuser;
    }

    /**
     *
     * @return
     */
    public String getDescription() {
        return this.description;
    }

    /**
     *
     * @param description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     *
     * @return
     */
    public String getIsenabled() {
        return this.isenabled;
    }

    /**
     *
     * @param isenabled
     */
    public void setIsenabled(String isenabled) {
        this.isenabled = isenabled;
    }

    /**
     *
     * @return
     */
    public String getHasmultcust() {
        return this.hasmultcust;
    }

    /**
     *
     * @param hasmultcust
     */
    public void setHasmultcust(String hasmultcust) {
        this.hasmultcust = hasmultcust;
    }

    /**
     *
     * @return
     */
    public String getFlginternaltype() {
        return this.flginternaltype;
    }

    /**
     *
     * @param flginternaltype
     */
    public void setFlginternaltype(String flginternaltype) {
        this.flginternaltype = flginternaltype;
    }

    /**
     *
     * @return
     */
    public String getBaseusertype() {
        return this.baseusertype;
    }

    /**
     *
     * @param baseusertype
     */
    public void setBaseusertype(String baseusertype) {
        this.baseusertype = baseusertype;
    }

    /**
     *
     * @return
     */
    public String getHascustid() {
        return this.hascustid;
    }

    /**
     *
     * @param hascustid
     */
    public void setHascustid(String hascustid) {
        this.hascustid = hascustid;
    }

    /**
     *
     * @return
     */
    public char getLookuptype() {
        return this.lookuptype;
    }

    /**
     *
     * @param lookuptype
     */
    public void setLookuptype(char lookuptype) {
        this.lookuptype = lookuptype;
    }

    /**
     *
     * @return
     */
    public Set getEtsMstroles() {
        return this.etsMstroles;
    }

    /**
     *
     * @param etsMstroles
     */
    public void setEtsMstroles(Set etsMstroles) {
        this.etsMstroles = etsMstroles;
    }

}
