package scb.com.vn.dbi.dto;

/**
 * EtsMstbranch generated by hbm2java
 */
public class EtsMstbranch implements java.io.Serializable {

    private String code;
    private String name;
    private String address;
    private String phone;
    private String fax;
    private String representer;
    private String representerPos;
    private String pageauthNo;
    private String pageauthDate;

    /**
     * Create a new instance of EtsMstbranch
     */
    public EtsMstbranch() {
    }

    /**
     *
     * @param code
     */
    public EtsMstbranch(String code) {
        this.code = code;
    }

    /**
     *
     * @param code
     * @param name
     * @param address
     * @param phone
     * @param fax
     * @param representer
     * @param representerPos
     * @param pageauthNo
     * @param pageauthDate
     */
    public EtsMstbranch(String code, String name, String address, String phone, String fax, String representer, String representerPos, String pageauthNo, String pageauthDate) {
        this.code = code;
        this.name = name;
        this.address = address;
        this.phone = phone;
        this.fax = fax;
        this.representer = representer;
        this.representerPos = representerPos;
        this.pageauthNo = pageauthNo;
        this.pageauthDate = pageauthDate;
    }

    /**
     *
     * @return
     */
    public String getCode() {
        return this.code;
    }

    /**
     *
     * @param code
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     *
     * @return
     */
    public String getName() {
        return this.name;
    }

    /**
     *
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     *
     * @return
     */
    public String getAddress() {
        return this.address;
    }

    /**
     *
     * @param address
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     *
     * @return
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     *
     * @param phone
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     *
     * @return
     */
    public String getFax() {
        return this.fax;
    }

    /**
     *
     * @param fax
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     *
     * @return
     */
    public String getRepresenter() {
        return this.representer;
    }

    /**
     *
     * @param representer
     */
    public void setRepresenter(String representer) {
        this.representer = representer;
    }

    /**
     *
     * @return
     */
    public String getRepresenterPos() {
        return this.representerPos;
    }

    /**
     *
     * @param representerPos
     */
    public void setRepresenterPos(String representerPos) {
        this.representerPos = representerPos;
    }

    /**
     *
     * @return
     */
    public String getPageauthNo() {
        return this.pageauthNo;
    }

    /**
     *
     * @param pageauthNo
     */
    public void setPageauthNo(String pageauthNo) {
        this.pageauthNo = pageauthNo;
    }

    /**
     *
     * @return
     */
    public String getPageauthDate() {
        return this.pageauthDate;
    }

    /**
     *
     * @param pageauthDate
     */
    public void setPageauthDate(String pageauthDate) {
        this.pageauthDate = pageauthDate;
    }

}
