package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * EtsMstchanneluser generated by hbm2java
 */
public class EtsMstchanneluser implements java.io.Serializable {

    private static final long serialVersionUID = -1601367309834759824L;

    private String idchanneluser;
    private String id_entity;
    private String iduser;
    private String idchannel;
    private String password;
    private String lockflag;
    private Date datlastsucclogin;
    private Date datlastfaillogin;
    private int nbrfailedlogins;
    private int nbrlogins;
    private String defaulttxn;
    private Date datsoftlastfail;
    private String flagforcechangepwd;
    private int failedattemptcnt;
    private String flagforcechangetxnpwd;
    private Date datelastchangepass;

    /**
     * Create a new instance of EtsMstchanneluser
     */
    public EtsMstchanneluser() {
    }

    /**
     *
     * @return
     */
    public String getIdchanneluser() {
        return this.idchanneluser;
    }

    /**
     *
     * @param idchanneluser
     */
    public void setIdchanneluser(String idchanneluser) {
        this.idchanneluser = idchanneluser;
    }

    /**
     *
     * @return
     */
    public String getId_entity() {
        return this.id_entity;
    }

    /**
     *
     * @param id_entity
     */
    public void setId_entity(String id_entity) {
        this.id_entity = id_entity;
    }

    /**
     *
     * @return
     */
    public String getIduser() {
        return this.iduser;
    }

    /**
     *
     * @param iduser
     */
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    /**
     *
     * @return
     */
    public String getIdchannel() {
        return this.idchannel;
    }

    /**
     *
     * @param idchannel
     */
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    /**
     *
     * @return
     */
    public String getPassword() {
        return this.password;
    }

    /**
     *
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     *
     * @return
     */
    public String getLockflag() {
        return this.lockflag;
    }

    /**
     *
     * @param lockflag
     */
    public void setLockflag(String lockflag) {
        this.lockflag = lockflag;
    }

    /**
     *
     * @return
     */
    public Date getDatlastsucclogin() {
        return this.datlastsucclogin;
    }

    /**
     *
     * @param datlastsucclogin
     */
    public void setDatlastsucclogin(Date datlastsucclogin) {
        this.datlastsucclogin = datlastsucclogin;
    }

    /**
     *
     * @return
     */
    public Date getDatlastfaillogin() {
        return this.datlastfaillogin;
    }

    /**
     *
     * @param datlastfaillogin
     */
    public void setDatlastfaillogin(Date datlastfaillogin) {
        this.datlastfaillogin = datlastfaillogin;
    }

    /**
     *
     * @return
     */
    public int getNbrfailedlogins() {
        return this.nbrfailedlogins;
    }

    /**
     *
     * @param nbrfailedlogins
     */
    public void setNbrfailedlogins(int nbrfailedlogins) {
        this.nbrfailedlogins = nbrfailedlogins;
    }

    /**
     *
     * @return
     */
    public int getNbrlogins() {
        return this.nbrlogins;
    }

    /**
     *
     * @param nbrlogins
     */
    public void setNbrlogins(int nbrlogins) {
        this.nbrlogins = nbrlogins;
    }

    /**
     *
     * @return
     */
    public String getDefaulttxn() {
        return this.defaulttxn;
    }

    /**
     *
     * @param defaulttxn
     */
    public void setDefaulttxn(String defaulttxn) {
        this.defaulttxn = defaulttxn;
    }

    /**
     *
     * @return
     */
    public Date getDatsoftlastfail() {
        return this.datsoftlastfail;
    }

    /**
     *
     * @param datsoftlastfail
     */
    public void setDatsoftlastfail(Date datsoftlastfail) {
        this.datsoftlastfail = datsoftlastfail;
    }

    /**
     *
     * @return
     */
    public String getFlagforcechangepwd() {
        return this.flagforcechangepwd;
    }

    /**
     *
     * @param flagforcechangepwd
     */
    public void setFlagforcechangepwd(String flagforcechangepwd) {
        this.flagforcechangepwd = flagforcechangepwd;
    }

    /**
     *
     * @return
     */
    public int getFailedattemptcnt() {
        return this.failedattemptcnt;
    }

    /**
     *
     * @param failedattemptcnt
     */
    public void setFailedattemptcnt(int failedattemptcnt) {
        this.failedattemptcnt = failedattemptcnt;
    }

    /**
     *
     * @return
     */
    public String getFlagforcechangetxnpwd() {
        return this.flagforcechangetxnpwd;
    }

    /**
     *
     * @param flagforcechangetxnpwd
     */
    public void setFlagforcechangetxnpwd(String flagforcechangetxnpwd) {
        this.flagforcechangetxnpwd = flagforcechangetxnpwd;
    }

    public Date getDatelastchangepass() {
        return datelastchangepass;
    }

    public void setDatelastchangepass(Date datelastchangepass) {
        this.datelastchangepass = datelastchangepass;
    }

   
    

}
