package scb.com.vn.dbi.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 * FeeTransactionUnlock generated by hbm2java
 */
public class FeeTransactionUnlock implements java.io.Serializable {

    private int id;
    private String cif;
    private String custname;
    private String username;
    private BigDecimal sotienphi;
    private String thangnam;
    private String loaikh;
    private String idaccount;
    private Date insdate;
    private Date paydate;
    private String refFcubs;
    private Character isapproved;
    private Character status;
    private String branchCode;
    private String iduserMaker;
    private String idchanneluserMaker;
    private String iduserChecker;
    private String idchanneluserChecker;
    private String tkmd;
    private String fromDate;
    private String toDate;
    private String lockstatus;
    private String thangnamretry;
    private String loaidv;
    private Date insdateChecker;

    /**
     * Create a new instance of FeeTransactionUnlock
     */
    public FeeTransactionUnlock() {
    }

    /**
     *
     * @param id
     * @param sotienphi
     */
    public FeeTransactionUnlock(int id, BigDecimal sotienphi) {
        this.id = id;
        this.sotienphi = sotienphi;
    }

    /**
     *
     * @param id
     * @param cif
     * @param custname
     * @param username
     * @param sotienphi
     * @param thangnam
     * @param loaikh
     * @param idaccount
     * @param insdate
     * @param paydate
     * @param refFcubs
     * @param isapproved
     * @param status
     * @param branchCode
     * @param iduserMaker
     * @param idchanneluserMaker
     * @param iduserChecker
     * @param idchanneluserChecker
     * @param tkmd
     * @param lockstatus
     * @param thangnamretry
     * @param loaidv
     * @param insdateChecker
     */
    public FeeTransactionUnlock(int id, String cif, String custname, String username, BigDecimal sotienphi, String thangnam, String loaikh, String idaccount, Date insdate, Date paydate, String refFcubs, Character isapproved, Character status, String branchCode, String iduserMaker, String idchanneluserMaker, String iduserChecker, String idchanneluserChecker, String tkmd, String lockstatus, String thangnamretry, String loaidv, Date insdateChecker) {
        this.id = id;
        this.cif = cif;
        this.custname = custname;
        this.username = username;
        this.sotienphi = sotienphi;
        this.thangnam = thangnam;
        this.loaikh = loaikh;
        this.idaccount = idaccount;
        this.insdate = insdate;
        this.paydate = paydate;
        this.refFcubs = refFcubs;
        this.isapproved = isapproved;
        this.status = status;
        this.branchCode = branchCode;
        this.iduserMaker = iduserMaker;
        this.idchanneluserMaker = idchanneluserMaker;
        this.iduserChecker = iduserChecker;
        this.idchanneluserChecker = idchanneluserChecker;
        this.tkmd = tkmd;
        this.lockstatus = lockstatus;
        this.thangnamretry = thangnamretry;
        this.thangnamretry = thangnamretry;
        this.loaidv = loaidv;
        this.insdateChecker = insdateChecker;
    }

    /**
     *
     * @return
     */
    public int getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getCif() {
        return this.cif;
    }

    /**
     *
     * @param cif
     */
    public void setCif(String cif) {
        this.cif = cif;
    }

    /**
     *
     * @return
     */
    public String getCustname() {
        return this.custname;
    }

    /**
     *
     * @param custname
     */
    public void setCustname(String custname) {
        this.custname = custname;
    }

    /**
     *
     * @return
     */
    public String getUsername() {
        return this.username;
    }

    /**
     *
     * @param username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     *
     * @return
     */
    public BigDecimal getSotienphi() {
        return this.sotienphi;
    }

    /**
     *
     * @param sotienphi
     */
    public void setSotienphi(BigDecimal sotienphi) {
        this.sotienphi = sotienphi;
    }

    /**
     *
     * @return
     */
    public String getThangnam() {
        return this.thangnam;
    }

    /**
     *
     * @param thangnam
     */
    public void setThangnam(String thangnam) {
        this.thangnam = thangnam;
    }

    /**
     *
     * @return
     */
    public String getLoaikh() {
        return this.loaikh;
    }

    /**
     *
     * @param loaikh
     */
    public void setLoaikh(String loaikh) {
        this.loaikh = loaikh;
    }

    /**
     *
     * @return
     */
    public String getIdaccount() {
        return this.idaccount;
    }

    /**
     *
     * @param idaccount
     */
    public void setIdaccount(String idaccount) {
        this.idaccount = idaccount;
    }

    /**
     *
     * @return
     */
    public Date getInsdate() {
        return this.insdate;
    }

    /**
     *
     * @param insdate
     */
    public void setInsdate(Date insdate) {
        this.insdate = insdate;
    }

    /**
     *
     * @return
     */
    public Date getPaydate() {
        return this.paydate;
    }

    /**
     *
     * @param paydate
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     *
     * @return
     */
    public String getRefFcubs() {
        return this.refFcubs;
    }

    /**
     *
     * @param refFcubs
     */
    public void setRefFcubs(String refFcubs) {
        this.refFcubs = refFcubs;
    }

    /**
     *
     * @return
     */
    public Character getIsapproved() {
        return this.isapproved;
    }

    /**
     *
     * @param isapproved
     */
    public void setIsapproved(Character isapproved) {
        this.isapproved = isapproved;
    }

    /**
     *
     * @return
     */
    public Character getStatus() {
        return this.status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(Character status) {
        this.status = status;
    }

    /**
     *
     * @return
     */
    public String getBranchCode() {
        return this.branchCode;
    }

    /**
     *
     * @param branchCode
     */
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    /**
     *
     * @return
     */
    public String getIduserMaker() {
        return this.iduserMaker;
    }

    /**
     *
     * @param iduserMaker
     */
    public void setIduserMaker(String iduserMaker) {
        this.iduserMaker = iduserMaker;
    }

    /**
     *
     * @return
     */
    public String getIdchanneluserMaker() {
        return this.idchanneluserMaker;
    }

    /**
     *
     * @param idchanneluserMaker
     */
    public void setIdchanneluserMaker(String idchanneluserMaker) {
        this.idchanneluserMaker = idchanneluserMaker;
    }

    /**
     *
     * @return
     */
    public String getIduserChecker() {
        return this.iduserChecker;
    }

    /**
     *
     * @param iduserChecker
     */
    public void setIduserChecker(String iduserChecker) {
        this.iduserChecker = iduserChecker;
    }

    /**
     *
     * @return
     */
    public String getIdchanneluserChecker() {
        return this.idchanneluserChecker;
    }

    /**
     *
     * @param idchanneluserChecker
     */
    public void setIdchanneluserChecker(String idchanneluserChecker) {
        this.idchanneluserChecker = idchanneluserChecker;
    }

    /**
     * @return the fromDate
     */
    public String getFromDate() {
        return fromDate;
    }

    /**
     * @param fromDate the fromDate to set
     */
    public void setFromDate(String fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * @return the toDate
     */
    public String getToDate() {
        return toDate;
    }

    /**
     * @param toDate the toDate to set
     */
    public void setToDate(String toDate) {
        this.toDate = toDate;
    }

    /**
     * @return the lockstatus
     */
    public String getLockstatus() {
        return lockstatus;
    }

    /**
     * @param lockstatus the lockstatus to set
     */
    public void setLockstatus(String lockstatus) {
        this.lockstatus = lockstatus;
    }

    /**
     * @return the thangnamretry
     */
    public String getThangnamretry() {
        return thangnamretry;
    }

    /**
     * @param thangnamretry the thangnamretry to set
     */
    public void setThangnamretry(String thangnamretry) {
        this.thangnamretry = thangnamretry;
    }

    /**
     * @return the loaidv
     */
    public String getLoaidv() {
        return loaidv;
    }

    /**
     * @param loaidv the loaidv to set
     */
    public void setLoaidv(String loaidv) {
        this.loaidv = loaidv;
    }

    /**
     * @return the insdateChecker
     */
    public Date getInsdateChecker() {
        return insdateChecker;
    }

    /**
     * @param insdateChecker the insdateChecker to set
     */
    public void setInsdateChecker(Date insdateChecker) {
        this.insdateChecker = insdateChecker;
    }

    /**
     * @return the tkmd
     */
    public String getTkmd() {
        return tkmd;
    }

    /**
     * @param tkmd the tkmd to set
     */
    public void setTkmd(String tkmd) {
        this.tkmd = tkmd;
    }

}
