package scb.com.vn.dbi.dto;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;

/**
 * GwEmailTd generated by hbm2java
 */
public class GwEmailTd implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private BigDecimal id;
    private String customerNo;
    private String custAcNo;
    private String email;
    private String status;
    private Date createdDate;
    private String srcchannel;
    private String serialno;
    private Long tdAmount;
    private float  interest;
    

    /**
     * Create a new instance of GwEmailTd
     */
    public GwEmailTd() {
    }

    /**
     *
     * @param customerNo
     * @param custAcNo
     */
    public GwEmailTd(String customerNo, String custAcNo) {
        this.customerNo = customerNo;
        this.custAcNo = custAcNo;
    }

    /**
     *
     * @param customerNo
     * @param custAcNo
     * @param email
     * @param status
     * @param createdDate
     * @param srcchannel
     * @param serialno
     * @param tdAmount
     */
    public GwEmailTd(String customerNo, String custAcNo, String email, String status, Date createdDate, String srcchannel, String serialno, Long tdAmount) {
        this.customerNo = customerNo;
        this.custAcNo = custAcNo;
        this.email = email;
        this.status = status;
        this.createdDate = createdDate;
        this.srcchannel = srcchannel;
        this.serialno = serialno;
        this.tdAmount = tdAmount;        
    }

    /**
     *
     * @return
     */
    public BigDecimal getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getCustomerNo() {
        return this.customerNo;
    }

    /**
     *
     * @param customerNo
     */
    public void setCustomerNo(String customerNo) {
        this.customerNo = customerNo;
    }

    /**
     *
     * @return
     */
    public String getCustAcNo() {
        return this.custAcNo;
    }

    /**
     *
     * @param custAcNo
     */
    public void setCustAcNo(String custAcNo) {
        this.custAcNo = custAcNo;
    }

    /**
     *
     * @return
     */
    public String getEmail() {
        return this.email;
    }

    /**
     *
     * @param email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     *
     * @return
     */
    public String getStatus() {
        return this.status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     *
     * @return
     */
    public Date getCreatedDate() {
        return this.createdDate;
    }

    /**
     *
     * @param createdDate
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     *
     * @return
     */
    public String getSrcchannel() {
        return this.srcchannel;
    }

    /**
     *
     * @param srcchannel
     */
    public void setSrcchannel(String srcchannel) {
        this.srcchannel = srcchannel;
    }

    /**
     * @return the serialno
     */
    public String getSerialno() {
        return serialno;
    }

    /**
     * @param serialno the serialno to set
     */
    public void setSerialno(String serialno) {
        this.serialno = serialno;
    }

    /**
     * @return the tdAmount
     */
    public Long getTdAmount() {
        return tdAmount;
    }

    /**
     * @param tdAmount the tdAmount to set
     */
    public void setTdAmount(Long tdAmount) {
        this.tdAmount = tdAmount;
    }

    /**
     * @return the interest
     */    
    public float getInterest() {
        return interest;
    }

    /**
     * @param interest the interest to set
     */
    
    public void setInterest(float interest) {
        this.interest = interest;
    }

}
