package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * GwEmailTd generated by hbm2java
 */
public class GwTdLucky implements java.io.Serializable {

    private String customerNo;
    private String custAcNo;
    private String status;
    private Date createdDate;
    private String srcchannel;
    private String accountClass;
    private Long tdAmount;
    private String dataStr;

    /**
     * Create a new instance of GwTdLucky
     */
    public GwTdLucky() {
    }

    /**
     *
     * @param customerNo
     * @param custAcNo
     */
    public GwTdLucky(String customerNo, String custAcNo) {
        this.customerNo = customerNo;
        this.custAcNo = custAcNo;
    }

    /**
     *
     * @param customerNo
     * @param custAcNo
     * @param accountClass
     * @param status
     * @param createdDate
     * @param srcchannel
     * @param tdAmount
     * @param dataStr
     */
    public GwTdLucky(String customerNo, String custAcNo, String accountClass, String status, Date createdDate, String srcchannel, Long tdAmount, String dataStr) {
        this.customerNo = customerNo;
        this.custAcNo = custAcNo;
        this.accountClass = accountClass;
        this.status = status;
        this.createdDate = createdDate;
        this.srcchannel = srcchannel;
        this.tdAmount = tdAmount;
        this.dataStr = dataStr;
    }

    /**
     *
     * @return
     */
    public String getCustomerNo() {
        return this.customerNo;
    }

    /**
     *
     * @param customerNo
     */
    public void setCustomerNo(String customerNo) {
        this.customerNo = customerNo;
    }

    /**
     *
     * @return
     */
    public String getCustAcNo() {
        return this.custAcNo;
    }

    /**
     *
     * @param custAcNo
     */
    public void setCustAcNo(String custAcNo) {
        this.custAcNo = custAcNo;
    }

    /**
     *
     * @return
     */
    public String getStatus() {
        return this.status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     *
     * @return
     */
    public Date getCreatedDate() {
        return this.createdDate;
    }

    /**
     *
     * @param createdDate
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     *
     * @return
     */
    public String getSrcchannel() {
        return this.srcchannel;
    }

    /**
     *
     * @param srcchannel
     */
    public void setSrcchannel(String srcchannel) {
        this.srcchannel = srcchannel;
    }

    /**
     * @return the tdAmount
     */
    public Long getTdAmount() {
        return tdAmount;
    }

    /**
     * @param tdAmount the tdAmount to set
     */
    public void setTdAmount(Long tdAmount) {
        this.tdAmount = tdAmount;
    }

    /**
     * @return the accountClass
     */
    public String getAccountClass() {
        return accountClass;
    }

    /**
     * @param accountClass the accountClass to set
     */
    public void setAccountClass(String accountClass) {
        this.accountClass = accountClass;
    }

    /**
     * @return the dataStr
     */
    public String getDataStr() {
        return dataStr;
    }

    /**
     * @param dataStr the dataStr to set
     */
    public void setDataStr(String dataStr) {
        this.dataStr = dataStr;
    }

}
