package scb.com.vn.dbi.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 * PblBillpaid generated by hbm2java
 */
public class InsurancePayment implements java.io.Serializable {

    //getActionform setResult getAmount getAcccust getAccIdaccount
    private int idinsurancepayment;
    private String idpartner;
    private String namepartner;
    private String ownername;
    private String duedt;
    private String polnum;
    private String pretyp;
    private String ownerid;
    private String dataxml;
    private String iduserMaker;
    private String idchanneluserMaker;//10
    private Date insdateMaker;
    private String iduserChecker;
    private String idchanneluserChecker;
    private Date insdateChecker;
    private String idchannel;
    private String usertype;
    private String refPartner;
    private String refFcubs;
    private Long totalamount;
    private int paymentmethod;//20
    private String acccust;
    private String accIdaccount;
    private String accHoldername;
    private String accAddress;
    private Date insdate;
    private Date transdate;
    private Date paydate;
    private Date paydateFcubs;
    private String isapproved;
    private String status;//30
    private String branchcode;
    private String col_code;
    private String checksum;
    private String area;
    private String ref_num;
    private int idpayment;

    private String idcard;
    private String idcardName;
    private String idcardDob;
    private String idcardAddress;
    private String so_ct;

    private String Actionform;
    private String Result;
    private String amount;
    private BigDecimal SOTIEN_TT;
    private String itemChoseTern;
    private int idbcbill;
    
    private String noiCapCMND;
    private String sdtKh;
   

    /**
     *
     * @return
     */
    public int getIdbcbill() {
        return idbcbill;
    }

    /**
     *
     * @param idbcbill
     */
    public void setIdbcbill(int idbcbill) {
        this.idbcbill = idbcbill;
    }

    /**
     *
     * @return
     */
    public String getItemChoseTern() {
        return itemChoseTern;
    }

    /**
     *
     * @param itemChoseTern
     */
    public void setItemChoseTern(String itemChoseTern) {
        this.itemChoseTern = itemChoseTern;
    }

    /**
     *
     * @return
     */
    public String getNamepartner() {
        return namepartner;
    }

    /**
     *
     * @param namepartner
     */
    public void setNamepartner(String namepartner) {
        this.namepartner = namepartner;
    }

    /**
     *
     * @return
     */
    public BigDecimal getSOTIEN_TT() {
        return SOTIEN_TT;
    }

    /**
     *
     * @param SOTIEN_TT
     */
    public void setSOTIEN_TT(BigDecimal SOTIEN_TT) {
        this.SOTIEN_TT = SOTIEN_TT;
    }

    /**
     *
     * @return
     */
    public String getActionform() {
        return Actionform;
    }

    /**
     *
     * @param Actionform
     */
    public void setActionform(String Actionform) {
        this.Actionform = Actionform;
    }

    /**
     *
     * @return
     */
    public String getResult() {
        return Result;
    }

    /**
     *
     * @param Result
     */
    public void setResult(String Result) {
        this.Result = Result;
    }

    /**
     *
     * @return
     */
    public String getAmount() {
        return amount;
    }

    /**
     *
     * @param amount
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     *
     * @return
     */
    public String getSo_ct() {
        return so_ct;
    }

    /**
     *
     * @param so_ct
     */
    public void setSo_ct(String so_ct) {
        this.so_ct = so_ct;
    }

    /**
     *
     * @return
     */
    public String getChecksum() {
        return checksum;
    }

    /**
     *
     * @return
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     *
     * @param idcard
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     *
     * @return
     */
    public String getIdcardName() {
        return idcardName;
    }

    /**
     *
     * @param idcardName
     */
    public void setIdcardName(String idcardName) {
        this.idcardName = idcardName;
    }

    /**
     *
     * @return
     */
    public String getIdcardDob() {
        return idcardDob;
    }

    /**
     *
     * @param idcardDob
     */
    public void setIdcardDob(String idcardDob) {
        this.idcardDob = idcardDob;
    }

    /**
     *
     * @return
     */
    public String getIdcardAddress() {
        return idcardAddress;
    }

    /**
     *
     * @param idcardAddress
     */
    public void setIdcardAddress(String idcardAddress) {
        this.idcardAddress = idcardAddress;
    }

    /**
     *
     * @param checksum
     */
    public void setChecksum(String checksum) {
        this.checksum = checksum;
    }

    /**
     *
     * @return
     */
    public String getCol_code() {
        return col_code;
    }

    /**
     *
     * @param col_code
     */
    public void setCol_code(String col_code) {
        this.col_code = col_code;
    }

    /**
     *
     * @return
     */
    public int getIdinsurancepayment() {
        return idinsurancepayment;
    }

    /**
     *
     * @param idinsurancepayment
     */
    public void setIdinsurancepayment(int idinsurancepayment) {
        this.idinsurancepayment = idinsurancepayment;
    }

    /**
     *
     * @return
     */
    public String getIdpartner() {
        return idpartner;
    }

    /**
     *
     * @param idpartner
     */
    public void setIdpartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @return
     */
    public String getOwnername() {
        return ownername;
    }

    /**
     *
     * @param ownername
     */
    public void setOwnername(String ownername) {
        this.ownername = ownername;
    }

    /**
     *
     * @return
     */
    public String getDuedt() {
        return duedt;
    }

    /**
     *
     * @param duedt
     */
    public void setDuedt(String duedt) {
        this.duedt = duedt;
    }

    /**
     *
     * @return
     */
    public String getPolnum() {
        return polnum;
    }

    /**
     *
     * @param polnum
     */
    public void setPolnum(String polnum) {
        this.polnum = polnum;
    }

    /**
     *
     * @return
     */
    public String getPretyp() {
        return pretyp;
    }

    /**
     *
     * @param pretyp
     */
    public void setPretyp(String pretyp) {
        this.pretyp = pretyp;
    }

    /**
     *
     * @return
     */
    public String getOwnerid() {
        return ownerid;
    }

    /**
     *
     * @param ownerid
     */
    public void setOwnerid(String ownerid) {
        this.ownerid = ownerid;
    }

    /**
     *
     * @return
     */
    public String getDataxml() {
        return dataxml;
    }

    /**
     *
     * @param dataxml
     */
    public void setDataxml(String dataxml) {
        this.dataxml = dataxml;
    }

    /**
     *
     * @return
     */
    public String getIduserMaker() {
        return iduserMaker;
    }

    /**
     *
     * @param iduserMaker
     */
    public void setIduserMaker(String iduserMaker) {
        this.iduserMaker = iduserMaker;
    }

    /**
     *
     * @return
     */
    public String getIdchanneluserMaker() {
        return idchanneluserMaker;
    }

    /**
     *
     * @param idchanneluserMaker
     */
    public void setIdchanneluserMaker(String idchanneluserMaker) {
        this.idchanneluserMaker = idchanneluserMaker;
    }

    /**
     *
     * @return
     */
    public Date getInsdateMaker() {
        return insdateMaker;
    }

    /**
     *
     * @param insdateMaker
     */
    public void setInsdateMaker(Date insdateMaker) {
        this.insdateMaker = insdateMaker;
    }

    /**
     *
     * @return
     */
    public String getIduserChecker() {
        return iduserChecker;
    }

    /**
     *
     * @param iduserChecker
     */
    public void setIduserChecker(String iduserChecker) {
        this.iduserChecker = iduserChecker;
    }

    /**
     *
     * @return
     */
    public String getIdchanneluserChecker() {
        return idchanneluserChecker;
    }

    /**
     *
     * @param idchanneluserChecker
     */
    public void setIdchanneluserChecker(String idchanneluserChecker) {
        this.idchanneluserChecker = idchanneluserChecker;
    }

    /**
     *
     * @return
     */
    public Date getInsdateChecker() {
        return insdateChecker;
    }

    /**
     *
     * @param insdateChecker
     */
    public void setInsdateChecker(Date insdateChecker) {
        this.insdateChecker = insdateChecker;
    }

    /**
     *
     * @return
     */
    public String getIdchannel() {
        return idchannel;
    }

    /**
     *
     * @param idchannel
     */
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    /**
     *
     * @return
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     *
     * @param usertype
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    /**
     *
     * @return
     */
    public String getRefPartner() {
        return refPartner;
    }

    /**
     *
     * @param refPartner
     */
    public void setRefPartner(String refPartner) {
        this.refPartner = refPartner;
    }

    /**
     *
     * @return
     */
    public String getRefFcubs() {
        return refFcubs;
    }

    /**
     *
     * @param refFcubs
     */
    public void setRefFcubs(String refFcubs) {
        this.refFcubs = refFcubs;
    }

    /**
     *
     * @return
     */
    public Long getTotalamount() {
        return totalamount;
    }

    /**
     *
     * @param totalamount
     */
    public void setTotalamount(Long totalamount) {
        this.totalamount = totalamount;
    }

    /**
     *
     * @return
     */
    public Integer getPaymentmethod() {
        return paymentmethod;
    }

    /**
     *
     * @param paymentmethod
     */
    public void setPaymentmethod(Integer paymentmethod) {
        this.paymentmethod = paymentmethod;
    }

    /**
     *
     * @return
     */
    public String getAcccust() {
        return acccust;
    }

    /**
     *
     * @param acccust
     */
    public void setAcccust(String acccust) {
        this.acccust = acccust;
    }

    /**
     *
     * @return
     */
    public String getAccIdaccount() {
        return accIdaccount;
    }

    /**
     *
     * @param accIdaccount
     */
    public void setAccIdaccount(String accIdaccount) {
        this.accIdaccount = accIdaccount;
    }

    /**
     *
     * @return
     */
    public String getAccHoldername() {
        return accHoldername;
    }

    /**
     *
     * @param accHoldername
     */
    public void setAccHoldername(String accHoldername) {
        this.accHoldername = accHoldername;
    }

    /**
     *
     * @return
     */
    public String getAccAddress() {
        return accAddress;
    }

    /**
     *
     * @param accAddress
     */
    public void setAccAddress(String accAddress) {
        this.accAddress = accAddress;
    }

    /**
     *
     * @return
     */
    public Date getInsdate() {
        return insdate;
    }

    /**
     *
     * @param insdate
     */
    public void setInsdate(Date insdate) {
        this.insdate = insdate;
    }

    /**
     *
     * @return
     */
    public Date getTransdate() {
        return transdate;
    }

    /**
     *
     * @param transdate
     */
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }

    /**
     *
     * @return
     */
    public Date getPaydate() {
        return paydate;
    }

    /**
     *
     * @param paydate
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     *
     * @return
     */
    public Date getPaydateFcubs() {
        return paydateFcubs;
    }

    /**
     *
     * @param paydateFcubs
     */
    public void setPaydateFcubs(Date paydateFcubs) {
        this.paydateFcubs = paydateFcubs;
    }

    /**
     *
     * @return
     */
    public String getIsapproved() {
        return isapproved;
    }

    /**
     *
     * @param isapproved
     */
    public void setIsapproved(String isapproved) {
        this.isapproved = isapproved;
    }

    /**
     *
     * @return
     */
    public String getStatus() {
        return status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     *
     * @return
     */
    public String getBranchcode() {
        return branchcode;
    }

    /**
     *
     * @param branchcode
     */
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }

    /**
     *
     * @return
     */
    public String getArea() {
        return area;
    }

    /**
     *
     * @param area
     */
    public void setArea(String area) {
        this.area = area;
    }

    /**
     *
     * @return
     */
    public int getIdpayment() {
        return idpayment;
    }

    /**
     *
     * @param idpayment
     */
    public void setIdpayment(int idpayment) {
        this.idpayment = idpayment;
    }

    /**
     *
     * @return
     */
    public String getRef_num() {
        return ref_num;
    }

    /**
     *
     * @param ref_num
     */
    public void setRef_num(String ref_num) {
        this.ref_num = ref_num;
    }

    public String getNoiCapCMND() {
        return noiCapCMND;
    }

    public void setNoiCapCMND(String noiCapCMND) {
        this.noiCapCMND = noiCapCMND;
    }

    public String getSdtKh() {
        return sdtKh;
    }

    public void setSdtKh(String sdtKh) {
        this.sdtKh = sdtKh;
    }

    
}
