package scb.com.vn.dbi.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 * NapasCollatedId generated by hbm2java
 */
public class NapasCollatedId implements java.io.Serializable {

    private BigDecimal id;
    private String filetype;
    private String transtype;
    private String service;
    private Date createdate;
    private String mti;
    private String f2Sothe;
    private String f3Maxuly;
    private String f62Svc;
    private String f60Tcc;
    private String f4Sotien;
    private String f4Rta;
    private String f49Ccy;
    private String f5Stqt;
    private String f50Ccy;
    private String f9Tygia;
    private String f6Stchuthe;
    private String f6Thucte;
    private String f51Ccy;
    private String f10Tygia;
    private String f11Trace;
    private String f12Giogd;
    private String f13Ngaygd;
    private String f15Ngayqt;
    private String f18Mct;
    private String addinfo;
    private String f41;
    private String acqIss;
    private String mid;
    private String bnb;
    private String f102;
    private String f103Thedich;
    private String addinfoFee;
    private String f37;
    private String f38;
    private String trn;
    private String rrc;
    private String rcv1;
    private String rcv2;
    private String rcv3;
    private String rrcFinal;
    private Date dateFinal;
    private String dateFile;

    private String HIDENCARD;
    private String HIDENCARD_F;

    /**
     * Create a new instance of NapasCollatedId
     */
    public NapasCollatedId() {
    }

    /**
     *
     * @param id
     * @param filetype
     * @param transtype
     * @param service
     * @param createdate
     * @param mti
     * @param f2Sothe
     * @param f3Maxuly
     * @param f62Svc
     * @param f60Tcc
     * @param f4Sotien
     * @param f4Rta
     * @param f49Ccy
     * @param f5Stqt
     * @param f50Ccy
     * @param f9Tygia
     * @param f6Stchuthe
     * @param f6Thucte
     * @param f51Ccy
     * @param f10Tygia
     * @param f11Trace
     * @param f12Giogd
     * @param f13Ngaygd
     * @param f15Ngayqt
     * @param f18Mct
     * @param addinfo
     * @param f41
     * @param acqIss
     * @param mid
     * @param bnb
     * @param f102
     * @param f103Thedich
     * @param addinfoFee
     * @param f37
     * @param f38
     * @param trn
     * @param rrc
     * @param rcv1
     * @param rcv2
     * @param rcv3
     * @param rrcFinal
     * @param dateFinal
     * @param dateFile
     * @param hidenCard
     */
    public NapasCollatedId(BigDecimal id, String filetype, String transtype, String service, Date createdate, String mti, String f2Sothe, String f3Maxuly, String f62Svc, String f60Tcc, String f4Sotien, String f4Rta, String f49Ccy, String f5Stqt, String f50Ccy, String f9Tygia, String f6Stchuthe, String f6Thucte, String f51Ccy, String f10Tygia, String f11Trace, String f12Giogd, String f13Ngaygd, String f15Ngayqt, String f18Mct, String addinfo, String f41, String acqIss, String mid, String bnb, String f102, String f103Thedich, String addinfoFee, String f37, String f38, String trn, String rrc, String rcv1, String rcv2, String rcv3, String rrcFinal, Date dateFinal, String dateFile, String hidenCard) {
        this.id = id;
        this.filetype = filetype;
        this.transtype = transtype;
        this.service = service;
        this.createdate = createdate;
        this.mti = mti;
        this.f2Sothe = f2Sothe;
        this.f3Maxuly = f3Maxuly;
        this.f62Svc = f62Svc;
        this.f60Tcc = f60Tcc;
        this.f4Sotien = f4Sotien;
        this.f4Rta = f4Rta;
        this.f49Ccy = f49Ccy;
        this.f5Stqt = f5Stqt;
        this.f50Ccy = f50Ccy;
        this.f9Tygia = f9Tygia;
        this.f6Stchuthe = f6Stchuthe;
        this.f6Thucte = f6Thucte;
        this.f51Ccy = f51Ccy;
        this.f10Tygia = f10Tygia;
        this.f11Trace = f11Trace;
        this.f12Giogd = f12Giogd;
        this.f13Ngaygd = f13Ngaygd;
        this.f15Ngayqt = f15Ngayqt;
        this.f18Mct = f18Mct;
        this.addinfo = addinfo;
        this.f41 = f41;
        this.acqIss = acqIss;
        this.mid = mid;
        this.bnb = bnb;
        this.f102 = f102;
        this.f103Thedich = f103Thedich;
        this.addinfoFee = addinfoFee;
        this.f37 = f37;
        this.f38 = f38;
        this.trn = trn;
        this.rrc = rrc;
        this.rcv1 = rcv1;
        this.rcv2 = rcv2;
        this.rcv3 = rcv3;
        this.rrcFinal = rrcFinal;
        this.dateFinal = dateFinal;
        this.dateFile = dateFile;
        this.HIDENCARD = hidenCard;
    }

    /**
     *
     * @return
     */
    public String getHIDENCARD_F() {
        return HIDENCARD_F;
    }

    /**
     *
     * @param HIDENCARD_F
     */
    public void setHIDENCARD_F(String HIDENCARD_F) {
        this.HIDENCARD_F = HIDENCARD_F;
    }

    /**
     *
     * @return
     */
    public String getHIDENCARD() {
        return HIDENCARD;
    }

    /**
     *
     * @param HIDENCARD
     */
    public void setHIDENCARD(String HIDENCARD) {
        this.HIDENCARD = HIDENCARD;
    }

    /**
     *
     * @return
     */
    public String getDateFile() {
        return dateFile;
    }

    /**
     *
     * @param dateFile
     */
    public void setDateFile(String dateFile) {
        this.dateFile = dateFile;
    }

    /**
     *
     * @return
     */
    public BigDecimal getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getFiletype() {
        return this.filetype;
    }

    /**
     *
     * @param filetype
     */
    public void setFiletype(String filetype) {
        this.filetype = filetype;
    }

    /**
     *
     * @return
     */
    public String getTranstype() {
        return this.transtype;
    }

    /**
     *
     * @param transtype
     */
    public void setTranstype(String transtype) {
        this.transtype = transtype;
    }

    /**
     *
     * @return
     */
    public String getService() {
        return this.service;
    }

    /**
     *
     * @param service
     */
    public void setService(String service) {
        this.service = service;
    }

    /**
     *
     * @return
     */
    public Date getCreatedate() {
        return this.createdate;
    }

    /**
     *
     * @param createdate
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     *
     * @return
     */
    public String getMti() {
        return this.mti;
    }

    /**
     *
     * @param mti
     */
    public void setMti(String mti) {
        this.mti = mti;
    }

    /**
     *
     * @return
     */
    public String getF2Sothe() {
        return this.f2Sothe;
    }

    /**
     *
     * @param f2Sothe
     */
    public void setF2Sothe(String f2Sothe) {
        this.f2Sothe = f2Sothe;
    }

    /**
     *
     * @return
     */
    public String getF3Maxuly() {
        return this.f3Maxuly;
    }

    /**
     *
     * @param f3Maxuly
     */
    public void setF3Maxuly(String f3Maxuly) {
        this.f3Maxuly = f3Maxuly;
    }

    /**
     *
     * @return
     */
    public String getF62Svc() {
        return this.f62Svc;
    }

    /**
     *
     * @param f62Svc
     */
    public void setF62Svc(String f62Svc) {
        this.f62Svc = f62Svc;
    }

    /**
     *
     * @return
     */
    public String getF60Tcc() {
        return this.f60Tcc;
    }

    /**
     *
     * @param f60Tcc
     */
    public void setF60Tcc(String f60Tcc) {
        this.f60Tcc = f60Tcc;
    }

    /**
     *
     * @return
     */
    public String getF4Sotien() {
        return this.f4Sotien;
    }

    /**
     *
     * @param f4Sotien
     */
    public void setF4Sotien(String f4Sotien) {
        this.f4Sotien = f4Sotien;
    }

    /**
     *
     * @return
     */
    public String getF4Rta() {
        return this.f4Rta;
    }

    /**
     *
     * @param f4Rta
     */
    public void setF4Rta(String f4Rta) {
        this.f4Rta = f4Rta;
    }

    /**
     *
     * @return
     */
    public String getF49Ccy() {
        return this.f49Ccy;
    }

    /**
     *
     * @param f49Ccy
     */
    public void setF49Ccy(String f49Ccy) {
        this.f49Ccy = f49Ccy;
    }

    /**
     *
     * @return
     */
    public String getF5Stqt() {
        return this.f5Stqt;
    }

    /**
     *
     * @param f5Stqt
     */
    public void setF5Stqt(String f5Stqt) {
        this.f5Stqt = f5Stqt;
    }

    /**
     *
     * @return
     */
    public String getF50Ccy() {
        return this.f50Ccy;
    }

    /**
     *
     * @param f50Ccy
     */
    public void setF50Ccy(String f50Ccy) {
        this.f50Ccy = f50Ccy;
    }

    /**
     *
     * @return
     */
    public String getF9Tygia() {
        return this.f9Tygia;
    }

    /**
     *
     * @param f9Tygia
     */
    public void setF9Tygia(String f9Tygia) {
        this.f9Tygia = f9Tygia;
    }

    /**
     *
     * @return
     */
    public String getF6Stchuthe() {
        return this.f6Stchuthe;
    }

    /**
     *
     * @param f6Stchuthe
     */
    public void setF6Stchuthe(String f6Stchuthe) {
        this.f6Stchuthe = f6Stchuthe;
    }

    /**
     *
     * @return
     */
    public String getF6Thucte() {
        return this.f6Thucte;
    }

    /**
     *
     * @param f6Thucte
     */
    public void setF6Thucte(String f6Thucte) {
        this.f6Thucte = f6Thucte;
    }

    /**
     *
     * @return
     */
    public String getF51Ccy() {
        return this.f51Ccy;
    }

    /**
     *
     * @param f51Ccy
     */
    public void setF51Ccy(String f51Ccy) {
        this.f51Ccy = f51Ccy;
    }

    /**
     *
     * @return
     */
    public String getF10Tygia() {
        return this.f10Tygia;
    }

    /**
     *
     * @param f10Tygia
     */
    public void setF10Tygia(String f10Tygia) {
        this.f10Tygia = f10Tygia;
    }

    /**
     *
     * @return
     */
    public String getF11Trace() {
        return this.f11Trace;
    }

    /**
     *
     * @param f11Trace
     */
    public void setF11Trace(String f11Trace) {
        this.f11Trace = f11Trace;
    }

    /**
     *
     * @return
     */
    public String getF12Giogd() {
        return this.f12Giogd;
    }

    /**
     *
     * @param f12Giogd
     */
    public void setF12Giogd(String f12Giogd) {
        this.f12Giogd = f12Giogd;
    }

    /**
     *
     * @return
     */
    public String getF13Ngaygd() {
        return this.f13Ngaygd;
    }

    /**
     *
     * @param f13Ngaygd
     */
    public void setF13Ngaygd(String f13Ngaygd) {
        this.f13Ngaygd = f13Ngaygd;
    }

    /**
     *
     * @return
     */
    public String getF15Ngayqt() {
        return this.f15Ngayqt;
    }

    /**
     *
     * @param f15Ngayqt
     */
    public void setF15Ngayqt(String f15Ngayqt) {
        this.f15Ngayqt = f15Ngayqt;
    }

    /**
     *
     * @return
     */
    public String getF18Mct() {
        return this.f18Mct;
    }

    /**
     *
     * @param f18Mct
     */
    public void setF18Mct(String f18Mct) {
        this.f18Mct = f18Mct;
    }

    /**
     *
     * @return
     */
    public String getAddinfo() {
        return this.addinfo;
    }

    /**
     *
     * @param addinfo
     */
    public void setAddinfo(String addinfo) {
        this.addinfo = addinfo;
    }

    /**
     *
     * @return
     */
    public String getF41() {
        return this.f41;
    }

    /**
     *
     * @param f41
     */
    public void setF41(String f41) {
        this.f41 = f41;
    }

    /**
     *
     * @return
     */
    public String getAcqIss() {
        return this.acqIss;
    }

    /**
     *
     * @param acqIss
     */
    public void setAcqIss(String acqIss) {
        this.acqIss = acqIss;
    }

    /**
     *
     * @return
     */
    public String getMid() {
        return this.mid;
    }

    /**
     *
     * @param mid
     */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /**
     *
     * @return
     */
    public String getBnb() {
        return this.bnb;
    }

    /**
     *
     * @param bnb
     */
    public void setBnb(String bnb) {
        this.bnb = bnb;
    }

    /**
     *
     * @return
     */
    public String getF102() {
        return this.f102;
    }

    /**
     *
     * @param f102
     */
    public void setF102(String f102) {
        this.f102 = f102;
    }

    /**
     *
     * @return
     */
    public String getF103Thedich() {
        return this.f103Thedich;
    }

    /**
     *
     * @param f103Thedich
     */
    public void setF103Thedich(String f103Thedich) {
        this.f103Thedich = f103Thedich;
    }

    /**
     *
     * @return
     */
    public String getAddinfoFee() {
        return this.addinfoFee;
    }

    /**
     *
     * @param addinfoFee
     */
    public void setAddinfoFee(String addinfoFee) {
        this.addinfoFee = addinfoFee;
    }

    /**
     *
     * @return
     */
    public String getF37() {
        return this.f37;
    }

    /**
     *
     * @param f37
     */
    public void setF37(String f37) {
        this.f37 = f37;
    }

    /**
     *
     * @return
     */
    public String getF38() {
        return this.f38;
    }

    /**
     *
     * @param f38
     */
    public void setF38(String f38) {
        this.f38 = f38;
    }

    /**
     *
     * @return
     */
    public String getTrn() {
        return this.trn;
    }

    /**
     *
     * @param trn
     */
    public void setTrn(String trn) {
        this.trn = trn;
    }

    /**
     *
     * @return
     */
    public String getRrc() {
        return this.rrc;
    }

    /**
     *
     * @param rrc
     */
    public void setRrc(String rrc) {
        this.rrc = rrc;
    }

    /**
     *
     * @return
     */
    public String getRcv1() {
        return this.rcv1;
    }

    /**
     *
     * @param rcv1
     */
    public void setRcv1(String rcv1) {
        this.rcv1 = rcv1;
    }

    /**
     *
     * @return
     */
    public String getRcv2() {
        return this.rcv2;
    }

    /**
     *
     * @param rcv2
     */
    public void setRcv2(String rcv2) {
        this.rcv2 = rcv2;
    }

    /**
     *
     * @return
     */
    public String getRcv3() {
        return this.rcv3;
    }

    /**
     *
     * @param rcv3
     */
    public void setRcv3(String rcv3) {
        this.rcv3 = rcv3;
    }

    /**
     *
     * @return
     */
    public String getRrcFinal() {
        return this.rrcFinal;
    }

    /**
     *
     * @param rrcFinal
     */
    public void setRrcFinal(String rrcFinal) {
        this.rrcFinal = rrcFinal;
    }

    /**
     *
     * @return
     */
    public Date getDateFinal() {
        return this.dateFinal;
    }

    /**
     *
     * @param dateFinal
     */
    public void setDateFinal(Date dateFinal) {
        this.dateFinal = dateFinal;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof NapasCollatedId)) {
            return false;
        }
        NapasCollatedId castOther = (NapasCollatedId) other;

        return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
                && ((this.getFiletype().equals(castOther.getFiletype())) || (this.getFiletype() != null && castOther.getFiletype() != null && this.getFiletype().equals(castOther.getFiletype())))
                && ((this.getTranstype().equals(castOther.getTranstype())) || (this.getTranstype() != null && castOther.getTranstype() != null && this.getTranstype().equals(castOther.getTranstype())))
                && ((this.getService().equals(castOther.getService())) || (this.getService() != null && castOther.getService() != null && this.getService().equals(castOther.getService())))
                && ((this.getCreatedate().equals(castOther.getCreatedate())) || (this.getCreatedate() != null && castOther.getCreatedate() != null && this.getCreatedate().equals(castOther.getCreatedate())))
                && ((this.getMti().equals(castOther.getMti())) || (this.getMti() != null && castOther.getMti() != null && this.getMti().equals(castOther.getMti())))
                && ((this.getF2Sothe().equals(castOther.getF2Sothe())) || (this.getF2Sothe() != null && castOther.getF2Sothe() != null && this.getF2Sothe().equals(castOther.getF2Sothe())))
                && ((this.getF3Maxuly().equals(castOther.getF3Maxuly())) || (this.getF3Maxuly() != null && castOther.getF3Maxuly() != null && this.getF3Maxuly().equals(castOther.getF3Maxuly())))
                && ((this.getF62Svc().equals(castOther.getF62Svc())) || (this.getF62Svc() != null && castOther.getF62Svc() != null && this.getF62Svc().equals(castOther.getF62Svc())))
                && ((this.getF60Tcc().equals(castOther.getF60Tcc())) || (this.getF60Tcc() != null && castOther.getF60Tcc() != null && this.getF60Tcc().equals(castOther.getF60Tcc())))
                && ((this.getF4Sotien().equals(castOther.getF4Sotien())) || (this.getF4Sotien() != null && castOther.getF4Sotien() != null && this.getF4Sotien().equals(castOther.getF4Sotien())))
                && ((this.getF4Rta().equals(castOther.getF4Rta())) || (this.getF4Rta() != null && castOther.getF4Rta() != null && this.getF4Rta().equals(castOther.getF4Rta())))
                && ((this.getF49Ccy().equals(castOther.getF49Ccy())) || (this.getF49Ccy() != null && castOther.getF49Ccy() != null && this.getF49Ccy().equals(castOther.getF49Ccy())))
                && ((this.getF5Stqt().equals(castOther.getF5Stqt())) || (this.getF5Stqt() != null && castOther.getF5Stqt() != null && this.getF5Stqt().equals(castOther.getF5Stqt())))
                && ((this.getF50Ccy().equals(castOther.getF50Ccy())) || (this.getF50Ccy() != null && castOther.getF50Ccy() != null && this.getF50Ccy().equals(castOther.getF50Ccy())))
                && ((this.getF9Tygia().equals(castOther.getF9Tygia())) || (this.getF9Tygia() != null && castOther.getF9Tygia() != null && this.getF9Tygia().equals(castOther.getF9Tygia())))
                && ((this.getF6Stchuthe().equals(castOther.getF6Stchuthe())) || (this.getF6Stchuthe() != null && castOther.getF6Stchuthe() != null && this.getF6Stchuthe().equals(castOther.getF6Stchuthe())))
                && ((this.getF6Thucte().equals(castOther.getF6Thucte())) || (this.getF6Thucte() != null && castOther.getF6Thucte() != null && this.getF6Thucte().equals(castOther.getF6Thucte())))
                && ((this.getF51Ccy().equals(castOther.getF51Ccy())) || (this.getF51Ccy() != null && castOther.getF51Ccy() != null && this.getF51Ccy().equals(castOther.getF51Ccy())))
                && ((this.getF10Tygia().equals(castOther.getF10Tygia())) || (this.getF10Tygia() != null && castOther.getF10Tygia() != null && this.getF10Tygia().equals(castOther.getF10Tygia())))
                && ((this.getF11Trace().equals(castOther.getF11Trace())) || (this.getF11Trace() != null && castOther.getF11Trace() != null && this.getF11Trace().equals(castOther.getF11Trace())))
                && ((this.getF12Giogd().equals(castOther.getF12Giogd())) || (this.getF12Giogd() != null && castOther.getF12Giogd() != null && this.getF12Giogd().equals(castOther.getF12Giogd())))
                && ((this.getF13Ngaygd().equals(castOther.getF13Ngaygd())) || (this.getF13Ngaygd() != null && castOther.getF13Ngaygd() != null && this.getF13Ngaygd().equals(castOther.getF13Ngaygd())))
                && ((this.getF15Ngayqt().equals(castOther.getF15Ngayqt())) || (this.getF15Ngayqt() != null && castOther.getF15Ngayqt() != null && this.getF15Ngayqt().equals(castOther.getF15Ngayqt())))
                && ((this.getF18Mct().equals(castOther.getF18Mct())) || (this.getF18Mct() != null && castOther.getF18Mct() != null && this.getF18Mct().equals(castOther.getF18Mct())))
                && ((this.getAddinfo().equals(castOther.getAddinfo())) || (this.getAddinfo() != null && castOther.getAddinfo() != null && this.getAddinfo().equals(castOther.getAddinfo())))
                && ((this.getF41().equals(castOther.getF41())) || (this.getF41() != null && castOther.getF41() != null && this.getF41().equals(castOther.getF41())))
                && ((this.getAcqIss().equals(castOther.getAcqIss())) || (this.getAcqIss() != null && castOther.getAcqIss() != null && this.getAcqIss().equals(castOther.getAcqIss())))
                && ((this.getMid().equals(castOther.getMid())) || (this.getMid() != null && castOther.getMid() != null && this.getMid().equals(castOther.getMid())))
                && ((this.getBnb().equals(castOther.getBnb())) || (this.getBnb() != null && castOther.getBnb() != null && this.getBnb().equals(castOther.getBnb())))
                && ((this.getF102().equals(castOther.getF102())) || (this.getF102() != null && castOther.getF102() != null && this.getF102().equals(castOther.getF102())))
                && ((this.getF103Thedich().equals(castOther.getF103Thedich())) || (this.getF103Thedich() != null && castOther.getF103Thedich() != null && this.getF103Thedich().equals(castOther.getF103Thedich())))
                && ((this.getAddinfoFee().equals(castOther.getAddinfoFee())) || (this.getAddinfoFee() != null && castOther.getAddinfoFee() != null && this.getAddinfoFee().equals(castOther.getAddinfoFee())))
                && ((this.getF37().equals(castOther.getF37())) || (this.getF37() != null && castOther.getF37() != null && this.getF37().equals(castOther.getF37())))
                && ((this.getF38().equals(castOther.getF38())) || (this.getF38() != null && castOther.getF38() != null && this.getF38().equals(castOther.getF38())))
                && ((this.getTrn().equals(castOther.getTrn())) || (this.getTrn() != null && castOther.getTrn() != null && this.getTrn().equals(castOther.getTrn())))
                && ((this.getRrc().equals(castOther.getRrc())) || (this.getRrc() != null && castOther.getRrc() != null && this.getRrc().equals(castOther.getRrc())))
                && ((this.getRcv1().equals(castOther.getRcv1())) || (this.getRcv1() != null && castOther.getRcv1() != null && this.getRcv1().equals(castOther.getRcv1())))
                && ((this.getRcv2().equals(castOther.getRcv2())) || (this.getRcv2() != null && castOther.getRcv2() != null && this.getRcv2().equals(castOther.getRcv2())))
                && ((this.getRcv3().equals(castOther.getRcv3())) || (this.getRcv3() != null && castOther.getRcv3() != null && this.getRcv3().equals(castOther.getRcv3())))
                && ((this.getRrcFinal().equals(castOther.getRrcFinal())) || (this.getRrcFinal() != null && castOther.getRrcFinal() != null && this.getRrcFinal().equals(castOther.getRrcFinal())))
                && ((this.getDateFinal().equals(castOther.getDateFinal())) || (this.getDateFinal() != null && castOther.getDateFinal() != null && this.getDateFinal().equals(castOther.getDateFinal())));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
        result = 37 * result + (getFiletype() == null ? 0 : this.getFiletype().hashCode());
        result = 37 * result + (getTranstype() == null ? 0 : this.getTranstype().hashCode());
        result = 37 * result + (getService() == null ? 0 : this.getService().hashCode());
        result = 37 * result + (getCreatedate() == null ? 0 : this.getCreatedate().hashCode());
        result = 37 * result + (getMti() == null ? 0 : this.getMti().hashCode());
        result = 37 * result + (getF2Sothe() == null ? 0 : this.getF2Sothe().hashCode());
        result = 37 * result + (getF3Maxuly() == null ? 0 : this.getF3Maxuly().hashCode());
        result = 37 * result + (getF62Svc() == null ? 0 : this.getF62Svc().hashCode());
        result = 37 * result + (getF60Tcc() == null ? 0 : this.getF60Tcc().hashCode());
        result = 37 * result + (getF4Sotien() == null ? 0 : this.getF4Sotien().hashCode());
        result = 37 * result + (getF4Rta() == null ? 0 : this.getF4Rta().hashCode());
        result = 37 * result + (getF49Ccy() == null ? 0 : this.getF49Ccy().hashCode());
        result = 37 * result + (getF5Stqt() == null ? 0 : this.getF5Stqt().hashCode());
        result = 37 * result + (getF50Ccy() == null ? 0 : this.getF50Ccy().hashCode());
        result = 37 * result + (getF9Tygia() == null ? 0 : this.getF9Tygia().hashCode());
        result = 37 * result + (getF6Stchuthe() == null ? 0 : this.getF6Stchuthe().hashCode());
        result = 37 * result + (getF6Thucte() == null ? 0 : this.getF6Thucte().hashCode());
        result = 37 * result + (getF51Ccy() == null ? 0 : this.getF51Ccy().hashCode());
        result = 37 * result + (getF10Tygia() == null ? 0 : this.getF10Tygia().hashCode());
        result = 37 * result + (getF11Trace() == null ? 0 : this.getF11Trace().hashCode());
        result = 37 * result + (getF12Giogd() == null ? 0 : this.getF12Giogd().hashCode());
        result = 37 * result + (getF13Ngaygd() == null ? 0 : this.getF13Ngaygd().hashCode());
        result = 37 * result + (getF15Ngayqt() == null ? 0 : this.getF15Ngayqt().hashCode());
        result = 37 * result + (getF18Mct() == null ? 0 : this.getF18Mct().hashCode());
        result = 37 * result + (getAddinfo() == null ? 0 : this.getAddinfo().hashCode());
        result = 37 * result + (getF41() == null ? 0 : this.getF41().hashCode());
        result = 37 * result + (getAcqIss() == null ? 0 : this.getAcqIss().hashCode());
        result = 37 * result + (getMid() == null ? 0 : this.getMid().hashCode());
        result = 37 * result + (getBnb() == null ? 0 : this.getBnb().hashCode());
        result = 37 * result + (getF102() == null ? 0 : this.getF102().hashCode());
        result = 37 * result + (getF103Thedich() == null ? 0 : this.getF103Thedich().hashCode());
        result = 37 * result + (getAddinfoFee() == null ? 0 : this.getAddinfoFee().hashCode());
        result = 37 * result + (getF37() == null ? 0 : this.getF37().hashCode());
        result = 37 * result + (getF38() == null ? 0 : this.getF38().hashCode());
        result = 37 * result + (getTrn() == null ? 0 : this.getTrn().hashCode());
        result = 37 * result + (getRrc() == null ? 0 : this.getRrc().hashCode());
        result = 37 * result + (getRcv1() == null ? 0 : this.getRcv1().hashCode());
        result = 37 * result + (getRcv2() == null ? 0 : this.getRcv2().hashCode());
        result = 37 * result + (getRcv3() == null ? 0 : this.getRcv3().hashCode());
        result = 37 * result + (getRrcFinal() == null ? 0 : this.getRrcFinal().hashCode());
        result = 37 * result + (getDateFinal() == null ? 0 : this.getDateFinal().hashCode());
        return result;
    }

}
