package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * PblAutoRegHistory generated by hbm2java
 */
public class PblAutoRegHistory implements java.io.Serializable {

    private int idlog;
    private String idcontract;
    private String custAccCif;
    private String custAccNo;
    private String custAccName;
    private String custAccAddress;
    private String custAccIdcard;
    private String custAccIdcardLoc;
    private String custAccIdcardDob;
    private char havesms;
    private String mobile;
    private char active;
    private Date datcreated;
    private String makerid;
    private String branchcode;
    private String checkerid;
    private Date datautheq;
    private String makeridModify;
    private String makeridModifyBrncode;
    private Date makeridModifyDatcreated;
    private String checkeridModify;
    private Date checkeridModifyDatcreate;
    private Date lastsendsms;
    private String idservicetype;
    private String idprovider;
    private String customercode;
    private char status;
    private Date validdate;
    private Date expiredate;
    private boolean scheduletype;
    private String daysinmonth;
    private Character isapproved;

    /**
     * Create a new instance of PblAutoRegHistory
     */
    public PblAutoRegHistory() {
    }

    /**
     *
     * @param idlog
     * @param idcontract
     * @param custAccCif
     * @param custAccNo
     * @param custAccName
     * @param havesms
     * @param active
     * @param datcreated
     * @param idservicetype
     * @param idprovider
     * @param customercode
     * @param status
     * @param validdate
     * @param scheduletype
     */
    public PblAutoRegHistory(int idlog, String idcontract, String custAccCif, String custAccNo, String custAccName, char havesms, char active, Date datcreated, String idservicetype, String idprovider, String customercode, char status, Date validdate, boolean scheduletype) {
        this.idlog = idlog;
        this.idcontract = idcontract;
        this.custAccCif = custAccCif;
        this.custAccNo = custAccNo;
        this.custAccName = custAccName;
        this.havesms = havesms;
        this.active = active;
        this.datcreated = datcreated;
        this.idservicetype = idservicetype;
        this.idprovider = idprovider;
        this.customercode = customercode;
        this.status = status;
        this.validdate = validdate;
        this.scheduletype = scheduletype;
    }

    /**
     *
     * @param idlog
     * @param idcontract
     * @param custAccCif
     * @param custAccNo
     * @param custAccName
     * @param custAccAddress
     * @param custAccIdcard
     * @param custAccIdcardLoc
     * @param custAccIdcardDob
     * @param havesms
     * @param mobile
     * @param active
     * @param datcreated
     * @param makerid
     * @param branchcode
     * @param checkerid
     * @param datautheq
     * @param makeridModify
     * @param makeridModifyBrncode
     * @param makeridModifyDatcreated
     * @param checkeridModify
     * @param checkeridModifyDatcreate
     * @param lastsendsms
     * @param idservicetype
     * @param idprovider
     * @param customercode
     * @param status
     * @param validdate
     * @param expiredate
     * @param scheduletype
     * @param daysinmonth
     * @param isapproved
     */
    public PblAutoRegHistory(int idlog, String idcontract, String custAccCif, String custAccNo, String custAccName, String custAccAddress, String custAccIdcard, String custAccIdcardLoc, String custAccIdcardDob, char havesms, String mobile, char active, Date datcreated, String makerid, String branchcode, String checkerid, Date datautheq, String makeridModify, String makeridModifyBrncode, Date makeridModifyDatcreated, String checkeridModify, Date checkeridModifyDatcreate, Date lastsendsms, String idservicetype, String idprovider, String customercode, char status, Date validdate, Date expiredate, boolean scheduletype, String daysinmonth, Character isapproved) {
        this.idlog = idlog;
        this.idcontract = idcontract;
        this.custAccCif = custAccCif;
        this.custAccNo = custAccNo;
        this.custAccName = custAccName;
        this.custAccAddress = custAccAddress;
        this.custAccIdcard = custAccIdcard;
        this.custAccIdcardLoc = custAccIdcardLoc;
        this.custAccIdcardDob = custAccIdcardDob;
        this.havesms = havesms;
        this.mobile = mobile;
        this.active = active;
        this.datcreated = datcreated;
        this.makerid = makerid;
        this.branchcode = branchcode;
        this.checkerid = checkerid;
        this.datautheq = datautheq;
        this.makeridModify = makeridModify;
        this.makeridModifyBrncode = makeridModifyBrncode;
        this.makeridModifyDatcreated = makeridModifyDatcreated;
        this.checkeridModify = checkeridModify;
        this.checkeridModifyDatcreate = checkeridModifyDatcreate;
        this.lastsendsms = lastsendsms;
        this.idservicetype = idservicetype;
        this.idprovider = idprovider;
        this.customercode = customercode;
        this.status = status;
        this.validdate = validdate;
        this.expiredate = expiredate;
        this.scheduletype = scheduletype;
        this.daysinmonth = daysinmonth;
        this.isapproved = isapproved;
    }

    /**
     *
     * @return
     */
    public int getIdlog() {
        return this.idlog;
    }

    /**
     *
     * @param idlog
     */
    public void setIdlog(int idlog) {
        this.idlog = idlog;
    }

    /**
     *
     * @return
     */
    public String getIdcontract() {
        return this.idcontract;
    }

    /**
     *
     * @param idcontract
     */
    public void setIdcontract(String idcontract) {
        this.idcontract = idcontract;
    }

    /**
     *
     * @return
     */
    public String getCustAccCif() {
        return this.custAccCif;
    }

    /**
     *
     * @param custAccCif
     */
    public void setCustAccCif(String custAccCif) {
        this.custAccCif = custAccCif;
    }

    /**
     *
     * @return
     */
    public String getCustAccNo() {
        return this.custAccNo;
    }

    /**
     *
     * @param custAccNo
     */
    public void setCustAccNo(String custAccNo) {
        this.custAccNo = custAccNo;
    }

    /**
     *
     * @return
     */
    public String getCustAccName() {
        return this.custAccName;
    }

    /**
     *
     * @param custAccName
     */
    public void setCustAccName(String custAccName) {
        this.custAccName = custAccName;
    }

    /**
     *
     * @return
     */
    public String getCustAccAddress() {
        return this.custAccAddress;
    }

    /**
     *
     * @param custAccAddress
     */
    public void setCustAccAddress(String custAccAddress) {
        this.custAccAddress = custAccAddress;
    }

    /**
     *
     * @return
     */
    public String getCustAccIdcard() {
        return this.custAccIdcard;
    }

    /**
     *
     * @param custAccIdcard
     */
    public void setCustAccIdcard(String custAccIdcard) {
        this.custAccIdcard = custAccIdcard;
    }

    /**
     *
     * @return
     */
    public String getCustAccIdcardLoc() {
        return this.custAccIdcardLoc;
    }

    /**
     *
     * @param custAccIdcardLoc
     */
    public void setCustAccIdcardLoc(String custAccIdcardLoc) {
        this.custAccIdcardLoc = custAccIdcardLoc;
    }

    /**
     *
     * @return
     */
    public String getCustAccIdcardDob() {
        return this.custAccIdcardDob;
    }

    /**
     *
     * @param custAccIdcardDob
     */
    public void setCustAccIdcardDob(String custAccIdcardDob) {
        this.custAccIdcardDob = custAccIdcardDob;
    }

    /**
     *
     * @return
     */
    public char getHavesms() {
        return this.havesms;
    }

    /**
     *
     * @param havesms
     */
    public void setHavesms(char havesms) {
        this.havesms = havesms;
    }

    /**
     *
     * @return
     */
    public String getMobile() {
        return this.mobile;
    }

    /**
     *
     * @param mobile
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     *
     * @return
     */
    public char getActive() {
        return this.active;
    }

    /**
     *
     * @param active
     */
    public void setActive(char active) {
        this.active = active;
    }

    /**
     *
     * @return
     */
    public Date getDatcreated() {
        return this.datcreated;
    }

    /**
     *
     * @param datcreated
     */
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    /**
     *
     * @return
     */
    public String getMakerid() {
        return this.makerid;
    }

    /**
     *
     * @param makerid
     */
    public void setMakerid(String makerid) {
        this.makerid = makerid;
    }

    /**
     *
     * @return
     */
    public String getBranchcode() {
        return this.branchcode;
    }

    /**
     *
     * @param branchcode
     */
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }

    /**
     *
     * @return
     */
    public String getCheckerid() {
        return this.checkerid;
    }

    /**
     *
     * @param checkerid
     */
    public void setCheckerid(String checkerid) {
        this.checkerid = checkerid;
    }

    /**
     *
     * @return
     */
    public Date getDatautheq() {
        return this.datautheq;
    }

    /**
     *
     * @param datautheq
     */
    public void setDatautheq(Date datautheq) {
        this.datautheq = datautheq;
    }

    /**
     *
     * @return
     */
    public String getMakeridModify() {
        return this.makeridModify;
    }

    /**
     *
     * @param makeridModify
     */
    public void setMakeridModify(String makeridModify) {
        this.makeridModify = makeridModify;
    }

    /**
     *
     * @return
     */
    public String getMakeridModifyBrncode() {
        return this.makeridModifyBrncode;
    }

    /**
     *
     * @param makeridModifyBrncode
     */
    public void setMakeridModifyBrncode(String makeridModifyBrncode) {
        this.makeridModifyBrncode = makeridModifyBrncode;
    }

    /**
     *
     * @return
     */
    public Date getMakeridModifyDatcreated() {
        return this.makeridModifyDatcreated;
    }

    /**
     *
     * @param makeridModifyDatcreated
     */
    public void setMakeridModifyDatcreated(Date makeridModifyDatcreated) {
        this.makeridModifyDatcreated = makeridModifyDatcreated;
    }

    /**
     *
     * @return
     */
    public String getCheckeridModify() {
        return this.checkeridModify;
    }

    /**
     *
     * @param checkeridModify
     */
    public void setCheckeridModify(String checkeridModify) {
        this.checkeridModify = checkeridModify;
    }

    /**
     *
     * @return
     */
    public Date getCheckeridModifyDatcreate() {
        return this.checkeridModifyDatcreate;
    }

    /**
     *
     * @param checkeridModifyDatcreate
     */
    public void setCheckeridModifyDatcreate(Date checkeridModifyDatcreate) {
        this.checkeridModifyDatcreate = checkeridModifyDatcreate;
    }

    /**
     *
     * @return
     */
    public Date getLastsendsms() {
        return this.lastsendsms;
    }

    /**
     *
     * @param lastsendsms
     */
    public void setLastsendsms(Date lastsendsms) {
        this.lastsendsms = lastsendsms;
    }

    /**
     *
     * @return
     */
    public String getIdservicetype() {
        return this.idservicetype;
    }

    /**
     *
     * @param idservicetype
     */
    public void setIdservicetype(String idservicetype) {
        this.idservicetype = idservicetype;
    }

    /**
     *
     * @return
     */
    public String getIdprovider() {
        return this.idprovider;
    }

    /**
     *
     * @param idprovider
     */
    public void setIdprovider(String idprovider) {
        this.idprovider = idprovider;
    }

    /**
     *
     * @return
     */
    public String getCustomercode() {
        return this.customercode;
    }

    /**
     *
     * @param customercode
     */
    public void setCustomercode(String customercode) {
        this.customercode = customercode;
    }

    /**
     *
     * @return
     */
    public char getStatus() {
        return this.status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(char status) {
        this.status = status;
    }

    /**
     *
     * @return
     */
    public Date getValiddate() {
        return this.validdate;
    }

    /**
     *
     * @param validdate
     */
    public void setValiddate(Date validdate) {
        this.validdate = validdate;
    }

    /**
     *
     * @return
     */
    public Date getExpiredate() {
        return this.expiredate;
    }

    /**
     *
     * @param expiredate
     */
    public void setExpiredate(Date expiredate) {
        this.expiredate = expiredate;
    }

    /**
     *
     * @return
     */
    public boolean isScheduletype() {
        return this.scheduletype;
    }

    /**
     *
     * @param scheduletype
     */
    public void setScheduletype(boolean scheduletype) {
        this.scheduletype = scheduletype;
    }

    /**
     *
     * @return
     */
    public String getDaysinmonth() {
        return this.daysinmonth;
    }

    /**
     *
     * @param daysinmonth
     */
    public void setDaysinmonth(String daysinmonth) {
        this.daysinmonth = daysinmonth;
    }

    /**
     *
     * @return
     */
    public Character getIsapproved() {
        return this.isapproved;
    }

    /**
     *
     * @param isapproved
     */
    public void setIsapproved(Character isapproved) {
        this.isapproved = isapproved;
    }

}
