package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * PblAutoReg generated by hbm2java
 */
public class PblAutoReg implements java.io.Serializable {

    private int id;
    private PblAutoRegContract pblAutoRegContract;
    private PblServicetype pblServicetype;
    private PblProvider pblProvider;
    private String customercode;
    private Character status;
    private Date validdate;
    private Date expiredate;
    private boolean scheduletype;
    private String daysinmonth;
    private Character paymenttype;
    /**
     * Create a new instance of PblAutoReg
     */
    public PblAutoReg() {
    }

    /**
     *
     * @param id
     * @param pblAutoRegContract
     * @param pblServicetype
     * @param pblProvider
     * @param customercode
     * @param status
     * @param validdate
     * @param scheduletype
     */
    public PblAutoReg(int id, PblAutoRegContract pblAutoRegContract, PblServicetype pblServicetype, PblProvider pblProvider, String customercode, char status, Date validdate, boolean scheduletype) {
        this.id = id;
        this.pblAutoRegContract = pblAutoRegContract;
        this.pblServicetype = pblServicetype;
        this.pblProvider = pblProvider;
        this.customercode = customercode;
        this.status = status;
        this.validdate = validdate;
        this.scheduletype = scheduletype;
    }

    /**
     *
     * @param id
     * @param pblAutoRegContract
     * @param pblServicetype
     * @param pblProvider
     * @param customercode
     * @param status
     * @param validdate
     * @param expiredate
     * @param scheduletype
     * @param daysinmonth
     */
    public PblAutoReg(int id, PblAutoRegContract pblAutoRegContract, PblServicetype pblServicetype, PblProvider pblProvider, String customercode, char status, Date validdate, Date expiredate, boolean scheduletype, String daysinmonth) {
        this.id = id;
        this.pblAutoRegContract = pblAutoRegContract;
        this.pblServicetype = pblServicetype;
        this.pblProvider = pblProvider;
        this.customercode = customercode;
        this.status = status;
        this.validdate = validdate;
        this.expiredate = expiredate;
        this.scheduletype = scheduletype;
        this.daysinmonth = daysinmonth;
    }

    public PblAutoReg(int id, PblAutoRegContract pblAutoRegContract, PblServicetype pblServicetype, PblProvider pblProvider, String customercode, char status, Date validdate, Date expiredate, boolean scheduletype, String daysinmonth, Character paymenttype) {
        this.id = id;
        this.pblAutoRegContract = pblAutoRegContract;
        this.pblServicetype = pblServicetype;
        this.pblProvider = pblProvider;
        this.customercode = customercode;
        this.status = status;
        this.validdate = validdate;
        this.expiredate = expiredate;
        this.scheduletype = scheduletype;
        this.daysinmonth = daysinmonth;
        this.paymenttype = paymenttype;
    }
    
    /**
     *
     * @return
     */
    public int getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public PblAutoRegContract getPblAutoRegContract() {
        return this.pblAutoRegContract;
    }

    /**
     *
     * @param pblAutoRegContract
     */
    public void setPblAutoRegContract(PblAutoRegContract pblAutoRegContract) {
        this.pblAutoRegContract = pblAutoRegContract;
    }

    /**
     *
     * @return
     */
    public PblServicetype getPblServicetype() {
        return this.pblServicetype;
    }

    /**
     *
     * @param pblServicetype
     */
    public void setPblServicetype(PblServicetype pblServicetype) {
        this.pblServicetype = pblServicetype;
    }

    /**
     *
     * @return
     */
    public PblProvider getPblProvider() {
        return this.pblProvider;
    }

    /**
     *
     * @param pblProvider
     */
    public void setPblProvider(PblProvider pblProvider) {
        this.pblProvider = pblProvider;
    }

    /**
     *
     * @return
     */
    public String getCustomercode() {
        return this.customercode;
    }

    /**
     *
     * @param customercode
     */
    public void setCustomercode(String customercode) {
        this.customercode = customercode;
    }

    /**
     *
     * @return
     */
    public Character getStatus() {
        return this.status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(Character status) {
        this.status = status;
    }

    /**
     *
     * @return
     */
    public Date getValiddate() {
        return this.validdate;
    }

    /**
     *
     * @param validdate
     */
    public void setValiddate(Date validdate) {
        this.validdate = validdate;
    }

    /**
     *
     * @return
     */
    public Date getExpiredate() {
        return this.expiredate;
    }

    /**
     *
     * @param expiredate
     */
    public void setExpiredate(Date expiredate) {
        this.expiredate = expiredate;
    }

    /**
     *
     * @return
     */
    public boolean isScheduletype() {
        return this.scheduletype;
    }

    /**
     *
     * @param scheduletype
     */
    public void setScheduletype(boolean scheduletype) {
        this.scheduletype = scheduletype;
    }

    /**
     *
     * @return
     */
    public String getDaysinmonth() {
        return this.daysinmonth;
    }

    /**
     *
     * @param daysinmonth
     */
    public void setDaysinmonth(String daysinmonth) {
        this.daysinmonth = daysinmonth;
    }
    
     public Character getPaymenttype() {
        return paymenttype;
    }

    public void setPaymenttype(Character paymenttype) {
        this.paymenttype = paymenttype;
    }
    
}
