package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * PblAutoregFail generated by hbm2java
 */
public class PblAutoregFail implements java.io.Serializable {

    private PblAutoregFailId id;
    private int numattempFail;
    private int limitNumFail;
    private Date dateFail;
    private Character sentsms;

    /**
     * Create a new instance of PblAutoregFail
     */
    public PblAutoregFail() {
    }

    /**
     *
     * @param id
     */
    public PblAutoregFail(PblAutoregFailId id) {
        this.id = id;
    }

    /**
     *
     * @param id
     * @param numattempFail
     * @param limitNumFail
     * @param dateFail
     * @param sentsms
     */
    public PblAutoregFail(PblAutoregFailId id, int numattempFail, int limitNumFail, Date dateFail, Character sentsms) {
        this.id = id;
        this.numattempFail = numattempFail;
        this.limitNumFail = limitNumFail;
        this.dateFail = dateFail;
        this.sentsms = sentsms;
    }

    /**
     *
     * @return
     */
    public PblAutoregFailId getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(PblAutoregFailId id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public int getNumattempFail() {
        return this.numattempFail;
    }

    /**
     *
     * @param numattempFail
     */
    public void setNumattempFail(int numattempFail) {
        this.numattempFail = numattempFail;
    }

    /**
     *
     * @return
     */
    public int getLimitNumFail() {
        return this.limitNumFail;
    }

    /**
     *
     * @param limitNumFail
     */
    public void setLimitNumFail(int limitNumFail) {
        this.limitNumFail = limitNumFail;
    }

    /**
     *
     * @return
     */
    public Date getDateFail() {
        return this.dateFail;
    }

    /**
     *
     * @param dateFail
     */
    public void setDateFail(Date dateFail) {
        this.dateFail = dateFail;
    }

    /**
     *
     * @return
     */
    public Character getSentsms() {
        return this.sentsms;
    }

    /**
     *
     * @param sentsms
     */
    public void setSentsms(Character sentsms) {
        this.sentsms = sentsms;
    }
}
