package scb.com.vn.dbi.dto;

/**
 * PblAutoregFailId generated by hbm2java
 */
public class PblAutoregFailId implements java.io.Serializable {

    private String idcontract;
    private String custAccNo;
    private String idservicetype;
    private String idprovider;
    private String customercode;

    /**
     * Create a new instance of PblAutoregFailId
     */
    public PblAutoregFailId() {
    }

    /**
     *
     * @param idcontract
     * @param custAccNo
     * @param idservicetype
     * @param idprovider
     * @param customercode
     */
    public PblAutoregFailId(String idcontract, String custAccNo, String idservicetype, String idprovider, String customercode) {
        this.idcontract = idcontract;
        this.custAccNo = custAccNo;
        this.idservicetype = idservicetype;
        this.idprovider = idprovider;
        this.customercode = customercode;
    }

    /**
     *
     * @return
     */
    public String getIdcontract() {
        return this.idcontract;
    }

    /**
     *
     * @param idcontract
     */
    public void setIdcontract(String idcontract) {
        this.idcontract = idcontract;
    }

    /**
     *
     * @return
     */
    public String getCustAccNo() {
        return this.custAccNo;
    }

    /**
     *
     * @param custAccNo
     */
    public void setCustAccNo(String custAccNo) {
        this.custAccNo = custAccNo;
    }

    /**
     *
     * @return
     */
    public String getIdservicetype() {
        return this.idservicetype;
    }

    /**
     *
     * @param idservicetype
     */
    public void setIdservicetype(String idservicetype) {
        this.idservicetype = idservicetype;
    }

    /**
     *
     * @return
     */
    public String getIdprovider() {
        return this.idprovider;
    }

    /**
     *
     * @param idprovider
     */
    public void setIdprovider(String idprovider) {
        this.idprovider = idprovider;
    }

    /**
     *
     * @return
     */
    public String getCustomercode() {
        return this.customercode;
    }

    /**
     *
     * @param customercode
     */
    public void setCustomercode(String customercode) {
        this.customercode = customercode;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof PblAutoregFailId)) {
            return false;
        }
        PblAutoregFailId castOther = (PblAutoregFailId) other;

        return ((this.getIdcontract().equals(castOther.getIdcontract())) || (this.getIdcontract() != null && castOther.getIdcontract() != null && this.getIdcontract().equals(castOther.getIdcontract())))
                && ((this.getCustAccNo().equals(castOther.getCustAccNo())) || (this.getCustAccNo() != null && castOther.getCustAccNo() != null && this.getCustAccNo().equals(castOther.getCustAccNo())));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getIdcontract() == null ? 0 : this.getIdcontract().hashCode());
        result = 37 * result + (getCustAccNo() == null ? 0 : this.getCustAccNo().hashCode());
        return result;
    }
}
