package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * PblBillpaid generated by hbm2java
 */
public class PblBillpaid implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
    private int idbillpaid;
    private PblServicetype pblServicetype;
    private PblProvider pblProvider;
    private String idpartner;
    private String customercode;
    private String dataxml;
    private String iduserMaker;
    private String idchanneluserMaker;
    private Date insdateMaker;
    private String iduserChecker;
    private String idchanneluserChecker;
    private Date insdateChecker;
    private String idchannel;
    private String usertype;
    private String refPartner;
    private String refFcubs;
    private Long totalamount;
    private Integer paymentmethod;
    private String accCust;
    private String accIdaccount;
    private String accHoldername;
    private String accAddress;
    private Date insdate;
    private Date transdate;
    private Date paydate;
    private Date paydateFcubs;
    private Character isapproved;
    private Character status;
    private String branchcode;
    private String IdentityCard;
    private String DateOfIssue;
    private String PlaceOfIssue;
    private String PhoneNumber;
    private String responseCode;
    private String refFcubsRevert;

    /**
     *
     * @return
     */
    public String getIdentityCard() {
        return IdentityCard;
    }

    /**
     *
     * @param IdentityCard
     */
    public void setIdentityCard(String IdentityCard) {
        this.IdentityCard = IdentityCard;
    }

    /**
     *
     * @return
     */
    public String getDateOfIssue() {
        return DateOfIssue;
    }

    /**
     *
     * @param DateOfIssue
     */
    public void setDateOfIssue(String DateOfIssue) {
        this.DateOfIssue = DateOfIssue;
    }

    /**
     *
     * @return
     */
    public String getPlaceOfIssue() {
        return PlaceOfIssue;
    }

    /**
     *
     * @param PlaceOfIssue
     */
    public void setPlaceOfIssue(String PlaceOfIssue) {
        this.PlaceOfIssue = PlaceOfIssue;
    }

    /**
     *
     * @return
     */
    public String getPhoneNumber() {
        return PhoneNumber;
    }

    /**
     *
     * @param PhoneNumber
     */
    public void setPhoneNumber(String PhoneNumber) {
        this.PhoneNumber = PhoneNumber;
    }

    /**
     *
     * @return
     */
    public Character getStatus() {
        return status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(Character status) {
        this.status = status;
    }

    /**
     * Create a new instance of PblBillpaid
     */
    public PblBillpaid() {
    }

    /**
     *
     * @param idbillpaid
     * @param pblServicetype
     * @param pblProvider
     * @param customercode
     */
    public PblBillpaid(int idbillpaid, PblServicetype pblServicetype, PblProvider pblProvider, String customercode) {
        this.idbillpaid = idbillpaid;
        this.pblServicetype = pblServicetype;
        this.pblProvider = pblProvider;
        this.customercode = customercode;
    }

    /**
     *
     * @param idbillpaid
     * @param pblServicetype
     * @param pblProvider
     * @param idpartner
     * @param customercode
     * @param dataxml
     * @param iduserMaker
     * @param idchanneluserMaker
     * @param insdateMaker
     * @param iduserChecker
     * @param idchanneluserChecker
     * @param insdateChecker
     * @param idchannel
     * @param usertype
     * @param refPartner
     * @param refFcubs
     * @param totalamount
     * @param paymentmethod
     * @param accCust
     * @param accIdaccount
     * @param accHoldername
     * @param accAddress
     * @param insdate
     * @param transdate
     * @param paydate
     * @param paydateFcubs
     * @param isapproved
     * @param status
     */
    public PblBillpaid(int idbillpaid, PblServicetype pblServicetype, PblProvider pblProvider, String idpartner, String customercode, String dataxml, String iduserMaker, String idchanneluserMaker, Date insdateMaker, String iduserChecker, String idchanneluserChecker, Date insdateChecker, String idchannel, String usertype, String refPartner, String refFcubs, Long totalamount, Integer paymentmethod, String accCust, String accIdaccount, String accHoldername, String accAddress, Date insdate, Date transdate, Date paydate, Date paydateFcubs, Character isapproved, Character status) {
        this.idbillpaid = idbillpaid;
        this.pblServicetype = pblServicetype;
        this.pblProvider = pblProvider;
        this.idpartner = idpartner;
        this.customercode = customercode;
        this.dataxml = dataxml;
        this.iduserMaker = iduserMaker;
        this.idchanneluserMaker = idchanneluserMaker;
        this.insdateMaker = insdateMaker;
        this.iduserChecker = iduserChecker;
        this.idchanneluserChecker = idchanneluserChecker;
        this.insdateChecker = insdateChecker;
        this.idchannel = idchannel;
        this.usertype = usertype;
        this.refPartner = refPartner;
        this.refFcubs = refFcubs;
        this.totalamount = totalamount;
        this.paymentmethod = paymentmethod;
        this.accCust = accCust;
        this.accIdaccount = accIdaccount;
        this.accHoldername = accHoldername;
        this.accAddress = accAddress;
        this.insdate = insdate;
        this.transdate = transdate;
        this.paydate = paydate;
        this.paydateFcubs = paydateFcubs;
        this.isapproved = isapproved;
        this.status = status;
    }

    /**
     *
     * @return
     */
    public int getIdbillpaid() {
        return this.idbillpaid;
    }

    /**
     *
     * @param idbillpaid
     */
    public void setIdbillpaid(int idbillpaid) {
        this.idbillpaid = idbillpaid;
    }

    /**
     *
     * @return
     */
    public PblServicetype getPblServicetype() {
        return this.pblServicetype;
    }

    /**
     *
     * @param pblServicetype
     */
    public void setPblServicetype(PblServicetype pblServicetype) {
        this.pblServicetype = pblServicetype;
    }

    /**
     *
     * @return
     */
    public PblProvider getPblProvider() {
        return this.pblProvider;
    }

    /**
     *
     * @param pblProvider
     */
    public void setPblProvider(PblProvider pblProvider) {
        this.pblProvider = pblProvider;
    }

    /**
     *
     * @return
     */
    public String getIdpartner() {
        return this.idpartner;
    }

    /**
     *
     * @param idpartner
     */
    public void setIdpartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @return
     */
    public String getCustomercode() {
        return this.customercode;
    }

    /**
     *
     * @param customercode
     */
    public void setCustomercode(String customercode) {
        this.customercode = customercode;
    }

    /**
     *
     * @return
     */
    public String getDataxml() {
        return this.dataxml;
    }

    /**
     *
     * @param dataxml
     */
    public void setDataxml(String dataxml) {
        this.dataxml = dataxml;
    }

    /**
     *
     * @return
     */
    public String getIduserMaker() {
        return this.iduserMaker;
    }

    /**
     *
     * @param iduserMaker
     */
    public void setIduserMaker(String iduserMaker) {
        this.iduserMaker = iduserMaker;
    }

    /**
     *
     * @return
     */
    public String getIdchanneluserMaker() {
        return this.idchanneluserMaker;
    }

    /**
     *
     * @param idchanneluserMaker
     */
    public void setIdchanneluserMaker(String idchanneluserMaker) {
        this.idchanneluserMaker = idchanneluserMaker;
    }

    /**
     *
     * @return
     */
    public Date getInsdateMaker() {
        return this.insdateMaker;
    }

    /**
     *
     * @param insdateMaker
     */
    public void setInsdateMaker(Date insdateMaker) {
        this.insdateMaker = insdateMaker;
    }

    /**
     *
     * @return
     */
    public String getIduserChecker() {
        return this.iduserChecker;
    }

    /**
     *
     * @param iduserChecker
     */
    public void setIduserChecker(String iduserChecker) {
        this.iduserChecker = iduserChecker;
    }

    /**
     *
     * @return
     */
    public String getIdchanneluserChecker() {
        return this.idchanneluserChecker;
    }

    /**
     *
     * @param idchanneluserChecker
     */
    public void setIdchanneluserChecker(String idchanneluserChecker) {
        this.idchanneluserChecker = idchanneluserChecker;
    }

    /**
     *
     * @return
     */
    public Date getInsdateChecker() {
        return this.insdateChecker;
    }

    /**
     *
     * @param insdateChecker
     */
    public void setInsdateChecker(Date insdateChecker) {
        this.insdateChecker = insdateChecker;
    }

    /**
     *
     * @return
     */
    public String getIdchannel() {
        return this.idchannel;
    }

    /**
     *
     * @param idchannel
     */
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    /**
     *
     * @return
     */
    public String getUsertype() {
        return this.usertype;
    }

    /**
     *
     * @param usertype
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    /**
     *
     * @return
     */
    public String getRefPartner() {
        return this.refPartner;
    }

    /**
     *
     * @param refPartner
     */
    public void setRefPartner(String refPartner) {
        this.refPartner = refPartner;
    }

    /**
     *
     * @return
     */
    public String getRefFcubs() {
        return this.refFcubs;
    }

    /**
     *
     * @param refFcubs
     */
    public void setRefFcubs(String refFcubs) {
        this.refFcubs = refFcubs;
    }

    /**
     *
     * @return
     */
    public Long getTotalamount() {
        return this.totalamount;
    }

    /**
     *
     * @param totalamount
     */
    public void setTotalamount(Long totalamount) {
        this.totalamount = totalamount;
    }

    /**
     *
     * @return
     */
    public Integer getPaymentmethod() {
        return this.paymentmethod;
    }

    /**
     *
     * @param paymentmethod
     */
    public void setPaymentmethod(Integer paymentmethod) {
        this.paymentmethod = paymentmethod;
    }

    /**
     *
     * @return
     */
    public String getAccCust() {
        return this.accCust;
    }

    /**
     *
     * @param accCust
     */
    public void setAccCust(String accCust) {
        this.accCust = accCust;
    }

    /**
     *
     * @return
     */
    public String getAccIdaccount() {
        return this.accIdaccount;
    }

    /**
     *
     * @param accIdaccount
     */
    public void setAccIdaccount(String accIdaccount) {
        this.accIdaccount = accIdaccount;
    }

    /**
     *
     * @return
     */
    public String getAccHoldername() {
        return this.accHoldername;
    }

    /**
     *
     * @param accHoldername
     */
    public void setAccHoldername(String accHoldername) {
        this.accHoldername = accHoldername;
    }

    /**
     *
     * @return
     */
    public String getAccAddress() {
        return this.accAddress;
    }

    /**
     *
     * @param accAddress
     */
    public void setAccAddress(String accAddress) {
        this.accAddress = accAddress;
    }

    /**
     *
     * @return
     */
    public Date getInsdate() {
        return this.insdate;
    }

    /**
     *
     * @param insdate
     */
    public void setInsdate(Date insdate) {
        this.insdate = insdate;
    }

    /**
     *
     * @return
     */
    public Date getTransdate() {
        return this.transdate;
    }

    /**
     *
     * @param transdate
     */
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }

    /**
     *
     * @return
     */
    public Date getPaydate() {
        return this.paydate;
    }

    /**
     *
     * @param paydate
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     *
     * @return
     */
    public Date getPaydateFcubs() {
        return this.paydateFcubs;
    }

    /**
     *
     * @param paydateFcubs
     */
    public void setPaydateFcubs(Date paydateFcubs) {
        this.paydateFcubs = paydateFcubs;
    }

    /**
     *
     * @return
     */
    public Character getIsapproved() {
        return this.isapproved;
    }

    /**
     *
     * @param isapproved
     */
    public void setIsapproved(Character isapproved) {
        this.isapproved = isapproved;
    }

    /**
     * @return the branchcode
     */
    public String getBranchcode() {
        return branchcode;
    }

    /**
     * @param branchcode the branchcode to set
     */
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }

    public String getResponseCode() {
        return responseCode;
    }

    public void setResponseCode(String responseCode) {
        this.responseCode = responseCode;
    }

    public String getRefFcubsRevert() {
        return refFcubsRevert;
    }

    public void setRefFcubsRevert(String refFcubsRevert) {
        this.refFcubsRevert = refFcubsRevert;
    }
}
