package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * PblBillpaidTransReverse generated by hbm2java
 */
public class PblBillpaidTransReverse implements java.io.Serializable {

    private int idbillpaid;
    private String idpartner;
    private String idservicetype;
    private String idprovider;
    private String customercode;
    private String idchannel;
    private String refPartner;
    private String refFcubs;
    private Long totalamount;
    private Date transdate;
    private Character status;
    private String branchCode;
    private String iduserMakerReverse;
    private String iduserCheckerReverse;
    private String reverseStatus;
    private String branchCodeReverse;
    private String iduserChannelMakerReverse;
    private String iduserChannelCheckerReverse;

    /**
     * Create a new instance of PblBillpaidTransReverse
     */
    public PblBillpaidTransReverse() {
    }

    /**
     *
     * @param idbillpaid
     * @param idservicetype
     * @param idprovider
     * @param customercode
     */
    public PblBillpaidTransReverse(int idbillpaid, String idservicetype, String idprovider, String customercode) {
        this.idbillpaid = idbillpaid;
        this.idservicetype = idservicetype;
        this.idprovider = idprovider;
        this.customercode = customercode;
    }

    /**
     *
     * @param idbillpaid
     * @param idpartner
     * @param idservicetype
     * @param idprovider
     * @param customercode
     * @param idchannel
     * @param refPartner
     * @param refFcubs
     * @param totalamount
     * @param transdate
     * @param status
     * @param branchCode
     * @param iduserMakerReverse
     * @param iduserCheckerReverse
     * @param reverseStatus
     * @param branchCodeReverse
     */
    public PblBillpaidTransReverse(int idbillpaid, String idpartner, String idservicetype, String idprovider, String customercode, String idchannel, String refPartner, String refFcubs, Long totalamount, Date transdate, Character status, String branchCode, String iduserMakerReverse, String iduserCheckerReverse, String reverseStatus, String branchCodeReverse) {
        this.idbillpaid = idbillpaid;
        this.idpartner = idpartner;
        this.idservicetype = idservicetype;
        this.idprovider = idprovider;
        this.customercode = customercode;
        this.idchannel = idchannel;
        this.refPartner = refPartner;
        this.refFcubs = refFcubs;
        this.totalamount = totalamount;
        this.transdate = transdate;
        this.status = status;
        this.branchCode = branchCode;
        this.iduserMakerReverse = iduserMakerReverse;
        this.iduserCheckerReverse = iduserCheckerReverse;
        this.reverseStatus = reverseStatus;
        this.branchCodeReverse = branchCodeReverse;
    }

    /**
     *
     * @return
     */
    public int getIdbillpaid() {
        return this.idbillpaid;
    }

    /**
     *
     * @param idbillpaid
     */
    public void setIdbillpaid(int idbillpaid) {
        this.idbillpaid = idbillpaid;
    }

    /**
     *
     * @return
     */
    public String getIdpartner() {
        return this.idpartner;
    }

    /**
     *
     * @param idpartner
     */
    public void setIdpartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @return
     */
    public String getIdservicetype() {
        return this.idservicetype;
    }

    /**
     *
     * @param idservicetype
     */
    public void setIdservicetype(String idservicetype) {
        this.idservicetype = idservicetype;
    }

    /**
     *
     * @return
     */
    public String getIdprovider() {
        return this.idprovider;
    }

    /**
     *
     * @param idprovider
     */
    public void setIdprovider(String idprovider) {
        this.idprovider = idprovider;
    }

    /**
     *
     * @return
     */
    public String getCustomercode() {
        return this.customercode;
    }

    /**
     *
     * @param customercode
     */
    public void setCustomercode(String customercode) {
        this.customercode = customercode;
    }

    /**
     *
     * @return
     */
    public String getIdchannel() {
        return this.idchannel;
    }

    /**
     *
     * @param idchannel
     */
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    /**
     *
     * @return
     */
    public String getRefPartner() {
        return this.refPartner;
    }

    /**
     *
     * @param refPartner
     */
    public void setRefPartner(String refPartner) {
        this.refPartner = refPartner;
    }

    /**
     *
     * @return
     */
    public String getRefFcubs() {
        return this.refFcubs;
    }

    /**
     *
     * @param refFcubs
     */
    public void setRefFcubs(String refFcubs) {
        this.refFcubs = refFcubs;
    }

    /**
     *
     * @return
     */
    public Long getTotalamount() {
        return this.totalamount;
    }

    /**
     *
     * @param totalamount
     */
    public void setTotalamount(Long totalamount) {
        this.totalamount = totalamount;
    }

    /**
     *
     * @return
     */
    public Date getTransdate() {
        return this.transdate;
    }

    /**
     *
     * @param transdate
     */
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }

    /**
     *
     * @return
     */
    public Character getStatus() {
        return this.status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(Character status) {
        this.status = status;
    }

    /**
     *
     * @return
     */
    public String getBranchCode() {
        return this.branchCode;
    }

    /**
     *
     * @param branchCode
     */
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    /**
     *
     * @return
     */
    public String getIduserMakerReverse() {
        return this.iduserMakerReverse;
    }

    /**
     *
     * @param iduserMakerReverse
     */
    public void setIduserMakerReverse(String iduserMakerReverse) {
        this.iduserMakerReverse = iduserMakerReverse;
    }

    /**
     *
     * @return
     */
    public String getIduserCheckerReverse() {
        return this.iduserCheckerReverse;
    }

    /**
     *
     * @param iduserCheckerReverse
     */
    public void setIduserCheckerReverse(String iduserCheckerReverse) {
        this.iduserCheckerReverse = iduserCheckerReverse;
    }

    /**
     *
     * @return
     */
    public String getReverseStatus() {
        return this.reverseStatus;
    }

    /**
     *
     * @param reverseStatus
     */
    public void setReverseStatus(String reverseStatus) {
        this.reverseStatus = reverseStatus;
    }

    /**
     *
     * @return
     */
    public String getBranchCodeReverse() {
        return this.branchCodeReverse;
    }

    /**
     *
     * @param branchCodeReverse
     */
    public void setBranchCodeReverse(String branchCodeReverse) {
        this.branchCodeReverse = branchCodeReverse;
    }

    /**
     *
     * @return
     */
    public String getIduserChannelMakerReverse() {
        return iduserChannelMakerReverse;
    }

    /**
     *
     * @param iduserChannelMakerReverse
     */
    public void setIduserChannelMakerReverse(String iduserChannelMakerReverse) {
        this.iduserChannelMakerReverse = iduserChannelMakerReverse;
    }

    /**
     *
     * @return
     */
    public String getIduserChannelCheckerReverse() {
        return iduserChannelCheckerReverse;
    }

    /**
     *
     * @param iduserChannelCheckerReverse
     */
    public void setIduserChannelCheckerReverse(String iduserChannelCheckerReverse) {
        this.iduserChannelCheckerReverse = iduserChannelCheckerReverse;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof PblBillpaidTransReverse)) {
            return false;
        }
        PblBillpaidTransReverse castOther = (PblBillpaidTransReverse) other;

        return (this.getIdbillpaid() == castOther.getIdbillpaid())
                && ((this.getIdpartner().equals(castOther.getIdpartner())) || (this.getIdpartner() != null && castOther.getIdpartner() != null && this.getIdpartner().equals(castOther.getIdpartner())))
                && ((this.getIdservicetype().equals(castOther.getIdservicetype())) || (this.getIdservicetype() != null && castOther.getIdservicetype() != null && this.getIdservicetype().equals(castOther.getIdservicetype())))
                && ((this.getIdprovider().equals(castOther.getIdprovider())) || (this.getIdprovider() != null && castOther.getIdprovider() != null && this.getIdprovider().equals(castOther.getIdprovider())))
                && ((this.getCustomercode().equals(castOther.getCustomercode())) || (this.getCustomercode() != null && castOther.getCustomercode() != null && this.getCustomercode().equals(castOther.getCustomercode())))
                && ((this.getIdchannel().equals(castOther.getIdchannel())) || (this.getIdchannel() != null && castOther.getIdchannel() != null && this.getIdchannel().equals(castOther.getIdchannel())))
                && ((this.getRefPartner().equals(castOther.getRefPartner())) || (this.getRefPartner() != null && castOther.getRefPartner() != null && this.getRefPartner().equals(castOther.getRefPartner())))
                && ((this.getRefFcubs().equals(castOther.getRefFcubs())) || (this.getRefFcubs() != null && castOther.getRefFcubs() != null && this.getRefFcubs().equals(castOther.getRefFcubs())))
                && ((this.getTotalamount().equals(castOther.getTotalamount())) || (this.getTotalamount() != null && castOther.getTotalamount() != null && this.getTotalamount().equals(castOther.getTotalamount())))
                && ((this.getTransdate().equals(castOther.getTransdate())) || (this.getTransdate() != null && castOther.getTransdate() != null && this.getTransdate().equals(castOther.getTransdate())))
                && ((this.getStatus().equals(castOther.getStatus())) || (this.getStatus() != null && castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
                && ((this.getBranchCode().equals(castOther.getBranchCode())) || (this.getBranchCode() != null && castOther.getBranchCode() != null && this.getBranchCode().equals(castOther.getBranchCode())))
                && ((this.getIduserMakerReverse().equals(castOther.getIduserMakerReverse())) || (this.getIduserMakerReverse() != null && castOther.getIduserMakerReverse() != null && this.getIduserMakerReverse().equals(castOther.getIduserMakerReverse())))
                && ((this.getIduserCheckerReverse().equals(castOther.getIduserCheckerReverse())) || (this.getIduserCheckerReverse() != null && castOther.getIduserCheckerReverse() != null && this.getIduserCheckerReverse().equals(castOther.getIduserCheckerReverse())))
                && ((this.getReverseStatus().equals(castOther.getReverseStatus())) || (this.getReverseStatus() != null && castOther.getReverseStatus() != null && this.getReverseStatus().equals(castOther.getReverseStatus())))
                && ((this.getBranchCodeReverse().equals(castOther.getBranchCodeReverse())) || (this.getBranchCodeReverse() != null && castOther.getBranchCodeReverse() != null && this.getBranchCodeReverse().equals(castOther.getBranchCodeReverse())))
                && ((this.getIduserChannelMakerReverse().equals(castOther.getIduserChannelMakerReverse())) || (this.getIduserChannelMakerReverse() != null && castOther.getIduserChannelMakerReverse() != null && this.getIduserChannelMakerReverse().equals(castOther.getIduserChannelMakerReverse())))
                && ((this.getIduserChannelCheckerReverse().equals(castOther.getIduserChannelCheckerReverse())) || (this.getIduserChannelCheckerReverse() != null && castOther.getIduserChannelCheckerReverse() != null && this.getIduserChannelCheckerReverse().equals(castOther.getIduserChannelCheckerReverse())));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdbillpaid();
        result = 37 * result + (getIdpartner() == null ? 0 : this.getIdpartner().hashCode());
        result = 37 * result + (getIdservicetype() == null ? 0 : this.getIdservicetype().hashCode());
        result = 37 * result + (getIdprovider() == null ? 0 : this.getIdprovider().hashCode());
        result = 37 * result + (getCustomercode() == null ? 0 : this.getCustomercode().hashCode());
        result = 37 * result + (getIdchannel() == null ? 0 : this.getIdchannel().hashCode());
        result = 37 * result + (getRefPartner() == null ? 0 : this.getRefPartner().hashCode());
        result = 37 * result + (getRefFcubs() == null ? 0 : this.getRefFcubs().hashCode());
        result = 37 * result + (getTotalamount() == null ? 0 : this.getTotalamount().hashCode());
        result = 37 * result + (getTransdate() == null ? 0 : this.getTransdate().hashCode());
        result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
        result = 37 * result + (getBranchCode() == null ? 0 : this.getBranchCode().hashCode());
        result = 37 * result + (getIduserMakerReverse() == null ? 0 : this.getIduserMakerReverse().hashCode());
        result = 37 * result + (getIduserCheckerReverse() == null ? 0 : this.getIduserCheckerReverse().hashCode());
        result = 37 * result + (getReverseStatus() == null ? 0 : this.getReverseStatus().hashCode());
        result = 37 * result + (getBranchCodeReverse() == null ? 0 : this.getBranchCodeReverse().hashCode());
        result = 37 * result + (getIduserChannelMakerReverse() == null ? 0 : this.getIduserChannelMakerReverse().hashCode());
        result = 37 * result + (getIduserChannelCheckerReverse() == null ? 0 : this.getIduserChannelCheckerReverse().hashCode());
        return result;
    }

}
