/**
 *
 * @author LyDTY
 * @Createdate :22/Apr/2014
 *
 */
package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * PblCollated generated by hbm2java
 */
public class PblCollated_VNPAY implements java.io.Serializable {

    private String idpartner;
    private String ACCOUNTNO;
    private String TYETRANS;
    private String AMOUNT;
    private String TRANSID;
    private String TRANSTIME;
    private String TRANSDATE;
    private String PAYDATE;
    private String DEVICETYPE;
    private String BANKTRANSID;
    private String RESPONSECODE;
    private String NOACCEPTCARD;
    private String ADDINFO;
    private String CUSTOMERCODE;
    private Date TRANSDATEFULL;

    /**
     * Create a new instance of PblCollated_VNPAY
     */
    public PblCollated_VNPAY() {
    }

    /**
     *
     * @param idpartner
     * @param ACCOUNTNO
     * @param TYETRANS
     * @param AMOUNT
     * @param TRANSID
     * @param TRANSTIME
     * @param TRANSDATE
     * @param PAYDATE
     * @param DEVICETYPE
     * @param BANKTRANSID
     * @param RESPONSECODE
     * @param NOACCEPTCARD
     * @param ADDINFO
     */
    public PblCollated_VNPAY(String idpartner, String ACCOUNTNO, String TYETRANS, String AMOUNT,
            String TRANSID, String TRANSTIME, String TRANSDATE, String PAYDATE, String DEVICETYPE,
            String BANKTRANSID,
            String RESPONSECODE,
            String NOACCEPTCARD,
            String ADDINFO) {
        this.idpartner = idpartner;
        this.ACCOUNTNO = ACCOUNTNO;
        this.TYETRANS = TYETRANS;
        this.AMOUNT = AMOUNT;
        this.TRANSID = TRANSID;
        this.TRANSTIME = TRANSTIME;
        this.TRANSDATE = TRANSDATE;
        this.PAYDATE = PAYDATE;
        this.DEVICETYPE = DEVICETYPE;
        this.BANKTRANSID = BANKTRANSID;
        this.RESPONSECODE = RESPONSECODE;
        this.NOACCEPTCARD = NOACCEPTCARD;
        this.ADDINFO = ADDINFO;
    }

    /**
     *
     * @return
     */
    public String getIdpartner() {
        return this.idpartner;
    }

    /**
     *
     * @param idpartner
     */
    public void setIdpartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @return
     */
    public String getACCOUNTNO() {
        return this.ACCOUNTNO;
    }

    /**
     *
     * @param ACCOUNTNO
     */
    public void setACCOUNTNO(String ACCOUNTNO) {
        this.ACCOUNTNO = ACCOUNTNO;
    }

    /**
     *
     * @return
     */
    public String getTYETRANS() {
        return this.TYETRANS;
    }

    /**
     *
     * @param TYETRANS
     */
    public void setTYETRANS(String TYETRANS) {
        this.TYETRANS = TYETRANS;
    }

    /**
     *
     * @return
     */
    public String getAMOUNT() {
        return this.AMOUNT;
    }

    /**
     *
     * @param AMOUNT
     */
    public void setAMOUNT(String AMOUNT) {
        this.AMOUNT = AMOUNT;
    }

    /**
     *
     * @return
     */
    public String getTRANSID() {
        return this.TRANSID;
    }

    /**
     *
     * @param TRANSID
     */
    public void setTRANSID(String TRANSID) {
        this.TRANSID = TRANSID;
    }

    /**
     *
     * @return
     */
    public String getTRANSTIME() {
        return this.TRANSTIME;
    }

    /**
     *
     * @param TRANSTIME
     */
    public void setTRANSTIME(String TRANSTIME) {
        this.TRANSTIME = TRANSTIME;
    }

    /**
     *
     * @return
     */
    public String getTRANSDATE() {
        return this.TRANSDATE;
    }

    /**
     *
     * @param TRANSDATE
     */
    public void setTRANSDATE(String TRANSDATE) {
        this.TRANSDATE = TRANSDATE;
    }

    /**
     *
     * @return
     */
    public String getPAYDATE() {
        return this.PAYDATE;
    }

    /**
     *
     * @param PAYDATE
     */
    public void setPAYDATE(String PAYDATE) {
        this.PAYDATE = PAYDATE;
    }

    /**
     *
     * @return
     */
    public String getDEVICETYPE() {
        return this.DEVICETYPE;
    }

    /**
     *
     * @param DEVICETYPE
     */
    public void setDEVICETYPE(String DEVICETYPE) {
        this.DEVICETYPE = DEVICETYPE;
    }

    /**
     *
     * @return
     */
    public String getBANKTRANSID() {
        return this.BANKTRANSID;
    }

    /**
     *
     * @param BANKTRANSID
     */
    public void setBANKTRANSID(String BANKTRANSID) {
        this.BANKTRANSID = BANKTRANSID;
    }

    /**
     *
     * @return
     */
    public String getRESPONSECODE() {
        return this.RESPONSECODE;
    }

    /**
     *
     * @param RESPONSECODE
     */
    public void setRESPONSECODE(String RESPONSECODE) {
        this.RESPONSECODE = RESPONSECODE;
    }

    /**
     *
     * @return
     */
    public String getNOACCEPTCARD() {
        return this.NOACCEPTCARD;
    }

    /**
     *
     * @param NOACCEPTCARD
     */
    public void setNOACCEPTCARD(String NOACCEPTCARD) {
        this.NOACCEPTCARD = NOACCEPTCARD;
    }

    /**
     *
     * @return
     */
    public String getADDINFO() {
        return this.ADDINFO;
    }

    /**
     *
     * @param ADDINFO
     */
    public void setADDINFO(String ADDINFO) {
        this.ADDINFO = ADDINFO;
    }

    /**
     *
     * @return
     */
    public String getCUSTOMERCODE() {
        return this.CUSTOMERCODE;
    }

    /**
     *
     * @param CUSTOMERCODE
     */
    public void setCUSTOMERCODE(String CUSTOMERCODE) {
        this.ADDINFO = CUSTOMERCODE;
    }

    /**
     *
     * @return
     */
    public Date getTRANSDATEFULL() {
        return this.TRANSDATEFULL;
    }

    /**
     *
     * @param TRANSDATEFULL
     */
    public void setTRANSDATEFULL(Date TRANSDATEFULL) {
        this.TRANSDATEFULL = TRANSDATEFULL;
    }

}
