package scb.com.vn.dbi.dto;

/**
 * PblCustTemplate generated by hbm2java
 */
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 *
 * @author system
 */
@XmlRootElement(name = "PblCustTemplate")
public class PblCustTemplate implements java.io.Serializable {

    private int id;
    private String tepmName;
    private String partnerCode;
    private String idservicetype;
    private String idprovider;
    private String customercode;
    private String custAcctNo;
    private String servicetypeName;
    private String providerName;
    private String iduser;

    /**
     * Create a new instance of PblCustTemplate
     */
    public PblCustTemplate() {
    }

    /**
     *
     * @param id
     * @param iduser
     */
    public PblCustTemplate(int id, String iduser) {
        this.id = id;
        this.iduser = iduser;
    }

    /**
     *
     * @param id
     * @param tepmName
     * @param partnerCode
     * @param idservicetype
     * @param idprovider
     * @param customercode
     * @param custAcctNo
     * @param servicetypeName
     * @param providerName
     * @param iduser
     */
    public PblCustTemplate(int id, String tepmName, String partnerCode, String idservicetype, String idprovider, String customercode, String custAcctNo, String servicetypeName, String providerName, String iduser) {
        this.id = id;
        this.tepmName = tepmName;
        this.partnerCode = partnerCode;
        this.idservicetype = idservicetype;
        this.idprovider = idprovider;
        this.customercode = customercode;
        this.custAcctNo = custAcctNo;
        this.servicetypeName = servicetypeName;
        this.providerName = providerName;
        this.iduser = iduser;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "id", nillable = true, required = false)
    public int getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "tepmName", nillable = true, required = false)
    public String getTepmName() {
        return this.tepmName;
    }

    /**
     *
     * @param tepmName
     */
    public void setTepmName(String tepmName) {
        this.tepmName = tepmName;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "partnerCode", nillable = true, required = false)
    public String getPartnerCode() {
        return this.partnerCode;
    }

    /**
     *
     * @param partnerCode
     */
    public void setPartnerCode(String partnerCode) {
        this.partnerCode = partnerCode;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "idservicetype", nillable = true, required = false)
    public String getIdservicetype() {
        return this.idservicetype;
    }

    /**
     *
     * @param idservicetype
     */
    public void setIdservicetype(String idservicetype) {
        this.idservicetype = idservicetype;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "idprovider", nillable = true, required = false)
    public String getIdprovider() {
        return this.idprovider;
    }

    /**
     *
     * @param idprovider
     */
    public void setIdprovider(String idprovider) {
        this.idprovider = idprovider;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "customercode", nillable = true, required = false)
    public String getCustomercode() {
        return this.customercode;
    }

    /**
     *
     * @param customercode
     */
    public void setCustomercode(String customercode) {
        this.customercode = customercode;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "custAcctNo", nillable = true, required = false)
    public String getCustAcctNo() {
        return this.custAcctNo;
    }

    /**
     *
     * @param custAcctNo
     */
    public void setCustAcctNo(String custAcctNo) {
        this.custAcctNo = custAcctNo;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "servicetypeName", nillable = true, required = false)
    public String getServicetypeName() {
        return this.servicetypeName;
    }

    /**
     *
     * @param servicetypeName
     */
    public void setServicetypeName(String servicetypeName) {
        this.servicetypeName = servicetypeName;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "providerName", nillable = true, required = false)
    public String getProviderName() {
        return this.providerName;
    }

    /**
     *
     * @param providerName
     */
    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }

    /**
     *
     * @return
     */
    @XmlElement(name = "iduser", nillable = true, required = false)
    public String getIduser() {
        return this.iduser;
    }

    /**
     *
     * @param iduser
     */
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

}
