package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * PblCollated generated by hbm2java
 */
public class PblCollated implements java.io.Serializable {

    private int id;
    private String idpartner;
    private String data;
    private String custAccNo;
    private String totalamount;
    private String tracecode;
    private String respcode;
    private String adtdata;
    private Date insdate;
    private String processedpartner;
    private String processedbank;

    /**
     * Create a new instance of PblCollated
     */
    public PblCollated() {
    }

    /**
     *
     * @param id
     */
    public PblCollated(int id) {
        this.id = id;
    }

    /**
     *
     * @param id
     * @param idpartner
     * @param data
     * @param custAccNo
     * @param totalamount
     * @param tracecode
     * @param respcode
     * @param adtdata
     * @param insdate
     * @param processedpartner
     * @param processedbank
     */
    public PblCollated(int id, String idpartner, String data, String custAccNo, String totalamount, String tracecode, String respcode, String adtdata, Date insdate, String processedpartner, String processedbank) {
        this.id = id;
        this.idpartner = idpartner;
        this.data = data;
        this.custAccNo = custAccNo;
        this.totalamount = totalamount;
        this.tracecode = tracecode;
        this.respcode = respcode;
        this.adtdata = adtdata;
        this.insdate = insdate;
        this.processedpartner = processedpartner;
        this.processedbank = processedbank;
    }

    /**
     *
     * @return
     */
    public int getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getIdpartner() {
        return this.idpartner;
    }

    /**
     *
     * @param idpartner
     */
    public void setIdpartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @return
     */
    public String getData() {
        return this.data;
    }

    /**
     *
     * @param data
     */
    public void setData(String data) {
        this.data = data;
    }

    /**
     *
     * @return
     */
    public String getCustAccNo() {
        return this.custAccNo;
    }

    /**
     *
     * @param custAccNo
     */
    public void setCustAccNo(String custAccNo) {
        this.custAccNo = custAccNo;
    }

    /**
     *
     * @return
     */
    public String getTotalamount() {
        return this.totalamount;
    }

    /**
     *
     * @param totalamount
     */
    public void setTotalamount(String totalamount) {
        this.totalamount = totalamount;
    }

    /**
     *
     * @return
     */
    public String getTracecode() {
        return this.tracecode;
    }

    /**
     *
     * @param tracecode
     */
    public void setTracecode(String tracecode) {
        this.tracecode = tracecode;
    }

    /**
     *
     * @return
     */
    public String getRespcode() {
        return this.respcode;
    }

    /**
     *
     * @param respcode
     */
    public void setRespcode(String respcode) {
        this.respcode = respcode;
    }

    /**
     *
     * @return
     */
    public String getAdtdata() {
        return this.adtdata;
    }

    /**
     *
     * @param adtdata
     */
    public void setAdtdata(String adtdata) {
        this.adtdata = adtdata;
    }

    /**
     *
     * @return
     */
    public Date getInsdate() {
        return this.insdate;
    }

    /**
     *
     * @param insdate
     */
    public void setInsdate(Date insdate) {
        this.insdate = insdate;
    }

    /**
     *
     * @return
     */
    public String getProcessedpartner() {
        return this.processedpartner;
    }

    /**
     *
     * @param processedpartner
     */
    public void setProcessedpartner(String processedpartner) {
        this.processedpartner = processedpartner;
    }

    /**
     *
     * @return
     */
    public String getProcessedbank() {
        return this.processedbank;
    }

    /**
     *
     * @param processedbank
     */
    public void setProcessedbank(String processedbank) {
        this.processedbank = processedbank;
    }

}
