package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * PblEbkProcess generated by hbm2java
 */
public class PblEbkProcess implements java.io.Serializable {

    private int transcode;
    private String idusr;
    private String custAccNo;
    private String idpartner;
    private String idservicetype;
    private String idprovider;
    private String customercode;
    private String amount;
    private String otptype;
    private String otp;
    private String idscreen;
    private String idkey;
    private String status;
    private Date txnDate;
    private String refBillpaid;

    /**
     * Create a new instance of PblEbkProcess
     */
    public PblEbkProcess() {
    }

    /**
     *
     * @param transcode
     * @param idkey
     */
    public PblEbkProcess(int transcode, String idkey) {
        this.transcode = transcode;
        this.idkey = idkey;
    }

    /**
     *
     * @param transcode
     * @param idusr
     * @param custAccNo
     * @param idpartner
     * @param idservicetype
     * @param idprovider
     * @param customercode
     * @param amount
     * @param otptype
     * @param otp
     * @param idscreen
     * @param idkey
     * @param status
     * @param txnDate
     * @param refBillpaid
     */
    public PblEbkProcess(int transcode, String idusr, String custAccNo, String idpartner, String idservicetype, String idprovider, String customercode, String amount, String otptype, String otp, String idscreen, String idkey, String status, Date txnDate, String refBillpaid) {
        this.transcode = transcode;
        this.idusr = idusr;
        this.custAccNo = custAccNo;
        this.idpartner = idpartner;
        this.idservicetype = idservicetype;
        this.idprovider = idprovider;
        this.customercode = customercode;
        this.amount = amount;
        this.otptype = otptype;
        this.otp = otp;
        this.idscreen = idscreen;
        this.idkey = idkey;
        this.status = status;
        this.txnDate = txnDate;
        this.refBillpaid = refBillpaid;
    }

    /**
     *
     * @return
     */
    public int getTranscode() {
        return this.transcode;
    }

    /**
     *
     * @param transcode
     */
    public void setTranscode(int transcode) {
        this.transcode = transcode;
    }

    /**
     *
     * @return
     */
    public String getIdusr() {
        return this.idusr;
    }

    /**
     *
     * @param idusr
     */
    public void setIdusr(String idusr) {
        this.idusr = idusr;
    }

    /**
     *
     * @return
     */
    public String getCustAccNo() {
        return this.custAccNo;
    }

    /**
     *
     * @param custAccNo
     */
    public void setCustAccNo(String custAccNo) {
        this.custAccNo = custAccNo;
    }

    /**
     *
     * @return
     */
    public String getIdpartner() {
        return this.idpartner;
    }

    /**
     *
     * @param idpartner
     */
    public void setIdpartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @return
     */
    public String getIdservicetype() {
        return this.idservicetype;
    }

    /**
     *
     * @param idservicetype
     */
    public void setIdservicetype(String idservicetype) {
        this.idservicetype = idservicetype;
    }

    /**
     *
     * @return
     */
    public String getIdprovider() {
        return this.idprovider;
    }

    /**
     *
     * @param idprovider
     */
    public void setIdprovider(String idprovider) {
        this.idprovider = idprovider;
    }

    /**
     *
     * @return
     */
    public String getCustomercode() {
        return this.customercode;
    }

    /**
     *
     * @param customercode
     */
    public void setCustomercode(String customercode) {
        this.customercode = customercode;
    }

    /**
     *
     * @return
     */
    public String getAmount() {
        return this.amount;
    }

    /**
     *
     * @param amount
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     *
     * @return
     */
    public String getOtptype() {
        return this.otptype;
    }

    /**
     *
     * @param otptype
     */
    public void setOtptype(String otptype) {
        this.otptype = otptype;
    }

    /**
     *
     * @return
     */
    public String getOtp() {
        return this.otp;
    }

    /**
     *
     * @param otp
     */
    public void setOtp(String otp) {
        this.otp = otp;
    }

    /**
     *
     * @return
     */
    public String getIdscreen() {
        return this.idscreen;
    }

    /**
     *
     * @param idscreen
     */
    public void setIdscreen(String idscreen) {
        this.idscreen = idscreen;
    }

    /**
     *
     * @return
     */
    public String getIdkey() {
        return this.idkey;
    }

    /**
     *
     * @param idkey
     */
    public void setIdkey(String idkey) {
        this.idkey = idkey;
    }

    /**
     *
     * @return
     */
    public String getStatus() {
        return this.status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     *
     * @return
     */
    public Date getTxnDate() {
        return this.txnDate;
    }

    /**
     *
     * @param txnDate
     */
    public void setTxnDate(Date txnDate) {
        this.txnDate = txnDate;
    }

    /**
     *
     * @return
     */
    public String getRefBillpaid() {
        return this.refBillpaid;
    }

    /**
     *
     * @param refBillpaid
     */
    public void setRefBillpaid(String refBillpaid) {
        this.refBillpaid = refBillpaid;
    }

}
