package scb.com.vn.dbi.dto;

/**
 * PblEbkScreenId generated by hbm2java
 */
public class PblEbkScreenId implements java.io.Serializable {

    private int idscreen;
    private String idservicetype;
    private String idprovider;
    private String idpartner;
    private String idlang;

    /**
     * Create a new instance of PblEbkScreenId
     */
    public PblEbkScreenId() {
    }

    /**
     *
     * @param idscreen
     * @param idservicetype
     * @param idprovider
     * @param idpartner
     * @param idlang
     */
    public PblEbkScreenId(int idscreen, String idservicetype, String idprovider, String idpartner, String idlang) {
        this.idscreen = idscreen;
        this.idservicetype = idservicetype;
        this.idprovider = idprovider;
        this.idpartner = idpartner;
        this.idlang = idlang;
    }

    /**
     *
     * @return
     */
    public int getIdscreen() {
        return this.idscreen;
    }

    /**
     *
     * @param idscreen
     */
    public void setIdscreen(int idscreen) {
        this.idscreen = idscreen;
    }

    /**
     *
     * @return
     */
    public String getIdservicetype() {
        return this.idservicetype;
    }

    /**
     *
     * @param idservicetype
     */
    public void setIdservicetype(String idservicetype) {
        this.idservicetype = idservicetype;
    }

    /**
     *
     * @return
     */
    public String getIdprovider() {
        return this.idprovider;
    }

    /**
     *
     * @param idprovider
     */
    public void setIdprovider(String idprovider) {
        this.idprovider = idprovider;
    }

    /**
     *
     * @return
     */
    public String getIdpartner() {
        return this.idpartner;
    }

    /**
     *
     * @param idpartner
     */
    public void setIdpartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @return
     */
    public String getIdlang() {
        return this.idlang;
    }

    /**
     *
     * @param idlang
     */
    public void setIdlang(String idlang) {
        this.idlang = idlang;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof PblEbkScreenId)) {
            return false;
        }
        PblEbkScreenId castOther = (PblEbkScreenId) other;

        return (this.getIdscreen() == castOther.getIdscreen())
                && ((this.getIdservicetype().equals(castOther.getIdservicetype())) || (this.getIdservicetype() != null && castOther.getIdservicetype() != null && this.getIdservicetype().equals(castOther.getIdservicetype())))
                && ((this.getIdprovider().equals(castOther.getIdprovider())) || (this.getIdprovider() != null && castOther.getIdprovider() != null && this.getIdprovider().equals(castOther.getIdprovider())))
                && ((this.getIdpartner().equals(castOther.getIdpartner())) || (this.getIdpartner() != null && castOther.getIdpartner() != null && this.getIdpartner().equals(castOther.getIdpartner())))
                && ((this.getIdlang().equals(castOther.getIdlang())) || (this.getIdlang() != null && castOther.getIdlang() != null && this.getIdlang().equals(castOther.getIdlang())));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdscreen();
        result = 37 * result + (getIdservicetype() == null ? 0 : this.getIdservicetype().hashCode());
        result = 37 * result + (getIdprovider() == null ? 0 : this.getIdprovider().hashCode());
        result = 37 * result + (getIdpartner() == null ? 0 : this.getIdpartner().hashCode());
        result = 37 * result + (getIdlang() == null ? 0 : this.getIdlang().hashCode());
        return result;
    }

}
