package scb.com.vn.dbi.dto;

/**
 * PblEbkScreen generated by hbm2java
 */
public class PblEbkScreen implements java.io.Serializable {

    private PblEbkScreenId id;
    private String data;
    private String description;
    private String data01;
    private String desription01;

    /**
     * Create a new instance of PblEbkScreen
     */
    public PblEbkScreen() {
    }

    /**
     *
     * @param id
     */
    public PblEbkScreen(PblEbkScreenId id) {
        this.id = id;
    }

    /**
     *
     * @param id
     * @param data
     * @param description
     * @param data01
     * @param desription01
     */
    public PblEbkScreen(PblEbkScreenId id, String data, String description, String data01, String desription01) {
        this.id = id;
        this.data = data;
        this.description = description;
        this.data01 = data01;
        this.desription01 = desription01;
    }

    /**
     *
     * @return
     */
    public PblEbkScreenId getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(PblEbkScreenId id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getData() {
        return this.data;
    }

    /**
     *
     * @param data
     */
    public void setData(String data) {
        this.data = data;
    }

    /**
     *
     * @return
     */
    public String getDescription() {
        return this.description;
    }

    /**
     *
     * @param description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     *
     * @return
     */
    public String getData01() {
        return this.data01;
    }

    /**
     *
     * @param data01
     */
    public void setData01(String data01) {
        this.data01 = data01;
    }

    /**
     *
     * @return
     */
    public String getDesription01() {
        return this.desription01;
    }

    /**
     *
     * @param desription01
     */
    public void setDesription01(String desription01) {
        this.desription01 = desription01;
    }

}
