package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * PblLog generated by hbm2java
 */
public class PblLog implements java.io.Serializable {

    private int id;
    private String channel;
    private String idpartner;
    private String idservicetype;
    private String idprovider;
    private String result;
    private String msglog;
    private String description;
    private String idmarker;
    private Date insdate;

    /**
     * Create a new instance of PblLog
     */
    public PblLog() {
    }

    /**
     *
     * @param id
     * @param msglog
     */
    public PblLog(int id, String msglog) {
        this.id = id;
        this.msglog = msglog;
    }

    /**
     *
     * @param id
     * @param channel
     * @param idpartner
     * @param idservicetype
     * @param idprovider
     * @param result
     * @param msglog
     * @param description
     * @param idmarker
     * @param insdate
     */
    public PblLog(int id, String channel, String idpartner, String idservicetype, String idprovider, String result, String msglog, String description, String idmarker, Date insdate) {
        this.id = id;
        this.channel = channel;
        this.idpartner = idpartner;
        this.idservicetype = idservicetype;
        this.idprovider = idprovider;
        this.result = result;
        this.msglog = msglog;
        this.description = description;
        this.idmarker = idmarker;
        this.insdate = insdate;
    }

    /**
     *
     * @return
     */
    public int getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getChannel() {
        return this.channel;
    }

    /**
     *
     * @param channel
     */
    public void setChannel(String channel) {
        this.channel = channel;
    }

    /**
     *
     * @return
     */
    public String getIdpartner() {
        return this.idpartner;
    }

    /**
     *
     * @param idpartner
     */
    public void setIdpartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @return
     */
    public String getIdservicetype() {
        return this.idservicetype;
    }

    /**
     *
     * @param idservicetype
     */
    public void setIdservicetype(String idservicetype) {
        this.idservicetype = idservicetype;
    }

    /**
     *
     * @return
     */
    public String getIdprovider() {
        return this.idprovider;
    }

    /**
     *
     * @param idprovider
     */
    public void setIdprovider(String idprovider) {
        this.idprovider = idprovider;
    }

    /**
     *
     * @return
     */
    public String getResult() {
        return this.result;
    }

    /**
     *
     * @param result
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     *
     * @return
     */
    public String getMsglog() {
        return this.msglog;
    }

    /**
     *
     * @param msglog
     */
    public void setMsglog(String msglog) {
        this.msglog = msglog;
    }

    /**
     *
     * @return
     */
    public String getDescription() {
        return this.description;
    }

    /**
     *
     * @param description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     *
     * @return
     */
    public String getIdmarker() {
        return this.idmarker;
    }

    /**
     *
     * @param idmarker
     */
    public void setIdmarker(String idmarker) {
        this.idmarker = idmarker;
    }

    /**
     *
     * @return
     */
    public Date getInsdate() {
        return this.insdate;
    }

    /**
     *
     * @param insdate
     */
    public void setInsdate(Date insdate) {
        this.insdate = insdate;
    }

}
