package scb.com.vn.dbi.dto;

import java.math.BigDecimal;

/**
 * PblPartnerservice generated by hbm2java
 */
public class PblPartnerservice implements java.io.Serializable {

    private PblPartnerserviceId id;
    private PblServicetype pblServicetype;
    private PblProvider pblProvider;
    private PblPartner pblPartner;
    private String accnofcubs;
    private String accnopartner;
    private BigDecimal priority;

    /**
     * Create a new instance of PblPartnerservice
     */
    public PblPartnerservice() {
    }

    /**
     *
     * @param id
     * @param pblServicetype
     * @param pblProvider
     * @param pblPartner
     */
    public PblPartnerservice(PblPartnerserviceId id, PblServicetype pblServicetype, PblProvider pblProvider, PblPartner pblPartner) {
        this.id = id;
        this.pblServicetype = pblServicetype;
        this.pblProvider = pblProvider;
        this.pblPartner = pblPartner;
    }

    /**
     *
     * @param id
     * @param pblServicetype
     * @param pblProvider
     * @param pblPartner
     * @param accnofcubs
     * @param accnopartner
     * @param priority
     */
    public PblPartnerservice(PblPartnerserviceId id, PblServicetype pblServicetype, PblProvider pblProvider, PblPartner pblPartner, String accnofcubs, String accnopartner, BigDecimal priority) {
        this.id = id;
        this.pblServicetype = pblServicetype;
        this.pblProvider = pblProvider;
        this.pblPartner = pblPartner;
        this.accnofcubs = accnofcubs;
        this.accnopartner = accnopartner;
        this.priority = priority;
    }

    /**
     *
     * @return
     */
    public PblPartnerserviceId getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(PblPartnerserviceId id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public PblServicetype getPblServicetype() {
        return this.pblServicetype;
    }

    /**
     *
     * @param pblServicetype
     */
    public void setPblServicetype(PblServicetype pblServicetype) {
        this.pblServicetype = pblServicetype;
    }

    /**
     *
     * @return
     */
    public PblProvider getPblProvider() {
        return this.pblProvider;
    }

    /**
     *
     * @param pblProvider
     */
    public void setPblProvider(PblProvider pblProvider) {
        this.pblProvider = pblProvider;
    }

    /**
     *
     * @return
     */
    public PblPartner getPblPartner() {
        return this.pblPartner;
    }

    /**
     *
     * @param pblPartner
     */
    public void setPblPartner(PblPartner pblPartner) {
        this.pblPartner = pblPartner;
    }

    /**
     *
     * @return
     */
    public String getAccnofcubs() {
        return this.accnofcubs;
    }

    /**
     *
     * @param accnofcubs
     */
    public void setAccnofcubs(String accnofcubs) {
        this.accnofcubs = accnofcubs;
    }

    /**
     *
     * @return
     */
    public String getAccnopartner() {
        return this.accnopartner;
    }

    /**
     *
     * @param accnopartner
     */
    public void setAccnopartner(String accnopartner) {
        this.accnopartner = accnopartner;
    }

    /**
     *
     * @return
     */
    public BigDecimal getPriority() {
        return this.priority;
    }

    /**
     *
     * @param priority
     */
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }

}
