package scb.com.vn.dbi.dto;

import java.util.HashSet;
import java.util.Set;

/**
 * PblPartner generated by hbm2java
 */
public class PblPartner implements java.io.Serializable {

    private String idpartner;
    private String name;
    private String shortname;
    private Set<PblPartnerservice> pblPartnerservices = new HashSet<PblPartnerservice>(0);

    /**
     * Create a new instance of PblPartner
     */
    public PblPartner() {
    }

    /**
     *
     * @param idpartner
     */
    public PblPartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @param idpartner
     * @param name
     * @param shortname
     * @param pblPartnerservices
     */
    public PblPartner(String idpartner, String name, String shortname, Set<PblPartnerservice> pblPartnerservices) {
        this.idpartner = idpartner;
        this.name = name;
        this.shortname = shortname;
        this.pblPartnerservices = pblPartnerservices;
    }

    /**
     *
     * @return
     */
    public String getIdpartner() {
        return this.idpartner;
    }

    /**
     *
     * @param idpartner
     */
    public void setIdpartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @return
     */
    public String getName() {
        return this.name;
    }

    /**
     *
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     *
     * @return
     */
    public String getShortname() {
        return this.shortname;
    }

    /**
     *
     * @param shortname
     */
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    /**
     *
     * @return
     */
    public Set<PblPartnerservice> getPblPartnerservices() {
        return this.pblPartnerservices;
    }

    /**
     *
     * @param pblPartnerservices
     */
    public void setPblPartnerservices(Set<PblPartnerservice> pblPartnerservices) {
        this.pblPartnerservices = pblPartnerservices;
    }
}
