package scb.com.vn.dbi.dto;

import java.util.HashSet;
import java.util.Set;

/**
 * PblProvider generated by hbm2java
 */
public class PblProvider implements java.io.Serializable {

    private String idprovider;
    private String providername;
    private Set<PblPartnerservice> pblPartnerservices = new HashSet<PblPartnerservice>(0);

    /**
     * Create a new instance of PblProvider
     */
    public PblProvider() {
    }

    /**
     *
     * @param idprovider
     */
    public PblProvider(String idprovider) {
        this.idprovider = idprovider;
    }

    /**
     *
     * @param idprovider
     * @param providername
     * @param pblAutoRegs
     * @param pblPartnerservices
     */
    public PblProvider(String idprovider, String providername, Set<PblAutoReg> pblAutoRegs, Set<PblPartnerservice> pblPartnerservices) {
        this.idprovider = idprovider;
        this.providername = providername;
        this.pblPartnerservices = pblPartnerservices;
    }

    /**
     *
     * @return
     */
    public String getIdprovider() {
        return this.idprovider;
    }

    /**
     *
     * @param idprovider
     */
    public void setIdprovider(String idprovider) {
        this.idprovider = idprovider;
    }

    /**
     *
     * @return
     */
    public String getProvidername() {
        return this.providername;
    }

    /**
     *
     * @param providername
     */
    public void setProvidername(String providername) {
        this.providername = providername;
    }

    /**
     *
     * @return
     */
    public Set<PblPartnerservice> getPblPartnerservices() {
        return this.pblPartnerservices;
    }

    /**
     *
     * @param pblPartnerservices
     */
    public void setPblPartnerservices(Set<PblPartnerservice> pblPartnerservices) {
        this.pblPartnerservices = pblPartnerservices;
    }

}
