package scb.com.vn.dbi.dto;

import java.util.HashSet;
import java.util.Set;

/**
 * PblServicetype generated by hbm2java
 */
public class PblServicetype implements java.io.Serializable {

    private String idservicetype;
    private String name;
    private Character hasautopay;
    private Set<PblPartnerservice> pblPartnerservices = new HashSet<PblPartnerservice>(0);

    /**
     * Create a new instance of PblServicetype
     */
    public PblServicetype() {
    }

    /**
     *
     * @param idservicetype
     */
    public PblServicetype(String idservicetype) {
        this.idservicetype = idservicetype;
    }

    /**
     *
     * @param idservicetype
     * @param name
     * @param hasautopay
     * @param pblPartnerservices
     * @param pblAutoRegs
     */
    public PblServicetype(String idservicetype, String name, Character hasautopay, Set<PblPartnerservice> pblPartnerservices, Set<PblAutoReg> pblAutoRegs) {
        this.idservicetype = idservicetype;
        this.name = name;
        this.hasautopay = hasautopay;
        this.pblPartnerservices = pblPartnerservices;
    }

    /**
     *
     * @return
     */
    public String getIdservicetype() {
        return this.idservicetype;
    }

    /**
     *
     * @param idservicetype
     */
    public void setIdservicetype(String idservicetype) {
        this.idservicetype = idservicetype;
    }

    /**
     *
     * @return
     */
    public String getName() {
        return this.name;
    }

    /**
     *
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     *
     * @return
     */
    public Character getHasautopay() {
        return this.hasautopay;
    }

    /**
     *
     * @param hasautopay
     */
    public void setHasautopay(Character hasautopay) {
        this.hasautopay = hasautopay;
    }

    /**
     *
     * @return
     */
    public Set<PblPartnerservice> getPblPartnerservices() {
        return this.pblPartnerservices;
    }

    /**
     *
     * @param pblPartnerservices
     */
    public void setPblPartnerservices(Set<PblPartnerservice> pblPartnerservices) {
        this.pblPartnerservices = pblPartnerservices;
    }
}
