package scb.com.vn.dbi.dto;

import java.util.HashSet;
import java.util.Set;

/**
 * PfiPartner generated by hbm2java
 */
public class PFIPartner implements java.io.Serializable {

    private String idpartner;
    private String name;
    private String shortname;
    private String partnertype;
    private String isactive;
    private Set<SITrftToSIAuth> siTrftToSIAuth = new HashSet<SITrftToSIAuth>(0);

    /**
     * Create a new instance of PFIPartner
     */
    public PFIPartner() {
    }

    /**
     *
     * @param idpartner
     */
    public PFIPartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @param idpartner
     * @param name
     * @param shortname
     * @param partnertype
     * @param isactive
     * @param siTrftToSIAuth
     */
    public PFIPartner(String idpartner, String name, String shortname, String partnertype, String isactive, Set<SITrftToSIAuth> siTrftToSIAuth) {
        this.idpartner = idpartner;
        this.name = name;
        this.shortname = shortname;
        this.partnertype = partnertype;
        this.isactive = isactive;
        this.siTrftToSIAuth = siTrftToSIAuth;
    }

    /**
     *
     * @return
     */
    public String getIdpartner() {
        return this.idpartner;
    }

    /**
     *
     * @param idpartner
     */
    public void setIdpartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @return
     */
    public String getName() {
        return this.name;
    }

    /**
     *
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     *
     * @return
     */
    public String getShortname() {
        return this.shortname;
    }

    /**
     *
     * @param shortname
     */
    public void setShortname(String shortname) {
        this.shortname = shortname;
    }

    /**
     *
     * @return
     */
    public String getPartnertype() {
        return partnertype;
    }

    /**
     *
     * @param partnertype
     */
    public void setPartnertype(String partnertype) {
        this.partnertype = partnertype;
    }

    /**
     *
     * @return
     */
    public String getIsactive() {
        return isactive;
    }

    /**
     *
     * @param isactive
     */
    public void setIsactive(String isactive) {
        this.isactive = isactive;
    }

    /**
     *
     * @return
     */
    public Set<SITrftToSIAuth> getSiTrftToSIAuth() {
        return siTrftToSIAuth;
    }

    /**
     *
     * @param siTrftToSIAuth
     */
    public void setSiTrftToSIAuth(Set<SITrftToSIAuth> siTrftToSIAuth) {
        this.siTrftToSIAuth = siTrftToSIAuth;
    }
}
