package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * PblBillpaid generated by hbm2java
 */
public class RTBuyCardDTO implements java.io.Serializable {

    private int id;
    private String idprovider;
    private String idpartner;
    private String orgtransid;
    private String pricetag;
    private Integer quantity;
    private Long discount;
    private String iduserMaker;
    private String idchanneluserMaker;
    private Date insdateMaker;
    private String iduserChecker;
    private String idchanneluserChecker;
    private Date insdateChecker;
    private String idchannel;
    private String refPartner;
    private String refFcubs;
    private Long totalamount;
    private Integer paymentmethod;
    private String accCust;
    private String accIdaccount;
    private String accHoldername;
    private String accAddress;
    private Date insdate;
    private Date transdate;
    private Date paydate;
    private Date paydateFcubs;
    private Character isapproved;
    private Character status;
    private String branchcode;

    /**
     *
     * @return
     */
    public Character getStatus() {
        return status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(Character status) {
        this.status = status;
    }

    /**
     * Create a new instance of RTBuyCardDTO
     */
    public RTBuyCardDTO() {
    }

    /**
     *
     * @param id
     * @param idprovider
     * @param idpartner
     * @param iduserMaker
     * @param idchanneluserMaker
     * @param insdateMaker
     * @param iduserChecker
     * @param idchanneluserChecker
     * @param insdateChecker
     * @param idchannel
     * @param refPartner
     * @param refFcubs
     * @param totalamount
     * @param paymentmethod
     * @param accCust
     * @param accIdaccount
     * @param accHoldername
     * @param accAddress
     * @param insdate
     * @param transdate
     * @param paydate
     * @param paydateFcubs
     * @param isapproved
     * @param status
     */
    public RTBuyCardDTO(int id, String idprovider, String idpartner, String iduserMaker, String idchanneluserMaker, Date insdateMaker, String iduserChecker, String idchanneluserChecker, Date insdateChecker, String idchannel, String refPartner, String refFcubs, Long totalamount, Integer paymentmethod, String accCust, String accIdaccount, String accHoldername, String accAddress, Date insdate, Date transdate, Date paydate, Date paydateFcubs, Character isapproved, Character status) {
        this.id = id;
        this.idprovider = idprovider;
        this.idpartner = idpartner;
        this.iduserMaker = iduserMaker;
        this.idchanneluserMaker = idchanneluserMaker;
        this.insdateMaker = insdateMaker;
        this.iduserChecker = iduserChecker;
        this.idchanneluserChecker = idchanneluserChecker;
        this.insdateChecker = insdateChecker;
        this.idchannel = idchannel;
        this.refPartner = refPartner;
        this.refFcubs = refFcubs;
        this.totalamount = totalamount;
        this.paymentmethod = paymentmethod;
        this.accCust = accCust;
        this.accIdaccount = accIdaccount;
        this.accHoldername = accHoldername;
        this.accAddress = accAddress;
        this.insdate = insdate;
        this.transdate = transdate;
        this.paydate = paydate;
        this.paydateFcubs = paydateFcubs;
        this.isapproved = isapproved;
        this.status = status;
    }

    /**
     *
     * @return
     */
    public int getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getIdprovider() {
        return idprovider;
    }

    /**
     *
     * @param idprovider
     */
    public void setIdprovider(String idprovider) {
        this.idprovider = idprovider;
    }

    /**
     *
     * @return
     */
    public String getOrgtransid() {
        return orgtransid;
    }

    /**
     *
     * @param orgtransid
     */
    public void setOrgtransid(String orgtransid) {
        this.orgtransid = orgtransid;
    }

    /**
     *
     * @return
     */
    public String getPricetag() {
        return pricetag;
    }

    /**
     *
     * @param pricetag
     */
    public void setPricetag(String pricetag) {
        this.pricetag = pricetag;
    }

    /**
     *
     * @return
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     *
     * @param quantity
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     *
     * @return
     */
    public Long getDiscount() {
        return discount;
    }

    /**
     *
     * @param discount
     */
    public void setDiscount(Long discount) {
        this.discount = discount;
    }

    /**
     *
     * @return
     */
    public String getIdpartner() {
        return this.idpartner;
    }

    /**
     *
     * @param idpartner
     */
    public void setIdpartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @return
     */
    public String getIduserMaker() {
        return this.iduserMaker;
    }

    /**
     *
     * @param iduserMaker
     */
    public void setIduserMaker(String iduserMaker) {
        this.iduserMaker = iduserMaker;
    }

    /**
     *
     * @return
     */
    public String getIdchanneluserMaker() {
        return this.idchanneluserMaker;
    }

    /**
     *
     * @param idchanneluserMaker
     */
    public void setIdchanneluserMaker(String idchanneluserMaker) {
        this.idchanneluserMaker = idchanneluserMaker;
    }

    /**
     *
     * @return
     */
    public Date getInsdateMaker() {
        return this.insdateMaker;
    }

    /**
     *
     * @param insdateMaker
     */
    public void setInsdateMaker(Date insdateMaker) {
        this.insdateMaker = insdateMaker;
    }

    /**
     *
     * @return
     */
    public String getIduserChecker() {
        return this.iduserChecker;
    }

    /**
     *
     * @param iduserChecker
     */
    public void setIduserChecker(String iduserChecker) {
        this.iduserChecker = iduserChecker;
    }

    /**
     *
     * @return
     */
    public String getIdchanneluserChecker() {
        return this.idchanneluserChecker;
    }

    /**
     *
     * @param idchanneluserChecker
     */
    public void setIdchanneluserChecker(String idchanneluserChecker) {
        this.idchanneluserChecker = idchanneluserChecker;
    }

    /**
     *
     * @return
     */
    public Date getInsdateChecker() {
        return this.insdateChecker;
    }

    /**
     *
     * @param insdateChecker
     */
    public void setInsdateChecker(Date insdateChecker) {
        this.insdateChecker = insdateChecker;
    }

    /**
     *
     * @return
     */
    public String getIdchannel() {
        return this.idchannel;
    }

    /**
     *
     * @param idchannel
     */
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    /**
     *
     * @return
     */
    public String getRefPartner() {
        return this.refPartner;
    }

    /**
     *
     * @param refPartner
     */
    public void setRefPartner(String refPartner) {
        this.refPartner = refPartner;
    }

    /**
     *
     * @return
     */
    public String getRefFcubs() {
        return this.refFcubs;
    }

    /**
     *
     * @param refFcubs
     */
    public void setRefFcubs(String refFcubs) {
        this.refFcubs = refFcubs;
    }

    /**
     *
     * @return
     */
    public Long getTotalamount() {
        return this.totalamount;
    }

    /**
     *
     * @param totalamount
     */
    public void setTotalamount(Long totalamount) {
        this.totalamount = totalamount;
    }

    /**
     *
     * @return
     */
    public Integer getPaymentmethod() {
        return this.paymentmethod;
    }

    /**
     *
     * @param paymentmethod
     */
    public void setPaymentmethod(Integer paymentmethod) {
        this.paymentmethod = paymentmethod;
    }

    /**
     *
     * @return
     */
    public String getAccCust() {
        return this.accCust;
    }

    /**
     *
     * @param accCust
     */
    public void setAccCust(String accCust) {
        this.accCust = accCust;
    }

    /**
     *
     * @return
     */
    public String getAccIdaccount() {
        return this.accIdaccount;
    }

    /**
     *
     * @param accIdaccount
     */
    public void setAccIdaccount(String accIdaccount) {
        this.accIdaccount = accIdaccount;
    }

    /**
     *
     * @return
     */
    public String getAccHoldername() {
        return this.accHoldername;
    }

    /**
     *
     * @param accHoldername
     */
    public void setAccHoldername(String accHoldername) {
        this.accHoldername = accHoldername;
    }

    /**
     *
     * @return
     */
    public String getAccAddress() {
        return this.accAddress;
    }

    /**
     *
     * @param accAddress
     */
    public void setAccAddress(String accAddress) {
        this.accAddress = accAddress;
    }

    /**
     *
     * @return
     */
    public Date getInsdate() {
        return this.insdate;
    }

    /**
     *
     * @param insdate
     */
    public void setInsdate(Date insdate) {
        this.insdate = insdate;
    }

    /**
     *
     * @return
     */
    public Date getTransdate() {
        return this.transdate;
    }

    /**
     *
     * @param transdate
     */
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }

    /**
     *
     * @return
     */
    public Date getPaydate() {
        return this.paydate;
    }

    /**
     *
     * @param paydate
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     *
     * @return
     */
    public Date getPaydateFcubs() {
        return this.paydateFcubs;
    }

    /**
     *
     * @param paydateFcubs
     */
    public void setPaydateFcubs(Date paydateFcubs) {
        this.paydateFcubs = paydateFcubs;
    }

    /**
     *
     * @return
     */
    public Character getIsapproved() {
        return this.isapproved;
    }

    /**
     *
     * @param isapproved
     */
    public void setIsapproved(Character isapproved) {
        this.isapproved = isapproved;
    }

    /**
     * @return the branchcode
     */
    public String getBranchcode() {
        return branchcode;
    }

    /**
     * @param branchcode the branchcode to set
     */
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }

}
