package scb.com.vn.dbi.dto;

/**
 * PblProvider generated by hbm2java
 */
public class RTCardDetailDTO implements java.io.Serializable {

    private Integer id;
    private Integer idbuycard;
    private String idprovider;
    private String cardcode;
    private String serial;
    private String pricetag;
    private String expire_date;

    /**
     * Create a new instance of RTCardDetailDTO
     */
    public RTCardDetailDTO() {
    }

    /**
     *
     * @return
     */
    public Integer getIdbuycard() {
        return idbuycard;
    }

    /**
     *
     * @param idbuycard
     */
    public void setIdbuycard(Integer idbuycard) {
        this.idbuycard = idbuycard;
    }

    /**
     *
     * @param id
     */
    public RTCardDetailDTO(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getIdprovider() {
        return idprovider;
    }

    /**
     *
     * @param idprovider
     */
    public void setIdprovider(String idprovider) {
        this.idprovider = idprovider;
    }

    /**
     *
     * @return
     */
    public String getCardcode() {
        return cardcode;
    }

    /**
     *
     * @param cardcode
     */
    public void setCardcode(String cardcode) {
        this.cardcode = cardcode;
    }

    /**
     *
     * @return
     */
    public String getSerial() {
        return serial;
    }

    /**
     *
     * @param serial
     */
    public void setSerial(String serial) {
        this.serial = serial;
    }

    /**
     *
     * @return
     */
    public String getPricetag() {
        return pricetag;
    }

    /**
     *
     * @param pricetag
     */
    public void setPricetag(String pricetag) {
        this.pricetag = pricetag;
    }

    /**
     *
     * @return
     */
    public String getExpire_date() {
        return expire_date;
    }

    /**
     *
     * @param expire_date
     */
    public void setExpire_date(String expire_date) {
        this.expire_date = expire_date;
    }

}
