package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * SITrftToSIAuth generated by hbm2java
 */
public class SITrftToSIAuth implements java.io.Serializable {

    private int idbillpaid;
    private String servicetype;
    private String provider;
    private PFIPartner pfipartner;
    private String customercode;
    private String dataxml;
    private String iduserMaker;
    private String idchanneluserMaker;
    private Date insdateMaker;
    private String iduserChecker;
    private String idchanneluserChecker;
    private Date insdateChecker;
    private String idchannel;
    private String usertype;
    private String refPartner;
    private String refFcubs;
    private Long totalamount;
    private Integer paymentmethod;
    private String accCust;
    private String accIdaccount;
    private String accHoldername;
    private String accAddress;
    private Date insdate;
    private Date transdate;
    private Date paydate;
    private Date paydateFcubs;
    private Character isapproved;
    private Character status;
    private String branchcode;
    private String siname;
    private String branch_name;
    private String custtype;

    private String CMND;
    private String cusType;
    private String ngayCapCMND;
    private String noiCapCMND;
    private String sdtKH;
    private String dCMND;
    private String dNguoiNopTien;
    private String dNgayCap;
    private String dNoiCap;
    private String dsdt;

    public String getCusttype() {
        return custtype;
    }

    public void setCusttype(String custtype) {
        this.custtype = custtype;
    }

    public String getBranch_name() {
        return branch_name;
    }

    public void setBranch_name(String branch_name) {
        this.branch_name = branch_name;
    }

    public String getSiname() {
        return siname;
    }

    /**
     *
     * @return
     */
    public void setSiname(String siname) {
        this.siname = siname;
    }

    public Character getStatus() {
        return status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(Character status) {
        this.status = status;
    }

    /**
     * Create a new instance of SITrftToSIAuth
     */
    public SITrftToSIAuth() {
    }

    /**
     *
     * @param idbillpaid
     * @param servicetype
     * @param provider
     * @param customercode
     */
    public SITrftToSIAuth(int idbillpaid, String servicetype, String provider, String customercode) {
        this.idbillpaid = idbillpaid;
        this.servicetype = servicetype;
        this.provider = provider;
        this.customercode = customercode;
    }

    /**
     *
     * @param idbillpaid
     * @param servicetype
     * @param provider
     * @param pfipartner
     * @param customercode
     * @param dataxml
     * @param iduserMaker
     * @param idchanneluserMaker
     * @param insdateMaker
     * @param iduserChecker
     * @param idchanneluserChecker
     * @param insdateChecker
     * @param idchannel
     * @param usertype
     * @param refPartner
     * @param refFcubs
     * @param totalamount
     * @param paymentmethod
     * @param accCust
     * @param accIdaccount
     * @param accHoldername
     * @param accAddress
     * @param insdate
     * @param transdate
     * @param paydate
     * @param paydateFcubs
     * @param isapproved
     * @param status
     */
    public SITrftToSIAuth(int idbillpaid, String servicetype, String provider, PFIPartner pfipartner, String customercode, String dataxml, String iduserMaker, String idchanneluserMaker, Date insdateMaker, String iduserChecker, String idchanneluserChecker, Date insdateChecker, String idchannel, String usertype, String refPartner, String refFcubs, Long totalamount, Integer paymentmethod, String accCust, String accIdaccount, String accHoldername, String accAddress, Date insdate, Date transdate, Date paydate, Date paydateFcubs, Character isapproved, Character status) {
        this.idbillpaid = idbillpaid;
        this.servicetype = servicetype;
        this.provider = provider;
        this.pfipartner = pfipartner;
        this.customercode = customercode;
        this.dataxml = dataxml;
        this.iduserMaker = iduserMaker;
        this.idchanneluserMaker = idchanneluserMaker;
        this.insdateMaker = insdateMaker;
        this.iduserChecker = iduserChecker;
        this.idchanneluserChecker = idchanneluserChecker;
        this.insdateChecker = insdateChecker;
        this.idchannel = idchannel;
        this.usertype = usertype;
        this.refPartner = refPartner;
        this.refFcubs = refFcubs;
        this.totalamount = totalamount;
        this.paymentmethod = paymentmethod;
        this.accCust = accCust;
        this.accIdaccount = accIdaccount;
        this.accHoldername = accHoldername;
        this.accAddress = accAddress;
        this.insdate = insdate;
        this.transdate = transdate;
        this.paydate = paydate;
        this.paydateFcubs = paydateFcubs;
        this.isapproved = isapproved;
        this.status = status;
    }

    /**
     *
     * @return
     */
    public int getIdbillpaid() {
        return this.idbillpaid;
    }

    /**
     *
     * @param idbillpaid
     */
    public void setIdbillpaid(int idbillpaid) {
        this.idbillpaid = idbillpaid;
    }

    /**
     *
     * @return
     */
    public String getServicetype() {
        return servicetype;
    }

    /**
     *
     * @param servicetype
     */
    public void setServicetype(String servicetype) {
        this.servicetype = servicetype;
    }

    /**
     *
     * @return
     */
    public String getProvider() {
        return provider;
    }

    /**
     *
     * @param provider
     */
    public void setProvider(String provider) {
        this.provider = provider;
    }

    /**
     *
     * @return
     */
    public PFIPartner getPfipartner() {
        return pfipartner;
    }

    /**
     *
     * @param pfipartner
     */
    public void setPfipartner(PFIPartner pfipartner) {
        this.pfipartner = pfipartner;
    }

    /**
     *
     * @return
     */
    public String getCustomercode() {
        return this.customercode;
    }

    /**
     *
     * @param customercode
     */
    public void setCustomercode(String customercode) {
        this.customercode = customercode;
    }

    /**
     *
     * @return
     */
    public String getDataxml() {
        return this.dataxml;
    }

    /**
     *
     * @param dataxml
     */
    public void setDataxml(String dataxml) {
        this.dataxml = dataxml;
    }

    /**
     *
     * @return
     */
    public String getIduserMaker() {
        return this.iduserMaker;
    }

    /**
     *
     * @param iduserMaker
     */
    public void setIduserMaker(String iduserMaker) {
        this.iduserMaker = iduserMaker;
    }

    /**
     *
     * @return
     */
    public String getIdchanneluserMaker() {
        return this.idchanneluserMaker;
    }

    /**
     *
     * @param idchanneluserMaker
     */
    public void setIdchanneluserMaker(String idchanneluserMaker) {
        this.idchanneluserMaker = idchanneluserMaker;
    }

    /**
     *
     * @return
     */
    public Date getInsdateMaker() {
        return this.insdateMaker;
    }

    /**
     *
     * @param insdateMaker
     */
    public void setInsdateMaker(Date insdateMaker) {
        this.insdateMaker = insdateMaker;
    }

    /**
     *
     * @return
     */
    public String getIduserChecker() {
        return this.iduserChecker;
    }

    /**
     *
     * @param iduserChecker
     */
    public void setIduserChecker(String iduserChecker) {
        this.iduserChecker = iduserChecker;
    }

    /**
     *
     * @return
     */
    public String getIdchanneluserChecker() {
        return this.idchanneluserChecker;
    }

    /**
     *
     * @param idchanneluserChecker
     */
    public void setIdchanneluserChecker(String idchanneluserChecker) {
        this.idchanneluserChecker = idchanneluserChecker;
    }

    /**
     *
     * @return
     */
    public Date getInsdateChecker() {
        return this.insdateChecker;
    }

    /**
     *
     * @param insdateChecker
     */
    public void setInsdateChecker(Date insdateChecker) {
        this.insdateChecker = insdateChecker;
    }

    /**
     *
     * @return
     */
    public String getIdchannel() {
        return this.idchannel;
    }

    /**
     *
     * @param idchannel
     */
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    /**
     *
     * @return
     */
    public String getUsertype() {
        return this.usertype;
    }

    /**
     *
     * @param usertype
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    /**
     *
     * @return
     */
    public String getRefPartner() {
        return this.refPartner;
    }

    /**
     *
     * @param refPartner
     */
    public void setRefPartner(String refPartner) {
        this.refPartner = refPartner;
    }

    /**
     *
     * @return
     */
    public String getRefFcubs() {
        return this.refFcubs;
    }

    /**
     *
     * @param refFcubs
     */
    public void setRefFcubs(String refFcubs) {
        this.refFcubs = refFcubs;
    }

    /**
     *
     * @return
     */
    public Long getTotalamount() {
        return this.totalamount;
    }

    /**
     *
     * @param totalamount
     */
    public void setTotalamount(Long totalamount) {
        this.totalamount = totalamount;
    }

    /**
     *
     * @return
     */
    public Integer getPaymentmethod() {
        return this.paymentmethod;
    }

    /**
     *
     * @param paymentmethod
     */
    public void setPaymentmethod(Integer paymentmethod) {
        this.paymentmethod = paymentmethod;
    }

    /**
     *
     * @return
     */
    public String getAccCust() {
        return this.accCust;
    }

    /**
     *
     * @param accCust
     */
    public void setAccCust(String accCust) {
        this.accCust = accCust;
    }

    /**
     *
     * @return
     */
    public String getAccIdaccount() {
        return this.accIdaccount;
    }

    /**
     *
     * @param accIdaccount
     */
    public void setAccIdaccount(String accIdaccount) {
        this.accIdaccount = accIdaccount;
    }

    /**
     *
     * @return
     */
    public String getAccHoldername() {
        return this.accHoldername;
    }

    /**
     *
     * @param accHoldername
     */
    public void setAccHoldername(String accHoldername) {
        this.accHoldername = accHoldername;
    }

    /**
     *
     * @return
     */
    public String getAccAddress() {
        return this.accAddress;
    }

    /**
     *
     * @param accAddress
     */
    public void setAccAddress(String accAddress) {
        this.accAddress = accAddress;
    }

    /**
     *
     * @return
     */
    public Date getInsdate() {
        return this.insdate;
    }

    /**
     *
     * @param insdate
     */
    public void setInsdate(Date insdate) {
        this.insdate = insdate;
    }

    /**
     *
     * @return
     */
    public Date getTransdate() {
        return this.transdate;
    }

    /**
     *
     * @param transdate
     */
    public void setTransdate(Date transdate) {
        this.transdate = transdate;
    }

    /**
     *
     * @return
     */
    public Date getPaydate() {
        return this.paydate;
    }

    /**
     *
     * @param paydate
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     *
     * @return
     */
    public Date getPaydateFcubs() {
        return this.paydateFcubs;
    }

    /**
     *
     * @param paydateFcubs
     */
    public void setPaydateFcubs(Date paydateFcubs) {
        this.paydateFcubs = paydateFcubs;
    }

    /**
     *
     * @return
     */
    public Character getIsapproved() {
        return this.isapproved;
    }

    /**
     *
     * @param isapproved
     */
    public void setIsapproved(Character isapproved) {
        this.isapproved = isapproved;
    }

    /**
     * @return the branchcode
     */
    public String getBranchcode() {
        return branchcode;
    }

    /**
     * @param branchcode the branchcode to set
     */
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }

    public String getCusType() {
        return cusType;
    }

    public void setCusType(String cusType) {
        this.cusType = cusType;
    }

    public String getCMND() {
        return CMND;
    }

    public void setCMND(String CMND) {
        this.CMND = CMND;
    }

    public String getNgayCapCMND() {
        return ngayCapCMND;
    }

    public void setNgayCapCMND(String ngayCapCMND) {
        this.ngayCapCMND = ngayCapCMND;
    }

    public String getNoiCapCMND() {
        return noiCapCMND;
    }

    public void setNoiCapCMND(String noiCapCMND) {
        this.noiCapCMND = noiCapCMND;
    }

    public String getSdtKH() {
        return sdtKH;
    }

    public void setSdtKH(String sdtKH) {
        this.sdtKH = sdtKH;
    }

    public String getdCMND() {
        return dCMND;
    }

    public void setdCMND(String dCMND) {
        this.dCMND = dCMND;
    }

    public String getdNguoiNopTien() {
        return dNguoiNopTien;
    }

    public void setdNguoiNopTien(String dNguoiNopTien) {
        this.dNguoiNopTien = dNguoiNopTien;
    }

    public String getdNgayCap() {
        return dNgayCap;
    }

    public void setdNgayCap(String dNgayCap) {
        this.dNgayCap = dNgayCap;
    }

    public String getdNoiCap() {
        return dNoiCap;
    }

    public void setdNoiCap(String dNoiCap) {
        this.dNoiCap = dNoiCap;
    }

    public String getDsdt() {
        return dsdt;
    }

    public void setDsdt(String dsdt) {
        this.dsdt = dsdt;
    }

}
