package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * SmsAlertnotify generated by hbm2java
 */
public class SmsAlertnotify implements java.io.Serializable {

    private static final long serialVersionUID = 5674858775824102571L;

    private long idmessage;
    private String idalert;
    private Date datcreated;
    private String subject;
    private String address;
    private String uniqueid;
    private String messageold;
    private String messagenew;
    private Character messagestat;
    private Date senddate;

    /**
     * Create a new instance of SmsAlertnotify
     */
    public SmsAlertnotify() {
    }

    /**
     *
     * @param idmessage
     */
    public SmsAlertnotify(long idmessage) {
        this.idmessage = idmessage;
    }

    /**
     *
     * @param idmessage
     * @param idalert
     * @param datcreated
     * @param subject
     * @param address
     * @param uniqueid
     * @param messageold
     * @param messagenew
     * @param messagestat
     * @param senddate
     */
    public SmsAlertnotify(long idmessage, String idalert, Date datcreated, String subject, String address, String uniqueid, String messageold, String messagenew, Character messagestat, Date senddate) {
        this.idmessage = idmessage;
        this.idalert = idalert;
        this.datcreated = datcreated;
        this.subject = subject;
        this.address = address;
        this.uniqueid = uniqueid;
        this.messageold = messageold;
        this.messagenew = messagenew;
        this.messagestat = messagestat;
        this.senddate = senddate;
    }

    /**
     *
     * @return
     */
    public long getIdmessage() {
        return this.idmessage;
    }

    /**
     *
     * @param idmessage
     */
    public void setIdmessage(long idmessage) {
        this.idmessage = idmessage;
    }

    /**
     *
     * @return
     */
    public String getIdalert() {
        return this.idalert;
    }

    /**
     *
     * @param idalert
     */
    public void setIdalert(String idalert) {
        this.idalert = idalert;
    }

    /**
     *
     * @return
     */
    public Date getDatcreated() {
        return this.datcreated;
    }

    /**
     *
     * @param datcreated
     */
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    /**
     *
     * @return
     */
    public String getSubject() {
        return this.subject;
    }

    /**
     *
     * @param subject
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     *
     * @return
     */
    public String getAddress() {
        return this.address;
    }

    /**
     *
     * @param address
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     *
     * @return
     */
    public String getUniqueid() {
        return this.uniqueid;
    }

    /**
     *
     * @param uniqueid
     */
    public void setUniqueid(String uniqueid) {
        this.uniqueid = uniqueid;
    }

    /**
     *
     * @return
     */
    public String getMessageold() {
        return this.messageold;
    }

    /**
     *
     * @param messageold
     */
    public void setMessageold(String messageold) {
        this.messageold = messageold;
    }

    /**
     *
     * @return
     */
    public String getMessagenew() {
        return this.messagenew;
    }

    /**
     *
     * @param messagenew
     */
    public void setMessagenew(String messagenew) {
        this.messagenew = messagenew;
    }

    /**
     *
     * @return
     */
    public Character getMessagestat() {
        return this.messagestat;
    }

    /**
     *
     * @param messagestat
     */
    public void setMessagestat(Character messagestat) {
        this.messagestat = messagestat;
    }

    /**
     *
     * @return
     */
    public Date getSenddate() {
        return this.senddate;
    }

    /**
     *
     * @param senddate
     */
    public void setSenddate(Date senddate) {
        this.senddate = senddate;
    }

}
