package scb.com.vn.dbi.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 * SmsLog generated by hbm2java
 */
public class SmsLog implements java.io.Serializable {

    private BigDecimal id;
    private String idchanneluser;
    private String typeuser;
    private String result;
    private String msglog;
    private String idmarker;
    private Date insdate;

    /**
     * Create a new instance of SmsLog
     */
    public SmsLog() {
    }

    /**
     *
     * @param id
     * @param msglog
     */
    public SmsLog(BigDecimal id, String msglog) {
        this.id = id;
        this.msglog = msglog;
    }

    /**
     *
     * @param id
     * @param idchanneluser
     * @param typeuser
     * @param result
     * @param msglog
     * @param idmarker
     * @param insdate
     */
    public SmsLog(BigDecimal id, String idchanneluser, String typeuser, String result, String msglog, String idmarker, Date insdate) {
        this.id = id;
        this.idchanneluser = idchanneluser;
        this.typeuser = typeuser;
        this.result = result;
        this.msglog = msglog;
        this.idmarker = idmarker;
        this.insdate = insdate;
    }

    /**
     *
     * @return
     */
    public BigDecimal getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getIdchanneluser() {
        return this.idchanneluser;
    }

    /**
     *
     * @param idchanneluser
     */
    public void setIdchanneluser(String idchanneluser) {
        this.idchanneluser = idchanneluser;
    }

    /**
     *
     * @return
     */
    public String getTypeuser() {
        return this.typeuser;
    }

    /**
     *
     * @param typeuser
     */
    public void setTypeuser(String typeuser) {
        this.typeuser = typeuser;
    }

    /**
     *
     * @return
     */
    public String getResult() {
        return this.result;
    }

    /**
     *
     * @param result
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     *
     * @return
     */
    public String getMsglog() {
        return this.msglog;
    }

    /**
     *
     * @param msglog
     */
    public void setMsglog(String msglog) {
        this.msglog = msglog;
    }

    /**
     *
     * @return
     */
    public String getIdmarker() {
        return this.idmarker;
    }

    /**
     *
     * @param idmarker
     */
    public void setIdmarker(String idmarker) {
        this.idmarker = idmarker;
    }

    /**
     *
     * @return
     */
    public Date getInsdate() {
        return this.insdate;
    }

    /**
     *
     * @param insdate
     */
    public void setInsdate(Date insdate) {
        this.insdate = insdate;
    }

}
