package scb.com.vn.dbi.dto;

/**
 * SmsPartner generated by hbm2java
 */
public class SmsPartner implements java.io.Serializable {

    private String idpartner;
    private String partnercode;
    private String partnername;
    private long retryNoMax;
    private long retried;
    private String phonecontact;
    private String status;

    /**
     * Create a new instance of SmsPartner
     */
    public SmsPartner() {
    }

    /**
     *
     * @param idpartner
     */
    public SmsPartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @param idpartner
     * @param partnercode
     * @param partnername
     * @param retryNoMax
     * @param retried
     * @param phonecontact
     * @param status
     */
    public SmsPartner(String idpartner, String partnercode, String partnername, long retryNoMax, long retried, String phonecontact, String status) {
        this.idpartner = idpartner;
        this.partnercode = partnercode;
        this.partnername = partnername;
        this.retryNoMax = retryNoMax;
        this.retried = retried;
        this.phonecontact = phonecontact;
        this.status = status;
    }

    /**
     *
     * @return
     */
    public String getIdpartner() {
        return this.idpartner;
    }

    /**
     *
     * @param idpartner
     */
    public void setIdpartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @return
     */
    public String getPartnercode() {
        return this.partnercode;
    }

    /**
     *
     * @param partnercode
     */
    public void setPartnercode(String partnercode) {
        this.partnercode = partnercode;
    }

    /**
     *
     * @return
     */
    public String getPartnername() {
        return this.partnername;
    }

    /**
     *
     * @param partnername
     */
    public void setPartnername(String partnername) {
        this.partnername = partnername;
    }

    /**
     *
     * @return
     */
    public long getRetryNoMax() {
        return this.retryNoMax;
    }

    /**
     *
     * @param retryNoMax
     */
    public void setRetryNoMax(long retryNoMax) {
        this.retryNoMax = retryNoMax;
    }

    /**
     *
     * @return
     */
    public long getRetried() {
        return this.retried;
    }

    /**
     *
     * @param retried
     */
    public void setRetried(long retried) {
        this.retried = retried;
    }

    /**
     *
     * @return
     */
    public String getPhonecontact() {
        return this.phonecontact;
    }

    /**
     *
     * @param phonecontact
     */
    public void setPhonecontact(String phonecontact) {
        this.phonecontact = phonecontact;
    }

    /**
     *
     * @return
     */
    public String getStatus() {
        return status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(String status) {
        this.status = status;
    }

}
