package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * SmsSender generated by hbm2java
 */
public class SmsSender implements java.io.Serializable {

    private int idmessage;
    private String idalert;
    private String mobile;
    private String message;
    private Character messagestat;
    private String idpartner;
    private String idprovider;
    private long nbrRetry;
    private Date senddate;
    private String serviceType;
    private String serviceCode;

    /**
     * Create a new instance of SmsSender
     */
    public SmsSender() {
    }

    /**
     *
     * @param idmessage
     */
    public SmsSender(int idmessage) {
        this.idmessage = idmessage;
    }

    /**
     *
     * @param idmessage
     * @param idalert
     * @param mobile
     * @param message
     * @param messagestat
     * @param idpartner
     * @param idprovider
     * @param nbrRetry
     * @param senddate
     * @param serviceType
     * @param serviceCode
     */
    public SmsSender(int idmessage, String idalert, String mobile, String message, Character messagestat, String idpartner, String idprovider, long nbrRetry, Date senddate, String serviceType, String serviceCode) {
        this.idmessage = idmessage;
        this.idalert = idalert;
        this.mobile = mobile;
        this.message = message;
        this.messagestat = messagestat;
        this.idpartner = idpartner;
        this.idprovider = idprovider;
        this.nbrRetry = nbrRetry;
        this.senddate = senddate;
        this.serviceType = serviceType;
        this.serviceCode = serviceCode;
    }

    /**
     *
     * @return
     */
    public int getIdmessage() {
        return this.idmessage;
    }

    /**
     *
     * @param idmessage
     */
    public void setIdmessage(int idmessage) {
        this.idmessage = idmessage;
    }

    /**
     *
     * @return
     */
    public String getIdalert() {
        return this.idalert;
    }

    /**
     *
     * @param idalert
     */
    public void setIdalert(String idalert) {
        this.idalert = idalert;
    }

    /**
     *
     * @return
     */
    public String getMobile() {
        return this.mobile;
    }

    /**
     *
     * @param mobile
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     *
     * @return
     */
    public String getMessage() {
        return this.message;
    }

    /**
     *
     * @param message
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     *
     * @return
     */
    public Character getMessagestat() {
        return this.messagestat;
    }

    /**
     *
     * @param messagestat
     */
    public void setMessagestat(Character messagestat) {
        this.messagestat = messagestat;
    }

    /**
     *
     * @return
     */
    public String getIdpartner() {
        return this.idpartner;
    }

    /**
     *
     * @param idpartner
     */
    public void setIdpartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @return
     */
    public String getIdprovider() {
        return this.idprovider;
    }

    /**
     *
     * @param idprovider
     */
    public void setIdprovider(String idprovider) {
        this.idprovider = idprovider;
    }

    /**
     *
     * @return
     */
    public long getNbrRetry() {
        return this.nbrRetry;
    }

    /**
     *
     * @param nbrRetry
     */
    public void setNbrRetry(long nbrRetry) {
        this.nbrRetry = nbrRetry;
    }

    /**
     *
     * @return
     */
    public Date getSenddate() {
        return this.senddate;
    }

    /**
     *
     * @param senddate
     */
    public void setSenddate(Date senddate) {
        this.senddate = senddate;
    }

    /**
     *
     * @return
     */
    public String getServiceType() {
        return this.serviceType;
    }

    /**
     *
     * @param serviceType
     */
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }

    /**
     *
     * @return
     */
    public String getServiceCode() {
        return this.serviceCode;
    }

    /**
     *
     * @param serviceCode
     */
    public void setServiceCode(String serviceCode) {
        this.serviceCode = serviceCode;
    }

}
