package scb.com.vn.dbi.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 * VwAutoregToPay generated by hbm2java
 */
public class VwAutoregToPay implements java.io.Serializable {

    private VwAutoregToPayId id;
    private Boolean scheduletype;
    private String daysinmonth;
    private Character havesms;
    private String mobile;
    private BigDecimal numattempFail;
    private String sentsms;
    private Date dateFail;
    private String accnofcubs;
    private String branchcode;
    private String paymenttype;
    
    /**
     * Create a new instance of VwAutoregToPay
     */
    public VwAutoregToPay() {
    }

    /**
     *
     * @param id
     * @param scheduletype
     * @param daysinmonth
     * @param havesms
     * @param mobile
     * @param numattempFail
     * @param sentsms
     * @param dateFail
     * @param accnofcubs
     * @param branchcode
     */
    public VwAutoregToPay(VwAutoregToPayId id, Boolean scheduletype, String daysinmonth, Character havesms, String mobile, BigDecimal numattempFail, String sentsms, Date dateFail, String accnofcubs, String branchcode) {
        this.id = id;
        this.scheduletype = scheduletype;
        this.daysinmonth = daysinmonth;
        this.havesms = havesms;
        this.mobile = mobile;
        this.numattempFail = numattempFail;
        this.sentsms = sentsms;
        this.dateFail = dateFail;
        this.accnofcubs = accnofcubs;
        this.branchcode = branchcode;

    }
    
     public VwAutoregToPay(VwAutoregToPayId id, Boolean scheduletype, String daysinmonth, Character havesms, String mobile, BigDecimal numattempFail, String sentsms, Date dateFail, String accnofcubs, String branchcode, String paymenttype) {
        this.id = id;
        this.scheduletype = scheduletype;
        this.daysinmonth = daysinmonth;
        this.havesms = havesms;
        this.mobile = mobile;
        this.numattempFail = numattempFail;
        this.sentsms = sentsms;
        this.dateFail = dateFail;
        this.accnofcubs = accnofcubs;
        this.branchcode = branchcode;
        this.paymenttype = paymenttype;
    }
    /**
     *
     * @return
     */
    public VwAutoregToPayId getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(VwAutoregToPayId id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public Boolean getScheduletype() {
        return this.scheduletype;
    }

    /**
     *
     * @param scheduletype
     */
    public void setScheduletype(Boolean scheduletype) {
        this.scheduletype = scheduletype;
    }

    /**
     *
     * @return
     */
    public String getDaysinmonth() {
        return this.daysinmonth;
    }

    /**
     *
     * @param daysinmonth
     */
    public void setDaysinmonth(String daysinmonth) {
        this.daysinmonth = daysinmonth;
    }

    /**
     *
     * @return
     */
    public Character getHavesms() {
        return this.havesms;
    }

    /**
     *
     * @param havesms
     */
    public void setHavesms(Character havesms) {
        this.havesms = havesms;
    }

    /**
     *
     * @return
     */
    public String getMobile() {
        return this.mobile;
    }

    /**
     *
     * @param mobile
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     *
     * @return
     */
    public BigDecimal getNumattempFail() {
        return this.numattempFail;
    }

    /**
     *
     * @param numattempFail
     */
    public void setNumattempFail(BigDecimal numattempFail) {
        this.numattempFail = numattempFail;
    }

    /**
     *
     * @return
     */
    public String getSentsms() {
        return this.sentsms;
    }

    /**
     *
     * @param sentsms
     */
    public void setSentsms(String sentsms) {
        this.sentsms = sentsms;
    }

    /**
     *
     * @return
     */
    public Date getDateFail() {
        return this.dateFail;
    }

    /**
     *
     * @param dateFail
     */
    public void setDateFail(Date dateFail) {
        this.dateFail = dateFail;
    }

    /**
     *
     * @return
     */
    public String getAccnofcubs() {
        return this.accnofcubs;
    }

    /**
     *
     * @param accnofcubs
     */
    public void setAccnofcubs(String accnofcubs) {
        this.accnofcubs = accnofcubs;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof VwAutoregToPay)) {
            return false;
        }
        VwAutoregToPay castOther = (VwAutoregToPay) other;

        return ((this.getId() == castOther.getId()) || (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
                && ((this.getScheduletype().equals(castOther.getScheduletype())) || (this.getScheduletype() != null && castOther.getScheduletype() != null && this.getScheduletype().equals(castOther.getScheduletype())))
                && ((this.getDaysinmonth().equals(castOther.getDaysinmonth())) || (this.getDaysinmonth() != null && castOther.getDaysinmonth() != null && this.getDaysinmonth().equals(castOther.getDaysinmonth())))
                && ((this.getHavesms().equals(castOther.getHavesms())) || (this.getHavesms() != null && castOther.getHavesms() != null && this.getHavesms().equals(castOther.getHavesms())))
                && ((this.getMobile().equals(castOther.getMobile())) || (this.getMobile() != null && castOther.getMobile() != null && this.getMobile().equals(castOther.getMobile())))
                && ((this.getNumattempFail() == castOther.getNumattempFail()) || (this.getNumattempFail() != null && castOther.getNumattempFail() != null && this.getNumattempFail().equals(castOther.getNumattempFail())))
                && ((this.getSentsms().equals(castOther.getSentsms())) || (this.getSentsms() != null && castOther.getSentsms() != null && this.getSentsms().equals(castOther.getSentsms())))
                && ((this.getDateFail().equals(castOther.getDateFail())) || (this.getDateFail() != null && castOther.getDateFail() != null && this.getDateFail().equals(castOther.getDateFail())))
                && ((this.getAccnofcubs().equals(castOther.getAccnofcubs())) || (this.getAccnofcubs() != null && castOther.getAccnofcubs() != null && this.getAccnofcubs().equals(castOther.getAccnofcubs())))
                && ((this.getBranchcode().equals(castOther.getBranchcode())) || (this.getBranchcode() != null && castOther.getBranchcode() != null && this.getAccnofcubs().equals(castOther.getBranchcode())));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
        result = 37 * result + (getScheduletype() == null ? 0 : this.getScheduletype().hashCode());
        result = 37 * result + (getDaysinmonth() == null ? 0 : this.getDaysinmonth().hashCode());
        result = 37 * result + (getHavesms() == null ? 0 : this.getHavesms().hashCode());
        result = 37 * result + (getMobile() == null ? 0 : this.getMobile().hashCode());
        result = 37 * result + (getNumattempFail() == null ? 0 : this.getNumattempFail().hashCode());
        result = 37 * result + (getSentsms() == null ? 0 : this.getSentsms().hashCode());
        result = 37 * result + (getDateFail() == null ? 0 : this.getDateFail().hashCode());
        result = 37 * result + (getAccnofcubs() == null ? 0 : this.getAccnofcubs().hashCode());
        result = 37 * result + (getBranchcode() == null ? 0 : this.getBranchcode().hashCode());

        return result;
    }

    /**
     * @return the branchcode
     */
    public String getBranchcode() {
        return branchcode;
    }

    /**
     * @param branchcode the branchcode to set
     */
    public void setBranchcode(String branchcode) {
        this.branchcode = branchcode;
    }

    public String getPaymenttype() {
        return paymenttype;
    }

    public void setPaymenttype(String paymenttype) {
        this.paymenttype = paymenttype;
    }
}
