package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * VwAutoReg generated by hbm2java
 */
public class VwAutoReg implements java.io.Serializable {

    private int id;
    private String idservicetype;
    private String idprovider;
    private String servicetypename;
    private String providername;
    private String customercode;
    private String dataxml;
    private Character status;
    private String mobile;
    private String custAccCif;
    private String custAccNo;
    private String custAccName;
    private String custAccAddress;
    private String custAccIdcard;
    private String custAccIdcardLoc;
    private String custAccIdcardDob;
    private Date validdate;
    private Date expiredate;
    private boolean scheduletype;
    private String daysinmonth;
    private String idteller;
    private String idchanneluserTeller;
    private Date insdateTeller;
    private String idchecker;
    private String idchanneluserChecker;
    private Date insdateChecker;
    private String description;
    private Character isapproved;
    private String branchCodeTeller;
    private String branchNameTeller;

    /**
     * Create a new instance of VwAutoReg
     */
    public VwAutoReg() {
    }

    /**
     *
     * @param id
     * @param idservicetype
     * @param idprovider
     * @param customercode
     * @param status
     * @param custAccCif
     * @param custAccNo
     * @param custAccName
     * @param validdate
     * @param scheduletype
     * @param idteller
     * @param idchanneluserTeller
     * @param insdateTeller
     * @param branchCodeTeller
     */
    public VwAutoReg(int id, String idservicetype, String idprovider, String customercode, Character status, String custAccCif, String custAccNo, String custAccName, Date validdate, boolean scheduletype, String idteller, String idchanneluserTeller, Date insdateTeller, String branchCodeTeller) {
        this.id = id;
        this.idservicetype = idservicetype;
        this.idprovider = idprovider;
        this.customercode = customercode;
        this.status = status;
        this.custAccCif = custAccCif;
        this.custAccNo = custAccNo;
        this.custAccName = custAccName;
        this.validdate = validdate;
        this.scheduletype = scheduletype;
        this.idteller = idteller;
        this.idchanneluserTeller = idchanneluserTeller;
        this.insdateTeller = insdateTeller;
        this.branchCodeTeller = branchCodeTeller;
    }

    /**
     *
     * @param id
     * @param idservicetype
     * @param idprovider
     * @param customercode
     * @param dataxml
     * @param status
     * @param mobile
     * @param custAccCif
     * @param custAccNo
     * @param custAccName
     * @param custAccAddress
     * @param custAccIdcard
     * @param custAccIdcardLoc
     * @param custAccIdcardDob
     * @param validdate
     * @param expiredate
     * @param scheduletype
     * @param daysinmonth
     * @param idteller
     * @param idchanneluserTeller
     * @param insdateTeller
     * @param idchecker
     * @param idchanneluserChecker
     * @param insdateChecker
     * @param description
     * @param isapproved
     * @param branchCodeTeller
     * @param branchNameTeller
     */
    public VwAutoReg(int id, String idservicetype, String idprovider, String customercode, String dataxml, Character status, String mobile, String custAccCif, String custAccNo, String custAccName, String custAccAddress, String custAccIdcard, String custAccIdcardLoc, String custAccIdcardDob, Date validdate, Date expiredate, boolean scheduletype, String daysinmonth, String idteller, String idchanneluserTeller, Date insdateTeller, String idchecker, String idchanneluserChecker, Date insdateChecker, String description, Character isapproved, String branchCodeTeller, String branchNameTeller) {
        this.id = id;
        this.idservicetype = idservicetype;
        this.idprovider = idprovider;
        this.customercode = customercode;
        this.dataxml = dataxml;
        this.status = status;
        this.mobile = mobile;
        this.custAccCif = custAccCif;
        this.custAccNo = custAccNo;
        this.custAccName = custAccName;
        this.custAccAddress = custAccAddress;
        this.custAccIdcard = custAccIdcard;
        this.custAccIdcardLoc = custAccIdcardLoc;
        this.custAccIdcardDob = custAccIdcardDob;
        this.validdate = validdate;
        this.expiredate = expiredate;
        this.scheduletype = scheduletype;
        this.daysinmonth = daysinmonth;
        this.idteller = idteller;
        this.idchanneluserTeller = idchanneluserTeller;
        this.insdateTeller = insdateTeller;
        this.idchecker = idchecker;
        this.idchanneluserChecker = idchanneluserChecker;
        this.insdateChecker = insdateChecker;
        this.description = description;
        this.isapproved = isapproved;
        this.branchCodeTeller = branchCodeTeller;
        this.branchNameTeller = branchNameTeller;
    }

    /**
     *
     * @return
     */
    public int getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getIdservicetype() {
        return this.idservicetype;
    }

    /**
     *
     * @param idservicetype
     */
    public void setIdservicetype(String idservicetype) {
        this.idservicetype = idservicetype;
    }

    /**
     *
     * @return
     */
    public String getIdprovider() {
        return this.idprovider;
    }

    /**
     *
     * @param idprovider
     */
    public void setIdprovider(String idprovider) {
        this.idprovider = idprovider;
    }

    /**
     *
     * @return
     */
    public String getCustomercode() {
        return this.customercode;
    }

    /**
     *
     * @param customercode
     */
    public void setCustomercode(String customercode) {
        this.customercode = customercode;
    }

    /**
     *
     * @return
     */
    public String getDataxml() {
        return this.dataxml;
    }

    /**
     *
     * @param dataxml
     */
    public void setDataxml(String dataxml) {
        this.dataxml = dataxml;
    }

    /**
     *
     * @return
     */
    public Character getStatus() {
        return this.status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(Character status) {
        this.status = status;
    }

    /**
     *
     * @return
     */
    public String getMobile() {
        return this.mobile;
    }

    /**
     *
     * @param mobile
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     *
     * @return
     */
    public String getCustAccCif() {
        return this.custAccCif;
    }

    /**
     *
     * @param custAccCif
     */
    public void setCustAccCif(String custAccCif) {
        this.custAccCif = custAccCif;
    }

    /**
     *
     * @return
     */
    public String getCustAccNo() {
        return this.custAccNo;
    }

    /**
     *
     * @param custAccNo
     */
    public void setCustAccNo(String custAccNo) {
        this.custAccNo = custAccNo;
    }

    /**
     *
     * @return
     */
    public String getCustAccName() {
        return this.custAccName;
    }

    /**
     *
     * @param custAccName
     */
    public void setCustAccName(String custAccName) {
        this.custAccName = custAccName;
    }

    /**
     *
     * @return
     */
    public String getCustAccAddress() {
        return this.custAccAddress;
    }

    /**
     *
     * @param custAccAddress
     */
    public void setCustAccAddress(String custAccAddress) {
        this.custAccAddress = custAccAddress;
    }

    /**
     *
     * @return
     */
    public String getCustAccIdcard() {
        return this.custAccIdcard;
    }

    /**
     *
     * @param custAccIdcard
     */
    public void setCustAccIdcard(String custAccIdcard) {
        this.custAccIdcard = custAccIdcard;
    }

    /**
     *
     * @return
     */
    public String getCustAccIdcardLoc() {
        return this.custAccIdcardLoc;
    }

    /**
     *
     * @param custAccIdcardLoc
     */
    public void setCustAccIdcardLoc(String custAccIdcardLoc) {
        this.custAccIdcardLoc = custAccIdcardLoc;
    }

    /**
     *
     * @return
     */
    public String getCustAccIdcardDob() {
        return this.custAccIdcardDob;
    }

    /**
     *
     * @param custAccIdcardDob
     */
    public void setCustAccIdcardDob(String custAccIdcardDob) {
        this.custAccIdcardDob = custAccIdcardDob;
    }

    /**
     *
     * @return
     */
    public Date getValiddate() {
        return this.validdate;
    }

    /**
     *
     * @param validdate
     */
    public void setValiddate(Date validdate) {
        this.validdate = validdate;
    }

    /**
     *
     * @return
     */
    public Date getExpiredate() {
        return this.expiredate;
    }

    /**
     *
     * @param expiredate
     */
    public void setExpiredate(Date expiredate) {
        this.expiredate = expiredate;
    }

    /**
     *
     * @return
     */
    public boolean isScheduletype() {
        return this.scheduletype;
    }

    /**
     *
     * @param scheduletype
     */
    public void setScheduletype(boolean scheduletype) {
        this.scheduletype = scheduletype;
    }

    /**
     *
     * @return
     */
    public String getDaysinmonth() {
        return this.daysinmonth;
    }

    /**
     *
     * @param daysinmonth
     */
    public void setDaysinmonth(String daysinmonth) {
        this.daysinmonth = daysinmonth;
    }

    /**
     *
     * @return
     */
    public String getIdteller() {
        return this.idteller;
    }

    /**
     *
     * @param idteller
     */
    public void setIdteller(String idteller) {
        this.idteller = idteller;
    }

    /**
     *
     * @return
     */
    public String getIdchanneluserTeller() {
        return this.idchanneluserTeller;
    }

    /**
     *
     * @param idchanneluserTeller
     */
    public void setIdchanneluserTeller(String idchanneluserTeller) {
        this.idchanneluserTeller = idchanneluserTeller;
    }

    /**
     *
     * @return
     */
    public Date getInsdateTeller() {
        return this.insdateTeller;
    }

    /**
     *
     * @param insdateTeller
     */
    public void setInsdateTeller(Date insdateTeller) {
        this.insdateTeller = insdateTeller;
    }

    /**
     *
     * @return
     */
    public String getIdchecker() {
        return this.idchecker;
    }

    /**
     *
     * @param idchecker
     */
    public void setIdchecker(String idchecker) {
        this.idchecker = idchecker;
    }

    /**
     *
     * @return
     */
    public String getIdchanneluserChecker() {
        return this.idchanneluserChecker;
    }

    /**
     *
     * @param idchanneluserChecker
     */
    public void setIdchanneluserChecker(String idchanneluserChecker) {
        this.idchanneluserChecker = idchanneluserChecker;
    }

    /**
     *
     * @return
     */
    public Date getInsdateChecker() {
        return this.insdateChecker;
    }

    /**
     *
     * @param insdateChecker
     */
    public void setInsdateChecker(Date insdateChecker) {
        this.insdateChecker = insdateChecker;
    }

    /**
     *
     * @return
     */
    public String getDescription() {
        return this.description;
    }

    /**
     *
     * @param description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     *
     * @return
     */
    public Character getIsapproved() {
        return this.isapproved;
    }

    /**
     *
     * @param isapproved
     */
    public void setIsapproved(Character isapproved) {
        this.isapproved = isapproved;
    }

    /**
     *
     * @return
     */
    public String getBranchCodeTeller() {
        return this.branchCodeTeller;
    }

    /**
     *
     * @param branchCodeTeller
     */
    public void setBranchCodeTeller(String branchCodeTeller) {
        this.branchCodeTeller = branchCodeTeller;
    }

    /**
     *
     * @return
     */
    public String getBranchNameTeller() {
        return this.branchNameTeller;
    }

    /**
     *
     * @param branchNameTeller
     */
    public void setBranchNameTeller(String branchNameTeller) {
        this.branchNameTeller = branchNameTeller;
    }

    /**
     *
     * @return
     */
    public String getServicetypename() {
        return servicetypename;
    }

    /**
     *
     * @param servicetypename
     */
    public void setServicetypename(String servicetypename) {
        this.servicetypename = servicetypename;
    }

    /**
     *
     * @return
     */
    public String getProvidername() {
        return providername;
    }

    /**
     *
     * @param providername
     */
    public void setProvidername(String providername) {
        this.providername = providername;
    }
}
