package scb.com.vn.dbi.dto;

/**
 * VwMbCustomer generated by hbm2java
 */
public class VwMbCustomer implements java.io.Serializable {

    private String customerNo;
    private String cusName;
    private String cusAddr;
    private String cusTel;

    /**
     * Create a new instance of VwMbCustomer
     */
    public VwMbCustomer() {
    }

    /**
     *
     * @param customerNo
     * @param cusName
     */
    public VwMbCustomer(String customerNo, String cusName) {
        this.customerNo = customerNo;
        this.cusName = cusName;
    }

    /**
     *
     * @param customerNo
     * @param cusName
     * @param cusAddr
     * @param cusTel
     */
    public VwMbCustomer(String customerNo, String cusName, String cusAddr, String cusTel) {
        this.customerNo = customerNo;
        this.cusName = cusName;
        this.cusAddr = cusAddr;
        this.cusTel = cusTel;
    }

    /**
     *
     * @return
     */
    public String getCustomerNo() {
        return this.customerNo;
    }

    /**
     *
     * @param customerNo
     */
    public void setCustomerNo(String customerNo) {
        this.customerNo = customerNo;
    }

    /**
     *
     * @return
     */
    public String getCusName() {
        return this.cusName;
    }

    /**
     *
     * @param cusName
     */
    public void setCusName(String cusName) {
        this.cusName = cusName;
    }

    /**
     *
     * @return
     */
    public String getCusAddr() {
        return this.cusAddr;
    }

    /**
     *
     * @param cusAddr
     */
    public void setCusAddr(String cusAddr) {
        this.cusAddr = cusAddr;
    }

    /**
     *
     * @return
     */
    public String getCusTel() {
        return this.cusTel;
    }

    /**
     *
     * @param cusTel
     */
    public void setCusTel(String cusTel) {
        this.cusTel = cusTel;
    }

}
