package scb.com.vn.dbi.dto;

import java.math.BigDecimal;
import java.util.Date;

/**
 * VwMstchanneluser generated by hbm2java
 */
public class VwMstchanneluser implements java.io.Serializable {

    private String idEntity;
    private String iduser;
    private String idchanneluser;
    private String idchannel;
    private String password;
    private char lockflag;
    private Date datlastsucclogin;
    private Date datlastfaillogin;
    private BigDecimal nbrfailedlogins;
    private BigDecimal nbrlogins;
    private String defaulttxn;
    private Date datsoftlastfail;
    private Character flagforcechangepwd;
    private Character isavcrequired;
    private String activationcode;
    private Date datavcgeneration;
    private BigDecimal failedattemptcnt;
    private Character flagforcechangetxnpwd;
    private String deactivationperiod;

    /**
     * Create a new instance of VwMstchanneluser
     */
    public VwMstchanneluser() {
    }

    /**
     *
     * @return
     */
    public String getIdEntity() {
        return this.idEntity;
    }

    /**
     *
     * @param idEntity
     */
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    /**
     *
     * @return
     */
    public String getIduser() {
        return this.iduser;
    }

    /**
     *
     * @param iduser
     */
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    /**
     *
     * @return
     */
    public String getIdchanneluser() {
        return this.idchanneluser;
    }

    /**
     *
     * @param idchanneluser
     */
    public void setIdchanneluser(String idchanneluser) {
        this.idchanneluser = idchanneluser;
    }

    /**
     *
     * @return
     */
    public String getIdchannel() {
        return this.idchannel;
    }

    /**
     *
     * @param idchannel
     */
    public void setIdchannel(String idchannel) {
        this.idchannel = idchannel;
    }

    /**
     *
     * @return
     */
    public String getPassword() {
        return this.password;
    }

    /**
     *
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     *
     * @return
     */
    public char getLockflag() {
        return this.lockflag;
    }

    /**
     *
     * @param lockflag
     */
    public void setLockflag(char lockflag) {
        this.lockflag = lockflag;
    }

    /**
     *
     * @return
     */
    public Date getDatlastsucclogin() {
        return this.datlastsucclogin;
    }

    /**
     *
     * @param datlastsucclogin
     */
    public void setDatlastsucclogin(Date datlastsucclogin) {
        this.datlastsucclogin = datlastsucclogin;
    }

    /**
     *
     * @return
     */
    public Date getDatlastfaillogin() {
        return this.datlastfaillogin;
    }

    /**
     *
     * @param datlastfaillogin
     */
    public void setDatlastfaillogin(Date datlastfaillogin) {
        this.datlastfaillogin = datlastfaillogin;
    }

    /**
     *
     * @return
     */
    public BigDecimal getNbrfailedlogins() {
        return this.nbrfailedlogins;
    }

    /**
     *
     * @param nbrfailedlogins
     */
    public void setNbrfailedlogins(BigDecimal nbrfailedlogins) {
        this.nbrfailedlogins = nbrfailedlogins;
    }

    /**
     *
     * @return
     */
    public BigDecimal getNbrlogins() {
        return this.nbrlogins;
    }

    /**
     *
     * @param nbrlogins
     */
    public void setNbrlogins(BigDecimal nbrlogins) {
        this.nbrlogins = nbrlogins;
    }

    /**
     *
     * @return
     */
    public String getDefaulttxn() {
        return this.defaulttxn;
    }

    /**
     *
     * @param defaulttxn
     */
    public void setDefaulttxn(String defaulttxn) {
        this.defaulttxn = defaulttxn;
    }

    /**
     *
     * @return
     */
    public Date getDatsoftlastfail() {
        return this.datsoftlastfail;
    }

    /**
     *
     * @param datsoftlastfail
     */
    public void setDatsoftlastfail(Date datsoftlastfail) {
        this.datsoftlastfail = datsoftlastfail;
    }

    /**
     *
     * @return
     */
    public Character getFlagforcechangepwd() {
        return this.flagforcechangepwd;
    }

    /**
     *
     * @param flagforcechangepwd
     */
    public void setFlagforcechangepwd(Character flagforcechangepwd) {
        this.flagforcechangepwd = flagforcechangepwd;
    }

    /**
     *
     * @return
     */
    public Character getIsavcrequired() {
        return this.isavcrequired;
    }

    /**
     *
     * @param isavcrequired
     */
    public void setIsavcrequired(Character isavcrequired) {
        this.isavcrequired = isavcrequired;
    }

    /**
     *
     * @return
     */
    public String getActivationcode() {
        return this.activationcode;
    }

    /**
     *
     * @param activationcode
     */
    public void setActivationcode(String activationcode) {
        this.activationcode = activationcode;
    }

    /**
     *
     * @return
     */
    public Date getDatavcgeneration() {
        return this.datavcgeneration;
    }

    /**
     *
     * @param datavcgeneration
     */
    public void setDatavcgeneration(Date datavcgeneration) {
        this.datavcgeneration = datavcgeneration;
    }

    /**
     *
     * @return
     */
    public BigDecimal getFailedattemptcnt() {
        return this.failedattemptcnt;
    }

    /**
     *
     * @param failedattemptcnt
     */
    public void setFailedattemptcnt(BigDecimal failedattemptcnt) {
        this.failedattemptcnt = failedattemptcnt;
    }

    /**
     *
     * @return
     */
    public Character getFlagforcechangetxnpwd() {
        return this.flagforcechangetxnpwd;
    }

    /**
     *
     * @param flagforcechangetxnpwd
     */
    public void setFlagforcechangetxnpwd(Character flagforcechangetxnpwd) {
        this.flagforcechangetxnpwd = flagforcechangetxnpwd;
    }

    /**
     *
     * @return
     */
    public String getDeactivationperiod() {
        return this.deactivationperiod;
    }

    /**
     *
     * @param deactivationperiod
     */
    public void setDeactivationperiod(String deactivationperiod) {
        this.deactivationperiod = deactivationperiod;
    }

}
