package scb.com.vn.dbi.dto;

import java.math.BigDecimal;

/**
 * Tmppartner generated by hbm2java
 */
public class VwPartner implements java.io.Serializable {

    private VwPartnerId id;
    private String accnofcubs;
    private String accnopartner;
    private BigDecimal priority;
    private String providername;

    /**
     * Create a new instance of VwPartner
     */
    public VwPartner() {
    }

    /**
     *
     * @param id
     */
    public VwPartner(VwPartnerId id) {
        this.id = id;
    }

    /**
     *
     * @param id
     * @param accnofcubs
     * @param accnopartner
     * @param priority
     * @param providername
     */
    public VwPartner(VwPartnerId id, String accnofcubs, String accnopartner, BigDecimal priority, String providername) {
        this.id = id;
        this.accnofcubs = accnofcubs;
        this.accnopartner = accnopartner;
        this.priority = priority;
        this.providername = providername;
    }

    /**
     *
     * @return
     */
    public VwPartnerId getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(VwPartnerId id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getAccnofcubs() {
        return this.accnofcubs;
    }

    /**
     *
     * @param accnofcubs
     */
    public void setAccnofcubs(String accnofcubs) {
        this.accnofcubs = accnofcubs;
    }

    /**
     *
     * @return
     */
    public String getAccnopartner() {
        return this.accnopartner;
    }

    /**
     *
     * @param accnopartner
     */
    public void setAccnopartner(String accnopartner) {
        this.accnopartner = accnopartner;
    }

    /**
     *
     * @return
     */
    public BigDecimal getPriority() {
        return this.priority;
    }

    /**
     *
     * @param priority
     */
    public void setPriority(BigDecimal priority) {
        this.priority = priority;
    }

    /**
     *
     * @return
     */
    public String getProvidername() {
        return this.providername;
    }

    /**
     *
     * @param providername
     */
    public void setProvidername(String providername) {
        this.providername = providername;
    }

}
