package scb.com.vn.dbi.dto;

/**
 * VwPartnerId generated by hbm2java
 */
public class VwPartnerId implements java.io.Serializable {

    private String idpartner;
    private String idservicetype;
    private String idprovider;

    /**
     * Create a new instance of VwPartnerId
     */
    public VwPartnerId() {
    }

    /**
     *
     * @param idpartner
     * @param idservicetype
     * @param idprovider
     */
    public VwPartnerId(String idpartner, String idservicetype, String idprovider) {
        this.idpartner = idpartner;
        this.idservicetype = idservicetype;
        this.idprovider = idprovider;
    }

    /**
     *
     * @return
     */
    public String getIdpartner() {
        return this.idpartner;
    }

    /**
     *
     * @param idpartner
     */
    public void setIdpartner(String idpartner) {
        this.idpartner = idpartner;
    }

    /**
     *
     * @return
     */
    public String getIdservicetype() {
        return this.idservicetype;
    }

    /**
     *
     * @param idservicetype
     */
    public void setIdservicetype(String idservicetype) {
        this.idservicetype = idservicetype;
    }

    /**
     *
     * @return
     */
    public String getIdprovider() {
        return this.idprovider;
    }

    /**
     *
     * @param idprovider
     */
    public void setIdprovider(String idprovider) {
        this.idprovider = idprovider;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof VwPartnerId)) {
            return false;
        }
        VwPartnerId castOther = (VwPartnerId) other;

        return ((this.getIdpartner().equals(castOther.getIdpartner())) || (this.getIdpartner() != null && castOther.getIdpartner() != null && this.getIdpartner().equals(castOther.getIdpartner())))
                && ((this.getIdservicetype().equals(castOther.getIdservicetype())) || (this.getIdservicetype() != null && castOther.getIdservicetype() != null && this.getIdservicetype().equals(castOther.getIdservicetype())))
                && ((this.getIdprovider().equals(castOther.getIdprovider())) || (this.getIdprovider() != null && castOther.getIdprovider() != null && this.getIdprovider().equals(castOther.getIdprovider())));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getIdpartner() == null ? 0 : this.getIdpartner().hashCode());
        result = 37 * result + (getIdservicetype() == null ? 0 : this.getIdservicetype().hashCode());
        result = 37 * result + (getIdprovider() == null ? 0 : this.getIdprovider().hashCode());
        return result;
    }

}
