package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * VwSmsThuphiKHCN2 generated by hbm2java
 */
public class VwSmsThuphiKHCN2 implements java.io.Serializable {

    private String id;
    private String custno;
    private String custname;
    private String acctno;
    private String phoneno;
    private Integer retry;
    private Character status;
    private String note;
    private Integer nophi;
    private Character sendsms;
    private String thangnam;
    private Date paydateFcubs;
    private Date datefail;
    private Long feeamount;
    private String refFcubs;
    private String branchCode;
    private String thangnamretry;
    private Date lockdate;
    private Character lockstatus;

    /**
     * Create a new instance of VwSmsThuphiKHCN2
     */
    public VwSmsThuphiKHCN2() {
    }

    /**
     *
     * @param id
     */
    public VwSmsThuphiKHCN2(String id) {
        this.id = id;
    }

    /**
     *
     * @param id
     * @param custno
     * @param custname
     * @param acctno
     * @param phoneno
     * @param retry
     * @param status
     * @param note
     * @param nophi
     * @param sendsms
     * @param thangnam
     * @param paydateFcubs
     * @param datefail
     * @param feeamount
     * @param refFcubs
     * @param branchCode
     * @param thangnamretry
     * @param lockdate
     * @param lockstatus
     */
    public VwSmsThuphiKHCN2(String id, String custno, String custname, String acctno, String phoneno, Integer retry, Character status, String note, Integer nophi, Character sendsms, String thangnam, Date paydateFcubs, Date datefail, Long feeamount, String refFcubs, String branchCode, String thangnamretry, Date lockdate, Character lockstatus) {
        this.id = id;
        this.custno = custno;
        this.custname = custname;
        this.acctno = acctno;
        this.phoneno = phoneno;
        this.retry = retry;
        this.status = status;
        this.note = note;
        this.nophi = nophi;
        this.sendsms = sendsms;
        this.thangnam = thangnam;
        this.paydateFcubs = paydateFcubs;
        this.datefail = datefail;
        this.feeamount = feeamount;
        this.refFcubs = refFcubs;
        this.branchCode = branchCode;
        this.thangnamretry = thangnamretry;
        this.lockdate = lockdate;
        this.lockstatus = lockstatus;
    }

    /**
     *
     * @return
     */
    public String getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getCustno() {
        return this.custno;
    }

    /**
     *
     * @param custno
     */
    public void setCustno(String custno) {
        this.custno = custno;
    }

    /**
     *
     * @return
     */
    public String getCustname() {
        return this.custname;
    }

    /**
     *
     * @param custname
     */
    public void setCustname(String custname) {
        this.custname = custname;
    }

    /**
     *
     * @return
     */
    public String getAcctno() {
        return this.acctno;
    }

    /**
     *
     * @param acctno
     */
    public void setAcctno(String acctno) {
        this.acctno = acctno;
    }

    /**
     *
     * @return
     */
    public String getPhoneno() {
        return this.phoneno;
    }

    /**
     *
     * @param phoneno
     */
    public void setPhoneno(String phoneno) {
        this.phoneno = phoneno;
    }

    /**
     *
     * @return
     */
    public Integer getRetry() {
        return this.retry;
    }

    /**
     *
     * @param retry
     */
    public void setRetry(Integer retry) {
        this.retry = retry;
    }

    /**
     *
     * @return
     */
    public Character getStatus() {
        return this.status;
    }

    /**
     *
     * @param status
     */
    public void setStatus(Character status) {
        this.status = status;
    }

    /**
     *
     * @return
     */
    public String getNote() {
        return this.note;
    }

    /**
     *
     * @param note
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     *
     * @return
     */
    public Integer getNophi() {
        return this.nophi;
    }

    /**
     *
     * @param nophi
     */
    public void setNophi(Integer nophi) {
        this.nophi = nophi;
    }

    /**
     *
     * @return
     */
    public Character getSendsms() {
        return this.sendsms;
    }

    /**
     *
     * @param sendsms
     */
    public void setSendsms(Character sendsms) {
        this.sendsms = sendsms;
    }

    /**
     *
     * @return
     */
    public String getThangnam() {
        return this.thangnam;
    }

    /**
     *
     * @param thangnam
     */
    public void setThangnam(String thangnam) {
        this.thangnam = thangnam;
    }

    /**
     *
     * @return
     */
    public Date getPaydateFcubs() {
        return this.paydateFcubs;
    }

    /**
     *
     * @param paydateFcubs
     */
    public void setPaydateFcubs(Date paydateFcubs) {
        this.paydateFcubs = paydateFcubs;
    }

    /**
     *
     * @return
     */
    public Date getDatefail() {
        return this.datefail;
    }

    /**
     *
     * @param datefail
     */
    public void setDatefail(Date datefail) {
        this.datefail = datefail;
    }

    /**
     *
     * @return
     */
    public Long getFeeamount() {
        return this.feeamount;
    }

    /**
     *
     * @param feeamount
     */
    public void setFeeamount(Long feeamount) {
        this.feeamount = feeamount;
    }

    /**
     *
     * @return
     */
    public String getRefFcubs() {
        return this.refFcubs;
    }

    /**
     *
     * @param refFcubs
     */
    public void setRefFcubs(String refFcubs) {
        this.refFcubs = refFcubs;
    }

    /**
     *
     * @return
     */
    public String getBranchCode() {
        return this.branchCode;
    }

    /**
     *
     * @param branchCode
     */
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    /**
     *
     * @return
     */
    public String getThangnamretry() {
        return this.thangnamretry;
    }

    /**
     *
     * @param thangnamretry
     */
    public void setThangnamretry(String thangnamretry) {
        this.thangnamretry = thangnamretry;
    }

    /**
     *
     * @return
     */
    public Date getLockdate() {
        return this.lockdate;
    }

    /**
     *
     * @param lockdate
     */
    public void setLockdate(Date lockdate) {
        this.lockdate = lockdate;
    }

    /**
     *
     * @return
     */
    public Character getLockstatus() {
        return this.lockstatus;
    }

    /**
     *
     * @param lockstatus
     */
    public void setLockstatus(Character lockstatus) {
        this.lockstatus = lockstatus;
    }

}
