package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * VwUserbranch generated by hbm2java
 */
public class VwUserbranch implements java.io.Serializable {

    private String idEntity;
    private String typeuser;
    private String iduser;
    private String nicname;
    private String salution;
    private String firstname;
    private String lastname;
    private String address1;
    private String address2;
    private String city;
    private String state;
    private String country;
    private String zip;
    private Date dob;
    private String email;
    private char activeflag;
    private String phonenumber;
    private String faxnbr;
    private char authreqd;
    private Date datcreated;
    private String makerid;
    private String branchCode;
    private String branchName;

    /**
     * Create a new instance of VwUserbranch
     */
    public VwUserbranch() {
    }

    /**
     *
     * @param idEntity
     * @param typeuser
     * @param iduser
     * @param firstname
     * @param activeflag
     * @param authreqd
     * @param branchCode
     */
    public VwUserbranch(String idEntity, String typeuser, String iduser, String firstname, char activeflag, char authreqd, String branchCode) {
        this.idEntity = idEntity;
        this.typeuser = typeuser;
        this.iduser = iduser;
        this.firstname = firstname;
        this.activeflag = activeflag;
        this.authreqd = authreqd;
        this.branchCode = branchCode;
    }

    /**
     *
     * @param idEntity
     * @param typeuser
     * @param iduser
     * @param nicname
     * @param salution
     * @param firstname
     * @param lastname
     * @param address1
     * @param address2
     * @param city
     * @param state
     * @param country
     * @param zip
     * @param dob
     * @param email
     * @param activeflag
     * @param phonenumber
     * @param faxnbr
     * @param authreqd
     * @param datcreated
     * @param makerid
     * @param branchCode
     * @param branchName
     */
    public VwUserbranch(String idEntity, String typeuser, String iduser, String nicname, String salution, String firstname, String lastname, String address1, String address2, String city, String state, String country, String zip, Date dob, String email, char activeflag, String phonenumber, String faxnbr, char authreqd, Date datcreated, String makerid, String branchCode, String branchName) {
        this.idEntity = idEntity;
        this.typeuser = typeuser;
        this.iduser = iduser;
        this.nicname = nicname;
        this.salution = salution;
        this.firstname = firstname;
        this.lastname = lastname;
        this.address1 = address1;
        this.address2 = address2;
        this.city = city;
        this.state = state;
        this.country = country;
        this.zip = zip;
        this.dob = dob;
        this.email = email;
        this.activeflag = activeflag;
        this.phonenumber = phonenumber;
        this.faxnbr = faxnbr;
        this.authreqd = authreqd;
        this.datcreated = datcreated;
        this.makerid = makerid;
        this.branchCode = branchCode;
        this.branchName = branchName;
    }

    /**
     *
     * @return
     */
    public String getIdEntity() {
        return this.idEntity;
    }

    /**
     *
     * @param idEntity
     */
    public void setIdEntity(String idEntity) {
        this.idEntity = idEntity;
    }

    /**
     *
     * @return
     */
    public String getTypeuser() {
        return this.typeuser;
    }

    /**
     *
     * @param typeuser
     */
    public void setTypeuser(String typeuser) {
        this.typeuser = typeuser;
    }

    /**
     *
     * @return
     */
    public String getIduser() {
        return this.iduser;
    }

    /**
     *
     * @param iduser
     */
    public void setIduser(String iduser) {
        this.iduser = iduser;
    }

    /**
     *
     * @return
     */
    public String getNicname() {
        return this.nicname;
    }

    /**
     *
     * @param nicname
     */
    public void setNicname(String nicname) {
        this.nicname = nicname;
    }

    /**
     *
     * @return
     */
    public String getSalution() {
        return this.salution;
    }

    /**
     *
     * @param salution
     */
    public void setSalution(String salution) {
        this.salution = salution;
    }

    /**
     *
     * @return
     */
    public String getFirstname() {
        return this.firstname;
    }

    /**
     *
     * @param firstname
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     *
     * @return
     */
    public String getLastname() {
        return this.lastname;
    }

    /**
     *
     * @param lastname
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     *
     * @return
     */
    public String getAddress1() {
        return this.address1;
    }

    /**
     *
     * @param address1
     */
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    /**
     *
     * @return
     */
    public String getAddress2() {
        return this.address2;
    }

    /**
     *
     * @param address2
     */
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    /**
     *
     * @return
     */
    public String getCity() {
        return this.city;
    }

    /**
     *
     * @param city
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     *
     * @return
     */
    public String getState() {
        return this.state;
    }

    /**
     *
     * @param state
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     *
     * @return
     */
    public String getCountry() {
        return this.country;
    }

    /**
     *
     * @param country
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     *
     * @return
     */
    public String getZip() {
        return this.zip;
    }

    /**
     *
     * @param zip
     */
    public void setZip(String zip) {
        this.zip = zip;
    }

    /**
     *
     * @return
     */
    public Date getDob() {
        return this.dob;
    }

    /**
     *
     * @param dob
     */
    public void setDob(Date dob) {
        this.dob = dob;
    }

    /**
     *
     * @return
     */
    public String getEmail() {
        return this.email;
    }

    /**
     *
     * @param email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     *
     * @return
     */
    public char getActiveflag() {
        return this.activeflag;
    }

    /**
     *
     * @param activeflag
     */
    public void setActiveflag(char activeflag) {
        this.activeflag = activeflag;
    }

    /**
     *
     * @return
     */
    public String getPhonenumber() {
        return this.phonenumber;
    }

    /**
     *
     * @param phonenumber
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     *
     * @return
     */
    public String getFaxnbr() {
        return this.faxnbr;
    }

    /**
     *
     * @param faxnbr
     */
    public void setFaxnbr(String faxnbr) {
        this.faxnbr = faxnbr;
    }

    /**
     *
     * @return
     */
    public char getAuthreqd() {
        return this.authreqd;
    }

    /**
     *
     * @param authreqd
     */
    public void setAuthreqd(char authreqd) {
        this.authreqd = authreqd;
    }

    /**
     *
     * @return
     */
    public Date getDatcreated() {
        return this.datcreated;
    }

    /**
     *
     * @param datcreated
     */
    public void setDatcreated(Date datcreated) {
        this.datcreated = datcreated;
    }

    /**
     *
     * @return
     */
    public String getMakerid() {
        return this.makerid;
    }

    /**
     *
     * @param makerid
     */
    public void setMakerid(String makerid) {
        this.makerid = makerid;
    }

    /**
     *
     * @return
     */
    public String getBranchCode() {
        return this.branchCode;
    }

    /**
     *
     * @param branchCode
     */
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    /**
     *
     * @return
     */
    public String getBranchName() {
        return this.branchName;
    }

    /**
     *
     * @param branchName
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
}
