package scb.com.vn.dbi.dto;

import java.math.BigDecimal;

/**
 * VwWaitapproveBranchId generated by hbm2java
 */
public class VwWaitapproveBranch implements java.io.Serializable {

    private String txncode;
    private String txnname;
    private BigDecimal counttxncode;
    private String branchCodeInit;

    /**
     * Create a new instance of VwWaitapproveBranch
     */
    public VwWaitapproveBranch() {
    }

    /**
     *
     * @param branchCodeInit
     */
    public VwWaitapproveBranch(String branchCodeInit) {
        this.branchCodeInit = branchCodeInit;
    }

    /**
     *
     * @param txncode
     * @param txnname
     * @param counttxncode
     * @param branchCodeInit
     */
    public VwWaitapproveBranch(String txncode, String txnname, BigDecimal counttxncode, String branchCodeInit) {
        this.txncode = txncode;
        this.txnname = txnname;
        this.counttxncode = counttxncode;
        this.branchCodeInit = branchCodeInit;
    }

    /**
     *
     * @return
     */
    public String getTxncode() {
        return this.txncode;
    }

    /**
     *
     * @param txncode
     */
    public void setTxncode(String txncode) {
        this.txncode = txncode;
    }

    /**
     *
     * @return
     */
    public String getTxnname() {
        return this.txnname;
    }

    /**
     *
     * @param txnname
     */
    public void setTxnname(String txnname) {
        this.txnname = txnname;
    }

    /**
     *
     * @return
     */
    public BigDecimal getCounttxncode() {
        return this.counttxncode;
    }

    /**
     *
     * @param counttxncode
     */
    public void setCounttxncode(BigDecimal counttxncode) {
        this.counttxncode = counttxncode;
    }

    /**
     *
     * @return
     */
    public String getBranchCodeInit() {
        return this.branchCodeInit;
    }

    /**
     *
     * @param branchCodeInit
     */
    public void setBranchCodeInit(String branchCodeInit) {
        this.branchCodeInit = branchCodeInit;
    }
}
