package scb.com.vn.dbi.dto;

/**
 * PblPartnerserviceId generated by hbm2java
 */
public class VwWaitapproveId implements java.io.Serializable {

    private String txncode;
    private String id;

    /**
     * Create a new instance of VwWaitapproveId
     */
    public VwWaitapproveId() {
    }

    /**
     *
     * @param txncode
     * @param id
     */
    public VwWaitapproveId(String txncode, String id) {
        this.txncode = txncode;
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getTxncode() {
        return txncode;
    }

    /**
     *
     * @param txncode
     */
    public void setTxncode(String txncode) {
        this.txncode = txncode;
    }

    /**
     *
     * @return
     */
    public String getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(String id) {
        this.id = id;
    }
}
