package scb.com.vn.dbi.dto;

import java.util.Date;

/**
 * VwWaitapprove generated by hbm2java
 */
public class VwWaitapprove implements java.io.Serializable {

    private VwWaitapproveId id;
    private String txnname;
    private String customercode;
    private String idchanneluserInit;
    private Date dateInit;
    private String branchCodeInit;
    private String custAccNo;
    private String custAccName;
    private String active;

    /**
     *
     * @return
     */
    public String getCustAccNo() {
        return custAccNo;
    }

    /**
     *
     * @param custAccNo
     */
    public void setCustAccNo(String custAccNo) {
        this.custAccNo = custAccNo;
    }

    /**
     * Create a new instance of VwWaitapprove
     */
    public VwWaitapprove() {
    }

    /**
     *
     * @param id
     * @param customercode
     * @param idchanneluserInit
     * @param dateInit
     * @param branchCodeInit
     * @param custAccNo
     */
    public VwWaitapprove(VwWaitapproveId id, String customercode, String idchanneluserInit, Date dateInit, String branchCodeInit, String custAccNo) {
        this.id = id;
        this.customercode = customercode;
        this.idchanneluserInit = idchanneluserInit;
        this.dateInit = dateInit;
        this.branchCodeInit = branchCodeInit;
        this.custAccNo = custAccNo;
    }

    /**
     *
     * @return
     */
    public String getTxnname() {
        return this.txnname;
    }

    /**
     *
     * @param txnname
     */
    public void setTxnname(String txnname) {
        this.txnname = txnname;
    }

    /**
     *
     * @return
     */
    public String getCustomercode() {
        return this.customercode;
    }

    /**
     *
     * @param customercode
     */
    public void setCustomercode(String customercode) {
        this.customercode = customercode;
    }

    /**
     *
     * @return
     */
    public String getIdchanneluserInit() {
        return this.idchanneluserInit;
    }

    /**
     *
     * @param idchanneluserInit
     */
    public void setIdchanneluserInit(String idchanneluserInit) {
        this.idchanneluserInit = idchanneluserInit;
    }

    /**
     *
     * @return
     */
    public Date getDateInit() {
        return this.dateInit;
    }

    /**
     *
     * @param dateInit
     */
    public void setDateInit(Date dateInit) {
        this.dateInit = dateInit;
    }

    /**
     *
     * @return
     */
    public String getBranchCodeInit() {
        return this.branchCodeInit;
    }

    /**
     *
     * @param branchCodeInit
     */
    public void setBranchCodeInit(String branchCodeInit) {
        this.branchCodeInit = branchCodeInit;
    }

    /**
     *
     * @return
     */
    public VwWaitapproveId getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(VwWaitapproveId id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getCustAccName() {
        return custAccName;
    }

    /**
     *
     * @param custAccName
     */
    public void setCustAccName(String custAccName) {
        this.custAccName = custAccName;
    }

    /**
     *
     * @return
     */
    public String getActive() {
        return active;
    }

    /**
     *
     * @param active
     */
    public void setActive(String active) {
        this.active = active;
    }
}
